apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: platform
  labels:
    app.kubernetes.io/part-of: jitml
    app.kubernetes.io/name: registry
spec:
  selector:
    app: registry
  ports:
    - name: registry
      port: 5000
      targetPort: registry
