[ "Dense"
, "Embedding"
, "Conv1D"
, "Conv2D"
, "Conv3D"
, "ConvTranspose"
, "ComplexDense"
, "ComplexConv2D"
, "BatchNorm"
, "LayerNorm"
, "GroupNorm"
, "Dropout"
, "ResidualBlock"
, "ScaledDotProductAttention"
, "MultiHeadAttention"
, "RotaryPositionalEmbedding"
]
