apiVersion: apps/v1
kind: Deployment
metadata:
  name: jitml-demo
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jitml-demo
  template:
    metadata:
      labels:
        app: jitml-demo
    spec:
      containers:
        - name: jitml-demo
          image: harbor.platform.svc.cluster.local/jitml/jitml-demo:local
          command: ["jitml-demo"]
          env:
            - name: PORT
              value: "80"
          ports:
            - name: http
              containerPort: 80
