apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: jitml-edge
  namespace: platform
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: NodePort
        externalTrafficPolicy: Cluster
        patch:
          value:
            spec:
              ports:
                - name: http
                  port: 9092
                  nodePort: 30090
      envoyDeployment:
        container:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
