apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: jitml-edge
  namespace: platform
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: NodePort
        externalTrafficPolicy: Cluster
        patch:
          value:
            spec:
              ports:
                - name: http
                  port: 9090
                  nodePort: 30090
      envoyDeployment:
        container:
          resources:
            requests:
              cpu: 50m
              memory: 512Mi
            limits:
              memory: 1Gi
        patch:
          type: StrategicMerge
          value:
            spec:
              template:
                spec:
                  containers:
                    - name: envoy
                      readinessProbe:
                        failureThreshold: 12
                        periodSeconds: 5
                        timeoutSeconds: 10
                      startupProbe:
                        failureThreshold: 60
                        periodSeconds: 10
                        timeoutSeconds: 10
                    - name: shutdown-manager
                      livenessProbe:
                        failureThreshold: 12
                        periodSeconds: 10
                        timeoutSeconds: 5
                      readinessProbe:
                        failureThreshold: 12
                        periodSeconds: 10
                        timeoutSeconds: 5
                      startupProbe:
                        failureThreshold: 60
                        periodSeconds: 10
                        timeoutSeconds: 5
