apiVersion: v1
kind: PersistentVolume
metadata:
  name: platform-pulsar-bookie-ledgers-pv-1
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jitml-manual
  local:
    path: /jitml/.data/platform/pulsar-bookie-ledgers/pv_1/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: Exists
  claimRef:
    namespace: platform
    name: pulsar-bookie-ledgers-pulsar-bookie-1
