apiVersion: v1
kind: PersistentVolume
metadata:
  name: platform-pulsar-zookeeper-data-pv-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jitml-manual
  local:
    path: /jitml/.data/platform/pulsar-zookeeper-data/pv_0/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: Exists
  claimRef:
    namespace: platform
    name: pulsar-zookeeper-data-pulsar-zookeeper-0
