apiVersion: v1
kind: PersistentVolume
metadata:
  name: platform-harbor-pg-pv-2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jitml-manual
  local:
    path: ./.data/platform/harbor-pg/pv_2/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: Exists
  claimRef:
    namespace: platform
    name: data-harbor-pg-2
