apiVersion: v1
kind: PersistentVolume
metadata:
  name: platform-harbor-pg-repo1-pv-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jitml-manual
  local:
    path: /jitml/.data/platform/harbor-pg-repo1/pv_0/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: Exists
