{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE OverloadedStrings #-}

module JitML.Docs.Render
  ( renderBashCompletion
  , renderClusterRoutes
  , renderDaemonSurface
  , renderFishCompletion
  , renderGeneratedSectionIndex
  , renderHelpBlocks
  , renderManpage
  , renderMarkdownReference
  , renderNumericsActivations
  , renderNumericsLayers
  , renderNumericsLosses
  , renderNumericsOptimizers
  , renderNumericsSchedulers
  , renderNumericsSpectral
  , renderReadmeCommandRegistry
  , renderReadmeCommandTree
  , renderTrainingRlCatalog
  , renderTrainingTunePruners
  , renderTrainingTuneSamplers
  , renderTrainingTuneSchedulers
  , renderZshCompletion
  )
where

import Data.Char (toUpper)
import Data.Text (Text)
import Data.Text qualified as Text

import JitML.CLI.Help (renderCommandHelp)
import JitML.CLI.Spec
  ( CommandSpec (..)
  , Example (..)
  , OptionKind (..)
  , OptionSpec (..)
  , commandLeaves
  , commandPathText
  , commandRegistry
  , commandUsage
  )
import JitML.Numerics.Catalog qualified as Numerics
import JitML.RL.Algorithms qualified as RL
import JitML.RL.Algorithms.Common qualified as RLCommon
import JitML.RL.Algorithms.Registry qualified as RLRegistry
import JitML.Routes qualified as Routes
import JitML.Tune.Catalog qualified as Tune

renderReadmeCommandTree :: Text
renderReadmeCommandTree =
  Text.unlines $
    [ "```mermaid"
    , "mindmap"
    , "  root((jitml))"
    ]
      <> concatMap (renderMindmapNode 2) (children commandRegistry)
      <> ["```"]

renderReadmeCommandRegistry :: Text
renderReadmeCommandRegistry =
  Text.unlines $
    [ "| Command | Summary | Usage |"
    , "|---------|---------|-------|"
    ]
      <> fmap registryRow (commandLeaves commandRegistry)

renderMarkdownReference :: Text
renderMarkdownReference =
  Text.unlines $
    [ "# jitML CLI Command Reference"
    , ""
    , "**Status**: Reference only"
    , "**Supersedes**: N/A"
    , "**Referenced by**: ../../README.md, ../engineering/cli_command_surface.md, ../../DEVELOPMENT_PLAN/phase-1-haskell-cli-surface.md"
    , "**Generated sections**: none"
    , ""
    , "> **Purpose**: Fully generated command reference rendered from `CommandSpec`."
    , ""
    , "_This file is fully generated by `jitml docs generate`; do not hand edit._"
    , ""
    ]
      <> concatMap commandReference (commandLeaves commandRegistry)

renderHelpBlocks :: Text
renderHelpBlocks =
  Text.intercalate "\n" (fmap helpBlock (commandLeaves commandRegistry))

renderGeneratedSectionIndex :: Text
renderGeneratedSectionIndex =
  Text.unlines
    [ "| Generation target | Marker key prefix | Owning sprint |"
    , "|-------------------|-------------------|---------------|"
    , "| Root README command tree and command registry | `command-tree`, `command-registry` | Sprint 1.2 / Sprint 1.3 |"
    , "| CLI command reference | `cli-commands.reference`, `cli-commands.help-blocks` | Sprint 1.2 / Sprint 1.3 |"
    , "| Generated section index in this file | `documentation-standards.generated-section-index` | Sprint 1.3 |"
    , "| Cluster route table | `cluster.routes` | Sprint 3.4 |"
    , "| Numerical-core catalog tables | `numerics.layers`, `numerics.activations`, `numerics.spectral`, `numerics.optimizers`, `numerics.schedulers`, `numerics.losses` | Sprint 6.1 / 6.2 / 6.3 / 6.4 / 6.5 / 6.6 |"
    , "| Daemon endpoint and config table | `daemon.surface` | Sprint 5.3 |"
    , "| RL algorithm catalog table | `training.rl.catalog` | Sprint 9.3 |"
    , "| Hyperparameter tuning tables | `training.tune.samplers`, `training.tune.schedulers`, `training.tune.pruners` | Sprint 9.7 |"
    , "| PureScript contract file | `web.contracts.purescript` | Sprint 11.2 |"
    , "| Chart HTTPRoutes | `chart.routes.*` | Sprint 3.4 |"
    , "| Grafana dashboard ConfigMaps | `chart.grafana.*` | Sprint 4.5 |"
    , "| Prometheus scrape config | `chart.prometheus.scrape` | Sprint 4.5 |"
    , "| Cross-language types (TypeScript / PureScript mirrors of Haskell ADTs) | `cross-language-types.*` | Sprint 11.2 |"
    ]

renderClusterRoutes :: Text
renderClusterRoutes = Routes.renderRouteTable

renderNumericsLayers :: Text
renderNumericsLayers = renderCurrentScopeTable "Constructor" (fmap showText Numerics.layerCatalog)

renderNumericsActivations :: Text
renderNumericsActivations =
  Text.unlines $
    [ "| Real-valued | Complex-valued |"
    , "|-------------|----------------|"
    ]
      <> zipActivationRows realActivations complexActivations
 where
  names = fmap showText Numerics.activationCatalog
  realActivations = filter (not . Text.isPrefixOf "Complex") names
  complexActivations = filter (Text.isPrefixOf "Complex") names

renderNumericsSpectral :: Text
renderNumericsSpectral = renderCurrentScopeTable "Constructor" (fmap showText Numerics.spectralCatalog)

renderNumericsOptimizers :: Text
renderNumericsOptimizers = renderCurrentScopeTable "Constructor" (fmap showText Numerics.optimizerCatalog)

renderNumericsSchedulers :: Text
renderNumericsSchedulers = renderCurrentScopeTable "Constructor" (fmap showText Numerics.schedulerCatalog)

renderNumericsLosses :: Text
renderNumericsLosses = renderCurrentScopeTable "Constructor" (fmap showText Numerics.lossCatalog)

renderDaemonSurface :: Text
renderDaemonSurface =
  Text.unlines
    [ "| Surface | Current owner | Current behavior |"
    , "|---------|---------------|------------------|"
    , "| `/healthz` | `JitML.Service.Runtime.daemonHttpRoutes` | Served by the in-binary HTTP runtime as a `200` response body |"
    , "| `/readyz` | `JitML.Service.Runtime.daemonHttpRoutes` | Served by the in-binary HTTP runtime with ready/not-ready status |"
    , "| `/metrics` | `JitML.Service.Runtime.daemonHttpRoutes` | Served by the in-binary HTTP runtime as Prometheus text |"
    , "| `BootConfig` | `JitML.Service.BootConfig` and `dhall/service/BootConfig.dhall` | Cluster/host residency, inference mode, Pulsar, MinIO, Harbor, HTTP listener fields |"
    , "| `LiveConfig` | `JitML.Service.LiveConfig` and `dhall/service/LiveConfig.dhall` | Log level, retry policy, inference batching/SLO, dedup cache size/TTL, drain deadline fields |"
    , "| SIGHUP reload decision | `JitML.Service.HotReload` | Pure reload/ignore/restart-required decision surface |"
    , "| POSIX signal wiring | `JitML.Service.Signal` and `JitML.Service.Runtime` | SIGHUP increments reload generation; SIGINT/SIGTERM begin graceful drain and drop readiness |"
    , "| Consumer idempotency | `JitML.Service.Consumer` | Pure payload-hash deduplication surface |"
    , "| HTTP listener | `JitML.Service.Http` | Low-level typed route server shared by `jitml service` and `jitml-demo` one-shot tests |"
    ]

renderTrainingRlCatalog :: Text
renderTrainingRlCatalog =
  Text.unlines $
    [ "| Algorithm | Family | Replay-backed | Hyperparameters | Module |"
    , "|-----------|--------|---------------|-----------------|--------|"
    ]
      <> fmap rlAlgorithmRow RL.algorithmCatalog

renderTrainingTuneSamplers :: Text
renderTrainingTuneSamplers = renderCurrentScopeTable "Constructor" (fmap showText Tune.samplerCatalog)

renderTrainingTuneSchedulers :: Text
renderTrainingTuneSchedulers = renderCurrentScopeTable "Constructor" (fmap showText Tune.schedulerCatalog)

renderTrainingTunePruners :: Text
renderTrainingTunePruners = renderCurrentScopeTable "Constructor" (fmap showText Tune.prunerCatalog)

renderCurrentScopeTable :: Text -> [Text] -> Text
renderCurrentScopeTable label values =
  Text.unlines $
    [ "| " <> label <> " | Current scope |"
    , "|-------------|---------------|"
    ]
      <> fmap (\value -> "| `" <> value <> "` | Generated from current Haskell catalog |") values

zipActivationRows :: [Text] -> [Text] -> [Text]
zipActivationRows left right =
  [ "| " <> renderCell realValue <> " | " <> renderCell complexValue <> " |"
  | (realValue, complexValue) <- zipPad left right
  ]

zipPad :: [Text] -> [Text] -> [(Maybe Text, Maybe Text)]
zipPad [] [] = []
zipPad (left : leftRest) [] = (Just left, Nothing) : zipPad leftRest []
zipPad [] (right : rightRest) = (Nothing, Just right) : zipPad [] rightRest
zipPad (left : leftRest) (right : rightRest) = (Just left, Just right) : zipPad leftRest rightRest

renderCell :: Maybe Text -> Text
renderCell Nothing = ""
renderCell (Just value) = "`" <> value <> "`"

rlAlgorithmRow :: RL.RLAlgorithm -> Text
rlAlgorithmRow algorithm =
  Text.intercalate
    " | "
    [ "| `" <> RL.algorithmName algorithm <> "`"
    , Text.pack (show (RL.algorithmFamily algorithm))
    , if RL.algorithmReplayBased algorithm then "yes" else "no"
    , Text.pack (show (rlAlgorithmHyperCount (RL.algorithmName algorithm)))
    , rlAlgorithmModulePath (RL.algorithmName algorithm) <> " |"
    ]

-- | Lookup the per-module hyperparameter count from
-- 'JitML.RL.Algorithms.Registry'. Algorithms without a dedicated module
-- (currently @AlphaZero@, which has its own @AlphaZero@ substack) report @0@
-- so the generated table stays per-row-stable.
rlAlgorithmHyperCount :: Text -> Int
rlAlgorithmHyperCount name =
  case RLRegistry.moduleFor name of
    Just m -> length (RLCommon.moduleHyperparameters m)
    Nothing -> 0

rlAlgorithmModulePath :: Text -> Text
rlAlgorithmModulePath name =
  case RLRegistry.moduleFor name of
    Just _ -> "`src/JitML/RL/Algorithms/" <> rlAlgorithmModuleFileName name <> ".hs`"
    Nothing -> "`src/JitML/RL/AlphaZero/`"

rlAlgorithmModuleFileName :: Text -> Text
rlAlgorithmModuleFileName name =
  case Text.unpack name of
    "QR-DQN" -> "QrDqn"
    "MaskablePPO" -> "MaskablePpo"
    "RecurrentPPO" -> "RecurrentPpo"
    "TRPO" -> "Trpo"
    "DDPG" -> "Ddpg"
    "TD3" -> "Td3"
    "SAC" -> "Sac"
    "DQN" -> "Dqn"
    "PPO" -> "Ppo"
    "A2C" -> "A2c"
    "CrossQ" -> "CrossQ"
    "TQC" -> "Tqc"
    "ARS" -> "Ars"
    "HER" -> "Her"
    other -> Text.pack other

showText :: (Show value) => value -> Text
showText = Text.pack . show

renderManpage :: Text
renderManpage =
  Text.unlines $
    [ ".TH JITML 1"
    , ".SH NAME"
    , "jitml \\- deterministic, reproducible, JIT-compiled machine learning"
    , ".SH SYNOPSIS"
    , ".B jitml"
    , "COMMAND [OPTIONS]"
    , ".SH DESCRIPTION"
    , "The jitml command surface is generated from the CommandSpec registry."
    , ".SH COMMANDS"
    ]
      <> concatMap manpageCommand (commandLeaves commandRegistry)

renderBashCompletion :: Text
renderBashCompletion =
  Text.unlines
    [ "# Generated by jitml docs generate; do not hand edit."
    , "_jitml_completions()"
    , "{"
    , "  local current=\"${COMP_WORDS[COMP_CWORD]}\""
    , "  COMPREPLY=( $(compgen -W '" <> completionWords <> "' -- \"$current\") )"
    , "}"
    , "complete -F _jitml_completions jitml"
    ]

renderZshCompletion :: Text
renderZshCompletion =
  Text.unlines
    [ "#compdef jitml"
    , "# Generated by jitml docs generate; do not hand edit."
    , "_arguments '*::command:(" <> completionWords <> ")'"
    ]

renderFishCompletion :: Text
renderFishCompletion =
  Text.unlines $
    "# Generated by jitml docs generate; do not hand edit."
      : fmap fishCommand (commandLeaves commandRegistry)

renderMindmapNode :: Int -> CommandSpec -> [Text]
renderMindmapNode depth spec =
  let line = Text.replicate depth "  " <> name spec
   in line : concatMap (renderMindmapNode (depth + 1)) (children spec)

registryRow :: ([Text], CommandSpec) -> Text
registryRow (path, spec) =
  Text.intercalate
    " | "
    [ "| `" <> escapeTableCell (commandPathText path) <> "`"
    , escapeTableCell (summary spec)
    , "`" <> escapeTableCell (commandUsage path spec) <> "` |"
    ]

commandReference :: ([Text], CommandSpec) -> [Text]
commandReference (path, spec) =
  [ "## `" <> commandPathText path <> "`"
  , ""
  , summary spec
  , ""
  , commandDescription spec
  , ""
  , "```text"
  , commandUsage path spec
  , "```"
  , ""
  ]
    <> optionTable (options spec)
    <> exampleList (examples spec)

optionTable :: [OptionSpec] -> [Text]
optionTable [] = []
optionTable commandOptions =
  [ "| Option | Kind | Required | Description |"
  , "|--------|------|----------|-------------|"
  ]
    <> fmap optionRow commandOptions
    <> [""]

optionRow :: OptionSpec -> Text
optionRow option =
  Text.intercalate
    " | "
    [ "| `" <> escapeTableCell (optionLabel option) <> "`"
    , optionKindText (optionKind option)
    , if required option then "yes" else "no"
    , escapeTableCell (optionDescription option) <> " |"
    ]

exampleList :: [Example] -> [Text]
exampleList [] = []
exampleList commandExamples =
  [ "Examples:"
  , ""
  ]
    <> concatMap exampleLines commandExamples
    <> [""]

exampleLines :: Example -> [Text]
exampleLines example =
  [ "```text"
  , exampleCommand example
  , "```"
  , ""
  , exampleDescription example
  , ""
  ]

helpBlock :: ([Text], CommandSpec) -> Text
helpBlock (path, spec) =
  Text.unlines
    [ "### `" <> commandPathText path <> "`"
    , ""
    , "```text"
    , renderCommandHelp path spec
    , "```"
    ]

manpageCommand :: ([Text], CommandSpec) -> [Text]
manpageCommand (path, spec) =
  [ ".SS " <> roffUpper (commandPathText path)
  , roffEscape (summary spec)
  , ".PP"
  , ".B " <> roffEscape (commandUsage path spec)
  ]

fishCommand :: ([Text], CommandSpec) -> Text
fishCommand (path, spec) =
  "complete -c jitml -a '" <> Text.unwords path <> "' -d '" <> shellEscapeSingle (summary spec) <> "'"

completionWords :: Text
completionWords =
  Text.unwords (fmap commandPathForCompletion (commandLeaves commandRegistry))

commandPathForCompletion :: ([Text], CommandSpec) -> Text
commandPathForCompletion (path, _) = Text.intercalate ":" path

optionLabel :: OptionSpec -> Text
optionLabel option =
  case optionKind option of
    FlagOption -> "--" <> longName option
    ValueOption -> "--" <> longName option <> " <" <> metavarText option <> ">"
    PositionalOption -> "<" <> metavarText option <> ">"
    RemainderOption -> "-- <" <> metavarText option <> "...>"

metavarText :: OptionSpec -> Text
metavarText option =
  case metavar option of
    Just value -> value
    Nothing -> longName option

optionKindText :: OptionKind -> Text
optionKindText FlagOption = "flag"
optionKindText ValueOption = "value"
optionKindText PositionalOption = "positional"
optionKindText RemainderOption = "remainder"

commandDescription :: CommandSpec -> Text
commandDescription CommandSpec {description = value} = value

optionDescription :: OptionSpec -> Text
optionDescription OptionSpec {description = value} = value

roffUpper :: Text -> Text
roffUpper = Text.map toUpper

roffEscape :: Text -> Text
roffEscape =
  Text.replace "\\" "\\\\"
    . Text.replace "-" "\\-"

shellEscapeSingle :: Text -> Text
shellEscapeSingle =
  Text.replace "'" "'\\''"

escapeTableCell :: Text -> Text
escapeTableCell =
  Text.replace "|" "\\|"
