apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: jitml
  namespace: platform
  labels:
    release: kube-prometheus-stack
spec:
  staticConfigs:
    - targets:
        - jitml-service.platform.svc.cluster.local:8080
