services:
  jitml:
    image: jitml:local
    build:
      context: ..
      dockerfile: docker/Dockerfile
    working_dir: /jitml
    volumes:
      - ..:/jitml
      - /var/run/docker.sock:/var/run/docker.sock
