apiVersion: v1
kind: ServiceAccount
metadata:
  name: jitml-engine
  namespace: platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jitml-coordinator
  namespace: platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jitml-coordinator
  namespace: platform
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jitml-coordinator
  namespace: platform
subjects:
  - kind: ServiceAccount
    name: jitml-coordinator
    namespace: platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jitml-coordinator
