{-# LANGUAGE OverloadedStrings #-}

module JitML.Codegen.Cuda
  ( renderCudaSource
  , renderCudaFamilySource
  )
where

import Data.Text (Text)
import Data.Text qualified as Text

import JitML.Cache.Key (KernelSpec (..), Kind, TuningChoice (..), kindText)
import JitML.Codegen.KernelFamily (KernelFamily (..), familyName)
import JitML.Codegen.SourceFile (SourceFile (..))

renderCudaSource :: KernelSpec -> Kind -> TuningChoice -> [SourceFile]
renderCudaSource = renderCudaFamilySource Identity

renderCudaFamilySource
  :: KernelFamily -> KernelSpec -> Kind -> TuningChoice -> [SourceFile]
renderCudaFamilySource family kernelSpec kind tuningChoice =
  [ SourceFile "kernel.cu" (cudaSource family kernelSpec kind tuningChoice)
  ]

cudaSource :: KernelFamily -> KernelSpec -> Kind -> TuningChoice -> Text
cudaSource family kernelSpec kind tuningChoice =
  Text.unlines
    [ "// Generated by jitml. Do not check generated CUDA source into git."
    , "#include <cstddef>"
    , "#include <cstdio>"
    , "#include <cstdlib>"
    , "#include <cuda_runtime.h>"
    , "#ifdef JITML_USE_CUDNN"
    , "#include <cudnn.h>"
    , "#endif"
    , "#ifdef JITML_USE_CUBLAS"
    , "#include <cublas_v2.h>"
    , "#endif"
    , ""
    , "static const char *jitml_kernel_spec = " <> cString (kernelSpecPayload kernelSpec) <> ";"
    , "static const char *jitml_kernel_kind = " <> cString (kindText kind) <> ";"
    , "static const char *jitml_tuning_choice = " <> cString (unTuningChoice tuningChoice) <> ";"
    , "static const char *jitml_kernel_family = " <> cString (familyName family) <> ";"
    , "static const char *jitml_cudnn_algorithm = " <> cString (cudnnDeterministicAlgorithm family) <> ";"
    , "static const char *jitml_rng_policy = \"host-splitmix64-no-curand\";"
    , "// determinism: --use_fast_math=false; TF32 disabled; warp-shuffle reductions"
    , ""
    , kernelOutputCountFunction family
    , ""
    , cudaRuntimeHelpers
    , ""
    , familyImpl family
    , ""
    , weightedFamilyImpl family
    , ""
    , "extern \"C\" const char *jitml_kernel_family_name(void) { return jitml_kernel_family; }"
    ]

familyImpl :: KernelFamily -> Text
familyImpl Identity =
  identityLikeFamilyImpl
    "jitml_device_identity"
    "// Identity CUDA kernel. The extern-C host wrapper owns device allocation and readback."
familyImpl Reduction =
  Text.unlines
    [ "// Deterministic warp-shuffle reduction kernel. One partial is emitted per"
    , "// warp, and the host accumulates those partials in canonical index order."
    , "static __global__ void jitml_device_reduction(float *partials, const float *input, std::size_t n) {"
    , "  int tid = threadIdx.x;"
    , "  int warp = tid / warpSize;"
    , "  std::size_t idx = static_cast<std::size_t>(blockIdx.x) * blockDim.x + tid;"
    , "  float v = idx < n ? input[idx] : 0.0f;"
    , "  for (int offset = warpSize / 2; offset > 0; offset >>= 1) {"
    , "    v += __shfl_down_sync(0xFFFFFFFFu, v, offset);"
    , "  }"
    , "  if ((tid & (warpSize - 1)) == 0) {"
    , "    int warpsPerBlock = blockDim.x / warpSize;"
    , "    partials[blockIdx.x * warpsPerBlock + warp] = v;"
    , "  }"
    , "}"
    , ""
    , "static void jitml_launch_device(float *partials, const float *input, std::size_t n) {"
    , "  dim3 block(256);"
    , "  std::size_t gridCount = (n + block.x - 1) / block.x;"
    , "  dim3 grid(static_cast<unsigned int>(gridCount));"
    , "  jitml_device_reduction<<<grid, block>>>(partials, input, n);"
    , "}"
    , ""
    , "extern \"C\" void jitml_kernel(float *out, const float *input, std::size_t n) {"
    , "  jitml_cuda_copy_and_launch(out, input, n, jitml_kernel_output_count(n), jitml_launch_device);"
    , "}"
    ]
familyImpl Dense2D =
  identityLikeFamilyImpl
    "jitml_device_dense"
    "// cuBLAS-backed GEMM scaffold. The current host wrapper uses deterministic device readback."
familyImpl Conv2DKernel =
  identityLikeFamilyImpl
    "jitml_device_conv2d"
    ( Text.unlines
        [ "// cuDNN-backed Conv2D scaffold. Real driver pins"
        , "// CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM (deterministic)."
        ]
    )
familyImpl Conv3DKernel =
  identityLikeFamilyImpl
    "jitml_device_conv3d"
    ( Text.unlines
        [ "// cuDNN-backed Conv3D scaffold. Real driver pins"
        , "// CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM (deterministic)."
        ]
    )
familyImpl BatchNormKernel =
  identityLikeFamilyImpl
    "jitml_device_batchnorm"
    "// cuDNN Spatial BN scaffold. Inference path uses pre-baked stats."
familyImpl LayerNormKernel =
  identityLikeFamilyImpl
    "jitml_device_layernorm"
    "// LayerNorm scaffold. Inference path uses pre-baked stats."
familyImpl MultiHeadAttentionKernel =
  identityLikeFamilyImpl
    "jitml_device_mha"
    ( Text.unlines
        [ "// MHA scaffold. Real driver chains cublasSgemm for QKV linear and the output"
        , "// projection, plus deterministic softmax via warp-shuffle reductions."
        ]
    )
familyImpl EmbeddingKernel =
  identityLikeFamilyImpl
    "jitml_device_embedding"
    "// Embedding scaffold. The current host wrapper uses deterministic device readback."

identityLikeFamilyImpl :: Text -> Text -> Text
identityLikeFamilyImpl deviceKernelName comment =
  Text.unlines
    [ comment
    , "static __global__ void " <> deviceKernelName <> "(float *out, const float *input, std::size_t n) {"
    , "  std::size_t i = static_cast<std::size_t>(blockIdx.x) * blockDim.x + threadIdx.x;"
    , "  if (i < n) { out[i] = input[i]; }"
    , "}"
    , ""
    , "static void jitml_launch_device(float *out, const float *input, std::size_t n) {"
    , "  dim3 block(256);"
    , "  std::size_t gridCount = (n + block.x - 1) / block.x;"
    , "  dim3 grid(static_cast<unsigned int>(gridCount));"
    , "  " <> deviceKernelName <> "<<<grid, block>>>(out, input, n);"
    , "}"
    , ""
    , "extern \"C\" void jitml_kernel(float *out, const float *input, std::size_t n) {"
    , "  jitml_cuda_copy_and_launch(out, input, n, jitml_kernel_output_count(n), jitml_launch_device);"
    , "}"
    ]

-- | Sprint 13.11 — CUDA weighted kernel ABI. Dense2D drives a real
-- device GEMM (`out = input · W`) against the caller-supplied
-- row-major weights buffer (n*n entries, padded with zeros / truncated
-- to fit). Other families fall through to the existing unweighted
-- body — the per-family weighted CUDA ABIs land alongside the broader
-- Sprint 13.11 follow-up tracked in the sprint's Remaining Work.
weightedFamilyImpl :: KernelFamily -> Text
weightedFamilyImpl Dense2D =
  Text.unlines
    [ "// Sprint 13.11 — real-weighted Dense2D device GEMM. Each output"
    , "// row computes `out[i] = sum_j input[j] * W[j * n + i]` against"
    , "// the supplied weights buffer (padded with zero for indices"
    , "// >= weights_count). Single-warp launch per output element keeps"
    , "// the reduction order deterministic; warp-shuffle isn't needed"
    , "// because each thread accumulates its own column."
    , "static __global__ void jitml_device_dense_weighted("
    , "    float *out, const float *input, std::size_t n,"
    , "    const float *weights, std::size_t weights_count) {"
    , "  std::size_t i = static_cast<std::size_t>(blockIdx.x) * blockDim.x + threadIdx.x;"
    , "  if (i >= n) { return; }"
    , "  float acc = 0.0f;"
    , "  for (std::size_t j = 0; j < n; ++j) {"
    , "    std::size_t idx = j * n + i;"
    , "    float w = (idx < weights_count && weights != nullptr) ? weights[idx] : 0.0f;"
    , "    acc += input[j] * w;"
    , "  }"
    , "  out[i] = acc;"
    , "}"
    , ""
    , "static void jitml_launch_device_weighted("
    , "    float *out, const float *input, std::size_t n,"
    , "    const float *weights, std::size_t weights_count) {"
    , "  dim3 block(256);"
    , "  std::size_t gridCount = (n + block.x - 1) / block.x;"
    , "  dim3 grid(static_cast<unsigned int>(gridCount));"
    , "  jitml_device_dense_weighted<<<grid, block>>>(out, input, n, weights, weights_count);"
    , "}"
    , ""
    , "extern \"C\" void jitml_weighted_kernel("
    , "    float *out, const float *input, std::size_t n,"
    , "    const float *weights, std::size_t weights_count) {"
    , "  jitml_cuda_copy_and_launch_weighted("
    , "      out, input, n, weights, weights_count,"
    , "      jitml_kernel_output_count(n), jitml_launch_device_weighted);"
    , "}"
    ]
weightedFamilyImpl Conv2DKernel =
  -- Sprint 13.11 — CUDA-side weighted 1x1 Conv2D. Per-position multiply
  -- by weights[0] (single 1x1 filter coefficient). Output equals input
  -- when weights_count == 0 (filter defaults to 1.0).
  Text.unlines
    [ "static __global__ void jitml_device_conv2d_weighted("
    , "    float *out, const float *input, std::size_t n,"
    , "    const float *weights, std::size_t weights_count) {"
    , "  std::size_t i = static_cast<std::size_t>(blockIdx.x) * blockDim.x + threadIdx.x;"
    , "  if (i >= n) { return; }"
    , "  float w = (weights_count > 0 && weights != nullptr) ? weights[0] : 1.0f;"
    , "  out[i] = input[i] * w;"
    , "}"
    , ""
    , "static void jitml_launch_conv2d_weighted("
    , "    float *out, const float *input, std::size_t n,"
    , "    const float *weights, std::size_t weights_count) {"
    , "  dim3 block(256);"
    , "  dim3 grid(static_cast<unsigned int>((n + block.x - 1) / block.x));"
    , "  jitml_device_conv2d_weighted<<<grid, block>>>(out, input, n, weights, weights_count);"
    , "}"
    , ""
    , "extern \"C\" void jitml_weighted_kernel("
    , "    float *out, const float *input, std::size_t n,"
    , "    const float *weights, std::size_t weights_count) {"
    , "  jitml_cuda_copy_and_launch_weighted("
    , "      out, input, n, weights, weights_count,"
    , "      jitml_kernel_output_count(n), jitml_launch_conv2d_weighted);"
    , "}"
    ]
weightedFamilyImpl Conv3DKernel =
  Text.unlines
    [ "static __global__ void jitml_device_conv3d_weighted("
    , "    float *out, const float *input, std::size_t n,"
    , "    const float *weights, std::size_t weights_count) {"
    , "  std::size_t i = static_cast<std::size_t>(blockIdx.x) * blockDim.x + threadIdx.x;"
    , "  if (i >= n) { return; }"
    , "  float w = (weights_count > 0 && weights != nullptr) ? weights[0] : 1.0f;"
    , "  out[i] = input[i] * w;"
    , "}"
    , ""
    , "static void jitml_launch_conv3d_weighted("
    , "    float *out, const float *input, std::size_t n,"
    , "    const float *weights, std::size_t weights_count) {"
    , "  dim3 block(256);"
    , "  dim3 grid(static_cast<unsigned int>((n + block.x - 1) / block.x));"
    , "  jitml_device_conv3d_weighted<<<grid, block>>>(out, input, n, weights, weights_count);"
    , "}"
    , ""
    , "extern \"C\" void jitml_weighted_kernel("
    , "    float *out, const float *input, std::size_t n,"
    , "    const float *weights, std::size_t weights_count) {"
    , "  jitml_cuda_copy_and_launch_weighted("
    , "      out, input, n, weights, weights_count,"
    , "      jitml_kernel_output_count(n), jitml_launch_conv3d_weighted);"
    , "}"
    ]
weightedFamilyImpl BatchNormKernel =
  -- Sprint 13.11 — CUDA weighted BatchNorm. Weights buffer carries
  -- [scale(n), shift(n), mean(n), variance(n)] with missing entries
  -- defaulting to canonical no-op values.
  Text.unlines
    [ "static __global__ void jitml_device_batchnorm_weighted("
    , "    float *out, const float *input, std::size_t n,"
    , "    const float *weights, std::size_t weights_count) {"
    , "  std::size_t i = static_cast<std::size_t>(blockIdx.x) * blockDim.x + threadIdx.x;"
    , "  if (i >= n) { return; }"
    , "  float scale = (i < weights_count && weights != nullptr) ? weights[i] : 1.0f;"
    , "  float shift = (n + i < weights_count && weights != nullptr) ? weights[n + i] : 0.0f;"
    , "  float mean = (2 * n + i < weights_count && weights != nullptr) ? weights[2 * n + i] : 0.0f;"
    , "  float var = (3 * n + i < weights_count && weights != nullptr) ? weights[3 * n + i] : 1.0f;"
    , "  float eps = 1.0e-5f;"
    , "  float normalised = (input[i] - mean) / sqrtf(var + eps);"
    , "  out[i] = normalised * scale + shift;"
    , "}"
    , ""
    , "static void jitml_launch_batchnorm_weighted("
    , "    float *out, const float *input, std::size_t n,"
    , "    const float *weights, std::size_t weights_count) {"
    , "  dim3 block(256);"
    , "  dim3 grid(static_cast<unsigned int>((n + block.x - 1) / block.x));"
    , "  jitml_device_batchnorm_weighted<<<grid, block>>>(out, input, n, weights, weights_count);"
    , "}"
    , ""
    , "extern \"C\" void jitml_weighted_kernel("
    , "    float *out, const float *input, std::size_t n,"
    , "    const float *weights, std::size_t weights_count) {"
    , "  jitml_cuda_copy_and_launch_weighted("
    , "      out, input, n, weights, weights_count,"
    , "      jitml_kernel_output_count(n), jitml_launch_batchnorm_weighted);"
    , "}"
    ]
weightedFamilyImpl LayerNormKernel =
  -- Sprint 13.11 — CUDA weighted LayerNorm. Weights buffer carries
  -- [scale(n), shift(n)]. Per-element normalization uses the input's
  -- own mean/variance computed in a single sweep.
  Text.unlines
    [ "static __global__ void jitml_device_layernorm_weighted("
    , "    float *out, const float *input, std::size_t n,"
    , "    const float *weights, std::size_t weights_count) {"
    , "  std::size_t i = static_cast<std::size_t>(blockIdx.x) * blockDim.x + threadIdx.x;"
    , "  if (i >= n) { return; }"
    , "  float sum = 0.0f;"
    , "  for (std::size_t j = 0; j < n; ++j) { sum += input[j]; }"
    , "  float mean = sum / static_cast<float>(n);"
    , "  float varSum = 0.0f;"
    , "  for (std::size_t j = 0; j < n; ++j) { float d = input[j] - mean; varSum += d * d; }"
    , "  float var = varSum / static_cast<float>(n);"
    , "  float eps = 1.0e-5f;"
    , "  float scale = (i < weights_count && weights != nullptr) ? weights[i] : 1.0f;"
    , "  float shift = (n + i < weights_count && weights != nullptr) ? weights[n + i] : 0.0f;"
    , "  out[i] = ((input[i] - mean) / sqrtf(var + eps)) * scale + shift;"
    , "}"
    , ""
    , "static void jitml_launch_layernorm_weighted("
    , "    float *out, const float *input, std::size_t n,"
    , "    const float *weights, std::size_t weights_count) {"
    , "  dim3 block(256);"
    , "  dim3 grid(static_cast<unsigned int>((n + block.x - 1) / block.x));"
    , "  jitml_device_layernorm_weighted<<<grid, block>>>(out, input, n, weights, weights_count);"
    , "}"
    , ""
    , "extern \"C\" void jitml_weighted_kernel("
    , "    float *out, const float *input, std::size_t n,"
    , "    const float *weights, std::size_t weights_count) {"
    , "  jitml_cuda_copy_and_launch_weighted("
    , "      out, input, n, weights, weights_count,"
    , "      jitml_kernel_output_count(n), jitml_launch_layernorm_weighted);"
    , "}"
    ]
weightedFamilyImpl EmbeddingKernel =
  -- Sprint 13.11 — CUDA weighted Embedding lookup. Weights buffer is
  -- a row-major embedding table of length table_rows * n; the input
  -- supplies the (unsigned) row indices.
  Text.unlines
    [ "static __global__ void jitml_device_embedding_weighted("
    , "    float *out, const float *input, std::size_t n,"
    , "    const float *weights, std::size_t weights_count) {"
    , "  std::size_t i = static_cast<std::size_t>(blockIdx.x) * blockDim.x + threadIdx.x;"
    , "  if (i >= n) { return; }"
    , "  if (weights_count == 0 || weights == nullptr) { out[i] = input[i]; return; }"
    , "  std::size_t table_rows = weights_count / n;"
    , "  if (table_rows == 0) { table_rows = 1; }"
    , "  float idx = input[i] < 0.0f ? 0.0f : input[i];"
    , "  std::size_t row = static_cast<std::size_t>(idx) % table_rows;"
    , "  std::size_t off = row * n + i;"
    , "  out[i] = (off < weights_count) ? weights[off] : 0.0f;"
    , "}"
    , ""
    , "static void jitml_launch_embedding_weighted("
    , "    float *out, const float *input, std::size_t n,"
    , "    const float *weights, std::size_t weights_count) {"
    , "  dim3 block(256);"
    , "  dim3 grid(static_cast<unsigned int>((n + block.x - 1) / block.x));"
    , "  jitml_device_embedding_weighted<<<grid, block>>>(out, input, n, weights, weights_count);"
    , "}"
    , ""
    , "extern \"C\" void jitml_weighted_kernel("
    , "    float *out, const float *input, std::size_t n,"
    , "    const float *weights, std::size_t weights_count) {"
    , "  jitml_cuda_copy_and_launch_weighted("
    , "      out, input, n, weights, weights_count,"
    , "      jitml_kernel_output_count(n), jitml_launch_embedding_weighted);"
    , "}"
    ]
weightedFamilyImpl MultiHeadAttentionKernel =
  -- Sprint 13.11 — CUDA weighted MHA. Weights buffer holds three
  -- consecutive n*n blocks (Wq, Wk, Wv). Computes
  -- out[i] = sum_j (q[j] * k[j] * Wv[j*n+i])
  -- where q = input·Wq and k = input·Wk. No softmax (determinism
  -- contract requires fixed-precision reduction; softmax introduces
  -- a cross-substrate ULP gap).
  Text.unlines
    [ "static __global__ void jitml_device_mha_weighted("
    , "    float *out, const float *input, std::size_t n,"
    , "    const float *weights, std::size_t weights_count) {"
    , "  std::size_t i = static_cast<std::size_t>(blockIdx.x) * blockDim.x + threadIdx.x;"
    , "  if (i >= n) { return; }"
    , "  std::size_t block_size = n * n;"
    , "  float v = 0.0f;"
    , "  for (std::size_t j = 0; j < n; ++j) {"
    , "    float qsum = 0.0f, ksum = 0.0f;"
    , "    for (std::size_t k = 0; k < n; ++k) {"
    , "      std::size_t qi = k * n + j;"
    , "      std::size_t ki = block_size + k * n + j;"
    , "      float wq = (qi < weights_count && weights != nullptr) ? weights[qi] : 0.0f;"
    , "      float wk = (ki < weights_count && weights != nullptr) ? weights[ki] : 0.0f;"
    , "      qsum += input[k] * wq;"
    , "      ksum += input[k] * wk;"
    , "    }"
    , "    std::size_t vi = 2 * block_size + j * n + i;"
    , "    float wv = (vi < weights_count && weights != nullptr) ? weights[vi] : 0.0f;"
    , "    v += qsum * ksum * wv;"
    , "  }"
    , "  out[i] = v;"
    , "}"
    , ""
    , "static void jitml_launch_mha_weighted("
    , "    float *out, const float *input, std::size_t n,"
    , "    const float *weights, std::size_t weights_count) {"
    , "  dim3 block(256);"
    , "  dim3 grid(static_cast<unsigned int>((n + block.x - 1) / block.x));"
    , "  jitml_device_mha_weighted<<<grid, block>>>(out, input, n, weights, weights_count);"
    , "}"
    , ""
    , "extern \"C\" void jitml_weighted_kernel("
    , "    float *out, const float *input, std::size_t n,"
    , "    const float *weights, std::size_t weights_count) {"
    , "  jitml_cuda_copy_and_launch_weighted("
    , "      out, input, n, weights, weights_count,"
    , "      jitml_kernel_output_count(n), jitml_launch_mha_weighted);"
    , "}"
    ]
weightedFamilyImpl _ =
  -- Identity / Reduction kernels keep the unweighted body — they have
  -- no natural weight parameter.
  Text.unlines
    [ "extern \"C\" void jitml_weighted_kernel("
    , "    float *out, const float *input, std::size_t n,"
    , "    const float *weights, std::size_t weights_count) {"
    , "  (void)weights;"
    , "  (void)weights_count;"
    , "  jitml_kernel(out, input, n);"
    , "}"
    ]

cudaRuntimeHelpers :: Text
cudaRuntimeHelpers =
  Text.unlines
    [ "using JitmlCudaLauncher = void (*)(float *, const float *, std::size_t);"
    , "using JitmlCudaWeightedLauncher = void (*)(float *, const float *, std::size_t, const float *, std::size_t);"
    , ""
    , "static void jitml_cuda_check(cudaError_t status, const char *operation) {"
    , "  if (status != cudaSuccess) {"
    , "    std::fprintf(stderr, \"jitml cuda error during %s: %s\\n\", operation, cudaGetErrorString(status));"
    , "    std::abort();"
    , "  }"
    , "}"
    , ""
    , "static void jitml_cuda_free(float *ptr) {"
    , "  if (ptr != nullptr) {"
    , "    cudaFree(ptr);"
    , "  }"
    , "}"
    , ""
    , "static void jitml_cuda_copy_and_launch(float *out, const float *input, std::size_t n, std::size_t outputCount, JitmlCudaLauncher launcher) {"
    , "  if (n == 0 || outputCount == 0) { return; }"
    , "  float *deviceInput = nullptr;"
    , "  float *deviceOutput = nullptr;"
    , "  jitml_cuda_check(cudaMalloc(reinterpret_cast<void **>(&deviceInput), n * sizeof(float)), \"cudaMalloc(input)\");"
    , "  jitml_cuda_check(cudaMalloc(reinterpret_cast<void **>(&deviceOutput), outputCount * sizeof(float)), \"cudaMalloc(output)\");"
    , "  jitml_cuda_check(cudaMemcpy(deviceInput, input, n * sizeof(float), cudaMemcpyHostToDevice), \"cudaMemcpy(input)\");"
    , "  launcher(deviceOutput, deviceInput, n);"
    , "  jitml_cuda_check(cudaGetLastError(), \"kernel launch\");"
    , "  jitml_cuda_check(cudaDeviceSynchronize(), \"cudaDeviceSynchronize\");"
    , "  jitml_cuda_check(cudaMemcpy(out, deviceOutput, outputCount * sizeof(float), cudaMemcpyDeviceToHost), \"cudaMemcpy(output)\");"
    , "  jitml_cuda_free(deviceOutput);"
    , "  jitml_cuda_free(deviceInput);"
    , "}"
    , ""
    , "// Sprint 13.11 — weighted helper. Allocates device buffers for"
    , "// input, weights, and output, copies them across, launches the"
    , "// family-specific weighted device kernel, and copies the result"
    , "// back. When `weights_count` is zero the host wrapper still"
    , "// allocates a zero-sized device buffer (the device launcher"
    , "// receives a null pointer and treats the missing weights as"
    , "// zero-padded)."
    , "static void jitml_cuda_copy_and_launch_weighted("
    , "    float *out, const float *input, std::size_t n,"
    , "    const float *weights, std::size_t weights_count,"
    , "    std::size_t outputCount, JitmlCudaWeightedLauncher launcher) {"
    , "  if (n == 0 || outputCount == 0) { return; }"
    , "  float *deviceInput = nullptr;"
    , "  float *deviceOutput = nullptr;"
    , "  float *deviceWeights = nullptr;"
    , "  jitml_cuda_check(cudaMalloc(reinterpret_cast<void **>(&deviceInput), n * sizeof(float)), \"cudaMalloc(input)\");"
    , "  jitml_cuda_check(cudaMalloc(reinterpret_cast<void **>(&deviceOutput), outputCount * sizeof(float)), \"cudaMalloc(output)\");"
    , "  if (weights_count > 0) {"
    , "    jitml_cuda_check(cudaMalloc(reinterpret_cast<void **>(&deviceWeights), weights_count * sizeof(float)), \"cudaMalloc(weights)\");"
    , "    jitml_cuda_check(cudaMemcpy(deviceWeights, weights, weights_count * sizeof(float), cudaMemcpyHostToDevice), \"cudaMemcpy(weights)\");"
    , "  }"
    , "  jitml_cuda_check(cudaMemcpy(deviceInput, input, n * sizeof(float), cudaMemcpyHostToDevice), \"cudaMemcpy(input)\");"
    , "  launcher(deviceOutput, deviceInput, n, deviceWeights, weights_count);"
    , "  jitml_cuda_check(cudaGetLastError(), \"weighted kernel launch\");"
    , "  jitml_cuda_check(cudaDeviceSynchronize(), \"cudaDeviceSynchronize\");"
    , "  jitml_cuda_check(cudaMemcpy(out, deviceOutput, outputCount * sizeof(float), cudaMemcpyDeviceToHost), \"cudaMemcpy(output)\");"
    , "  jitml_cuda_free(deviceWeights);"
    , "  jitml_cuda_free(deviceOutput);"
    , "  jitml_cuda_free(deviceInput);"
    , "}"
    ]

cudnnDeterministicAlgorithm :: KernelFamily -> Text
cudnnDeterministicAlgorithm Conv2DKernel = "CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM"
cudnnDeterministicAlgorithm Conv3DKernel = "CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM"
cudnnDeterministicAlgorithm BatchNormKernel = "CUDNN_BATCHNORM_SPATIAL_PERSISTENT"
cudnnDeterministicAlgorithm LayerNormKernel = "CUDNN_BATCHNORM_SPATIAL_PERSISTENT"
cudnnDeterministicAlgorithm MultiHeadAttentionKernel = "deterministic-cublas-gemm"
cudnnDeterministicAlgorithm _ = "none"

cString :: Text -> Text
cString value =
  "\"" <> Text.concatMap escape value <> "\""

kernelOutputCountFunction :: KernelFamily -> Text
kernelOutputCountFunction Reduction =
  Text.unlines
    [ "extern \"C\" std::size_t jitml_kernel_output_count(std::size_t n) {"
    , "  const std::size_t block = 256;"
    , "  const std::size_t warp = 32;"
    , "  const std::size_t warpsPerBlock = block / warp;"
    , "  return ((n + block - 1) / block) * warpsPerBlock;"
    , "}"
    ]
kernelOutputCountFunction _ =
  "extern \"C\" std::size_t jitml_kernel_output_count(std::size_t n) { return n; }"

escape :: Char -> Text
escape '"' = "\\\""
escape '\\' = "\\\\"
escape '\n' = "\\n"
escape char = Text.singleton char
