{-# LANGUAGE OverloadedStrings #-}

module JitML.Codegen.Cuda
  ( renderCudaSource
  , renderCudaFamilySource
  )
where

import Data.Text (Text)
import Data.Text qualified as Text

import JitML.Cache.Key (KernelSpec (..), Kind, TuningChoice (..), kindText)
import JitML.Codegen.KernelFamily (KernelFamily (..), familyName)
import JitML.Codegen.SourceFile (SourceFile (..))

renderCudaSource :: KernelSpec -> Kind -> TuningChoice -> [SourceFile]
renderCudaSource = renderCudaFamilySource Identity

renderCudaFamilySource
  :: KernelFamily -> KernelSpec -> Kind -> TuningChoice -> [SourceFile]
renderCudaFamilySource family kernelSpec kind tuningChoice =
  [ SourceFile "kernel.cu" (cudaSource family kernelSpec kind tuningChoice)
  ]

cudaSource :: KernelFamily -> KernelSpec -> Kind -> TuningChoice -> Text
cudaSource family kernelSpec kind tuningChoice =
  Text.unlines
    [ "// Generated by jitml. Do not check generated CUDA source into git."
    , "#include <cstddef>"
    , "#include <cstdio>"
    , "#include <cstdlib>"
    , "#include <cuda_runtime.h>"
    , "#ifdef JITML_USE_CUDNN"
    , "#include <cudnn.h>"
    , "#endif"
    , "#ifdef JITML_USE_CUBLAS"
    , "#include <cublas_v2.h>"
    , "#endif"
    , ""
    , "static const char *jitml_kernel_spec = " <> cString (kernelSpecPayload kernelSpec) <> ";"
    , "static const char *jitml_kernel_kind = " <> cString (kindText kind) <> ";"
    , "static const char *jitml_tuning_choice = " <> cString (unTuningChoice tuningChoice) <> ";"
    , "static const char *jitml_kernel_family = " <> cString (familyName family) <> ";"
    , "static const char *jitml_cudnn_algorithm = " <> cString (cudnnDeterministicAlgorithm family) <> ";"
    , "static const char *jitml_rng_policy = \"host-splitmix64-no-curand\";"
    , "// determinism: --use_fast_math=false; TF32 disabled; warp-shuffle reductions"
    , ""
    , kernelOutputCountFunction family
    , ""
    , cudaRuntimeHelpers
    , ""
    , familyImpl family
    , ""
    , "extern \"C\" const char *jitml_kernel_family_name(void) { return jitml_kernel_family; }"
    ]

familyImpl :: KernelFamily -> Text
familyImpl Identity =
  identityLikeFamilyImpl
    "jitml_device_identity"
    "// Identity CUDA kernel. The extern-C host wrapper owns device allocation and readback."
familyImpl Reduction =
  Text.unlines
    [ "// Deterministic warp-shuffle reduction kernel. One partial is emitted per"
    , "// warp, and the host accumulates those partials in canonical index order."
    , "static __global__ void jitml_device_reduction(float *partials, const float *input, std::size_t n) {"
    , "  int tid = threadIdx.x;"
    , "  int warp = tid / warpSize;"
    , "  std::size_t idx = static_cast<std::size_t>(blockIdx.x) * blockDim.x + tid;"
    , "  float v = idx < n ? input[idx] : 0.0f;"
    , "  for (int offset = warpSize / 2; offset > 0; offset >>= 1) {"
    , "    v += __shfl_down_sync(0xFFFFFFFFu, v, offset);"
    , "  }"
    , "  if ((tid & (warpSize - 1)) == 0) {"
    , "    int warpsPerBlock = blockDim.x / warpSize;"
    , "    partials[blockIdx.x * warpsPerBlock + warp] = v;"
    , "  }"
    , "}"
    , ""
    , "static void jitml_launch_device(float *partials, const float *input, std::size_t n) {"
    , "  dim3 block(256);"
    , "  std::size_t gridCount = (n + block.x - 1) / block.x;"
    , "  dim3 grid(static_cast<unsigned int>(gridCount));"
    , "  jitml_device_reduction<<<grid, block>>>(partials, input, n);"
    , "}"
    , ""
    , "extern \"C\" void jitml_kernel(float *out, const float *input, std::size_t n) {"
    , "  jitml_cuda_copy_and_launch(out, input, n, jitml_kernel_output_count(n), jitml_launch_device);"
    , "}"
    ]
familyImpl Dense2D =
  identityLikeFamilyImpl
    "jitml_device_dense"
    "// cuBLAS-backed GEMM scaffold. The current host wrapper uses deterministic device readback."
familyImpl Conv2DKernel =
  identityLikeFamilyImpl
    "jitml_device_conv2d"
    ( Text.unlines
        [ "// cuDNN-backed Conv2D scaffold. Real driver pins"
        , "// CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM (deterministic)."
        ]
    )
familyImpl Conv3DKernel =
  identityLikeFamilyImpl
    "jitml_device_conv3d"
    ( Text.unlines
        [ "// cuDNN-backed Conv3D scaffold. Real driver pins"
        , "// CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM (deterministic)."
        ]
    )
familyImpl BatchNormKernel =
  identityLikeFamilyImpl
    "jitml_device_batchnorm"
    "// cuDNN Spatial BN scaffold. Inference path uses pre-baked stats."
familyImpl LayerNormKernel =
  identityLikeFamilyImpl
    "jitml_device_layernorm"
    "// LayerNorm scaffold. Inference path uses pre-baked stats."
familyImpl MultiHeadAttentionKernel =
  identityLikeFamilyImpl
    "jitml_device_mha"
    ( Text.unlines
        [ "// MHA scaffold. Real driver chains cublasSgemm for QKV linear and the output"
        , "// projection, plus deterministic softmax via warp-shuffle reductions."
        ]
    )
familyImpl EmbeddingKernel =
  identityLikeFamilyImpl
    "jitml_device_embedding"
    "// Embedding scaffold. The current host wrapper uses deterministic device readback."

identityLikeFamilyImpl :: Text -> Text -> Text
identityLikeFamilyImpl deviceKernelName comment =
  Text.unlines
    [ comment
    , "static __global__ void " <> deviceKernelName <> "(float *out, const float *input, std::size_t n) {"
    , "  std::size_t i = static_cast<std::size_t>(blockIdx.x) * blockDim.x + threadIdx.x;"
    , "  if (i < n) { out[i] = input[i]; }"
    , "}"
    , ""
    , "static void jitml_launch_device(float *out, const float *input, std::size_t n) {"
    , "  dim3 block(256);"
    , "  std::size_t gridCount = (n + block.x - 1) / block.x;"
    , "  dim3 grid(static_cast<unsigned int>(gridCount));"
    , "  " <> deviceKernelName <> "<<<grid, block>>>(out, input, n);"
    , "}"
    , ""
    , "extern \"C\" void jitml_kernel(float *out, const float *input, std::size_t n) {"
    , "  jitml_cuda_copy_and_launch(out, input, n, jitml_kernel_output_count(n), jitml_launch_device);"
    , "}"
    ]

cudaRuntimeHelpers :: Text
cudaRuntimeHelpers =
  Text.unlines
    [ "using JitmlCudaLauncher = void (*)(float *, const float *, std::size_t);"
    , ""
    , "static void jitml_cuda_check(cudaError_t status, const char *operation) {"
    , "  if (status != cudaSuccess) {"
    , "    std::fprintf(stderr, \"jitml cuda error during %s: %s\\n\", operation, cudaGetErrorString(status));"
    , "    std::abort();"
    , "  }"
    , "}"
    , ""
    , "static void jitml_cuda_free(float *ptr) {"
    , "  if (ptr != nullptr) {"
    , "    cudaFree(ptr);"
    , "  }"
    , "}"
    , ""
    , "static void jitml_cuda_copy_and_launch(float *out, const float *input, std::size_t n, std::size_t outputCount, JitmlCudaLauncher launcher) {"
    , "  if (n == 0 || outputCount == 0) { return; }"
    , "  float *deviceInput = nullptr;"
    , "  float *deviceOutput = nullptr;"
    , "  jitml_cuda_check(cudaMalloc(reinterpret_cast<void **>(&deviceInput), n * sizeof(float)), \"cudaMalloc(input)\");"
    , "  jitml_cuda_check(cudaMalloc(reinterpret_cast<void **>(&deviceOutput), outputCount * sizeof(float)), \"cudaMalloc(output)\");"
    , "  jitml_cuda_check(cudaMemcpy(deviceInput, input, n * sizeof(float), cudaMemcpyHostToDevice), \"cudaMemcpy(input)\");"
    , "  launcher(deviceOutput, deviceInput, n);"
    , "  jitml_cuda_check(cudaGetLastError(), \"kernel launch\");"
    , "  jitml_cuda_check(cudaDeviceSynchronize(), \"cudaDeviceSynchronize\");"
    , "  jitml_cuda_check(cudaMemcpy(out, deviceOutput, outputCount * sizeof(float), cudaMemcpyDeviceToHost), \"cudaMemcpy(output)\");"
    , "  jitml_cuda_free(deviceOutput);"
    , "  jitml_cuda_free(deviceInput);"
    , "}"
    ]

cudnnDeterministicAlgorithm :: KernelFamily -> Text
cudnnDeterministicAlgorithm Conv2DKernel = "CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM"
cudnnDeterministicAlgorithm Conv3DKernel = "CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM"
cudnnDeterministicAlgorithm BatchNormKernel = "CUDNN_BATCHNORM_SPATIAL_PERSISTENT"
cudnnDeterministicAlgorithm LayerNormKernel = "CUDNN_BATCHNORM_SPATIAL_PERSISTENT"
cudnnDeterministicAlgorithm MultiHeadAttentionKernel = "deterministic-cublas-gemm"
cudnnDeterministicAlgorithm _ = "none"

cString :: Text -> Text
cString value =
  "\"" <> Text.concatMap escape value <> "\""

kernelOutputCountFunction :: KernelFamily -> Text
kernelOutputCountFunction Reduction =
  Text.unlines
    [ "extern \"C\" std::size_t jitml_kernel_output_count(std::size_t n) {"
    , "  const std::size_t block = 256;"
    , "  const std::size_t warp = 32;"
    , "  const std::size_t warpsPerBlock = block / warp;"
    , "  return ((n + block - 1) / block) * warpsPerBlock;"
    , "}"
    ]
kernelOutputCountFunction _ =
  "extern \"C\" std::size_t jitml_kernel_output_count(std::size_t n) { return n; }"

escape :: Char -> Text
escape '"' = "\\\""
escape '\\' = "\\\\"
escape '\n' = "\\n"
escape char = Text.singleton char
