{-# LANGUAGE OverloadedStrings #-}

module JitML.Codegen.Cuda
  ( renderCudaSource
  )
where

import Data.Text qualified as Text

import JitML.Cache.Key (KernelSpec (..), Kind, TuningChoice (..), kindText)
import JitML.Codegen.SourceFile (SourceFile (..))

renderCudaSource :: KernelSpec -> Kind -> TuningChoice -> [SourceFile]
renderCudaSource kernelSpec kind tuningChoice =
  [ SourceFile
      "kernel.cu"
      ( Text.unlines
          [ "// Generated by jitml. Do not check generated CUDA source into git."
          , "#include <cuda_runtime.h>"
          , ""
          , "extern \"C\" __global__ void jitml_kernel(float *out, const float *input, int n) {"
          , "  int i = blockIdx.x * blockDim.x + threadIdx.x;"
          , "  if (i < n) {"
          , "    out[i] = input[i];"
          , "  }"
          , "}"
          , ""
          , "extern \"C\" void jitml_launch(float *out, const float *input, int n) {"
          , "  dim3 block(256);"
          , "  dim3 grid((n + block.x - 1) / block.x);"
          , "  jitml_kernel<<<grid, block>>>(out, input, n);"
          , "}"
          , ""
          , "static const char *jitml_kernel_spec = " <> cString (kernelSpecPayload kernelSpec) <> ";"
          , "static const char *jitml_kernel_kind = " <> cString (kindText kind) <> ";"
          , "static const char *jitml_tuning_choice = " <> cString (unTuningChoice tuningChoice) <> ";"
          ]
      )
  ]

cString :: Text.Text -> Text.Text
cString value =
  "\"" <> Text.concatMap escape value <> "\""

escape :: Char -> Text.Text
escape '"' = "\\\""
escape '\\' = "\\\\"
escape '\n' = "\\n"
escape char = Text.singleton char
