{-# LANGUAGE OverloadedStrings #-}

-- | The backend-agnostic operator layer of the generated layer-graph training
-- kernel.
--
-- Sprint `264.1`. Every substrate that trains the typed 'JitML.Numerics.LayerGraph'
-- IR renders the same operator bodies — the affine/kind dispatch, the correct
-- operators (GeGLU, normalization, patch-embed, multi-head attention, residual),
-- and the unified `jitml_op_train` opcode entry. They are shared text rather than
-- a per-lane copy because the operators are compositions: each one calls into the
-- /primitive layer/ its backend supplies (matmul, convolution, pooling, scale) and
-- otherwise does elementwise and reduction glue that has no backend-specific form.
-- A divergence between two lanes' operator semantics therefore requires editing
-- one string, which is the point.
--
-- The primitive-layer contract — the names this text may call, which every
-- backend renderer must define before splicing it — is:
--
-- * @jitml_matmul_{forward,backward_data,backward_weights}@
-- * @jitml_conv2d_{forward,backward_data,backward_weights}@ (flat)
-- * @jitml_conv3d_{forward,backward_data,backward_weights}@ (flat)
-- * @jitml_pool_train@, @jitml_scale_train@
-- * @{forward,backward_data,backward_weights}_primitive_name@
-- * the @JITML_LAYER_{DENSE,CONV2D,CONV3D}@ kind codes
module JitML.Codegen.LayerTraining
  ( layerTrainingOperatorLayer
  , layerTrainingKindDispatchLayer
  , layerTrainingOperatorBodies
  , layerTrainingOpTrainEntry
  )
where

import Data.Text (Text)

-- | The shared operator layer as one contiguous block, for a backend whose
-- emission order is free to be chosen.  A backend that must preserve an
-- existing byte-for-byte emission order splices the three chunks below at its
-- own offsets instead; Sprint `263.1` pinned the `linux-cpu` artifact digest
-- into the committed lane fragment, so `linux-cpu` is such a backend.
layerTrainingOperatorLayer :: [Text]
layerTrainingOperatorLayer =
  layerTrainingKindDispatchLayer
    <> ("" : layerTrainingOperatorBodies)
    <> ("" : layerTrainingOpTrainEntry)

-- | Chunk A: the primitive-name accessors and the layer-kind dispatch that
-- routes an affine layer to its backend's matmul or convolution primitive.
layerTrainingKindDispatchLayer :: [Text]
layerTrainingKindDispatchLayer =
  [ "extern \"C\" const char *jitml_layer_forward_primitive(int kind) {"
  , "  return forward_primitive_name(kind);"
  , "}"
  , ""
  , "extern \"C\" const char *jitml_layer_backward_data_primitive(int kind) {"
  , "  return backward_data_primitive_name(kind);"
  , "}"
  , ""
  , "extern \"C\" const char *jitml_layer_backward_weights_primitive(int kind) {"
  , "  return backward_weights_primitive_name(kind);"
  , "}"
  , ""
  , "extern \"C\" void jitml_layer_forward("
  , "    float *out, const float *input, const float *weights, const float *bias,"
  , "    int inputs, int outputs, int kind, int batch) {"
  , "  if (kind == JITML_LAYER_CONV2D) {"
  , "    jitml_conv2d_forward(out, input, weights, bias, inputs, outputs, batch);"
  , "    return;"
  , "  }"
  , "  if (kind == JITML_LAYER_CONV3D) {"
  , "    jitml_conv3d_forward(out, input, weights, bias, inputs, outputs, batch);"
  , "    return;"
  , "  }"
  , "  jitml_matmul_forward(out, input, weights, bias, inputs, outputs, batch);"
  , "}"
  , ""
  , "extern \"C\" void jitml_layer_backward_data("
  , "    float *dx, const float *d_pre, const float *weights,"
  , "    int inputs, int outputs, int kind, int batch) {"
  , "  if (kind == JITML_LAYER_CONV2D) {"
  , "    jitml_conv2d_backward_data(dx, d_pre, weights, inputs, outputs, batch);"
  , "    return;"
  , "  }"
  , "  if (kind == JITML_LAYER_CONV3D) {"
  , "    jitml_conv3d_backward_data(dx, d_pre, weights, inputs, outputs, batch);"
  , "    return;"
  , "  }"
  , "  jitml_matmul_backward_data(dx, d_pre, weights, inputs, outputs, batch);"
  , "}"
  , ""
  , "extern \"C\" void jitml_layer_backward_weights("
  , "    float *g_weights, float *g_bias, const float *d_pre, const float *input,"
  , "    int inputs, int outputs, int kind, int batch) {"
  , "  if (kind == JITML_LAYER_CONV2D) {"
  , "    jitml_conv2d_backward_weights(g_weights, g_bias, d_pre, input, inputs, outputs, batch);"
  , "    return;"
  , "  }"
  , "  if (kind == JITML_LAYER_CONV3D) {"
  , "    jitml_conv3d_backward_weights(g_weights, g_bias, d_pre, input, inputs, outputs, batch);"
  , "    return;"
  , "  }"
  , "  jitml_matmul_backward_weights(g_weights, g_bias, d_pre, input, inputs, outputs, batch);"
  , "}"
  ]

-- | Chunk B: the correct-operator bodies (GELU, GeGLU, normalization, patch
-- embedding, multi-head attention, residual) that every substrate shares.
layerTrainingOperatorBodies :: [Text]
layerTrainingOperatorBodies =
  [ "// Phase 241 correct-operator device training kernels. Each renders the"
  , "// operator's real forward + backward-data + backward-weights, reusing the"
  , "// proven oneDNN matmul primitives (jitml_matmul_forward / _backward_data /"
  , "// _backward_weights) for every affine/projection sub-op and plain device C++"
  , "// for the elementwise (GELU), reduction (normalization statistics, softmax),"
  , "// and gather/scatter (patch) glue. Layouts match the pure LayerGraph oracle"
  , "// exactly (row-major W[out,in]; packed weight/bias segment order per"
  , "// opWeightSegments / opBiasSegments) so the device gradient matches"
  , "// backwardLayerGraph within float32 tolerance. Single example (batch=1); the"
  , "// Haskell batched path folds per example."
  , "static inline float jitml_gelu(float u) {"
  , "  return 0.5f * u * (1.0f + std::erf(u * 0.7071067811865476f));"
  , "}"
  , "static inline float jitml_gelu_deriv(float u) {"
  , "  return 0.5f * (1.0f + std::erf(u * 0.7071067811865476f))"
  , "       + u * std::exp(-0.5f * u * u) * 0.3989422804014327f;"
  , "}"
  , "static inline float jitml_act_fwd(int code, float z) {"
  , "  if (code == 1) { return std::tanh(z); }"
  , "  if (code == 2) { return z > 0.0f ? z : 0.0f; }"
  , "  return z;"
  , "}"
  , "static inline float jitml_act_bwd(int code, float activated, float up) {"
  , "  if (code == 1) { return (1.0f - activated * activated) * up; }"
  , "  if (code == 2) { return activated > 0.0f ? up : 0.0f; }"
  , "  return up;"
  , "}"
  , ""
  , "// GeGLU: a = Wa x + ba; g = Wb x + bb; h = a * gelu(g); y = W2 h + b2."
  , "static void jitml_geglu_train("
  , "    float *out, float *dx, float *dw, float *db,"
  , "    const float *x, const float *weights, const float *bias, const float *dy,"
  , "    int gin, int gff, int gout) {"
  , "  const float *wa = weights;"
  , "  const float *wb = weights + static_cast<std::size_t>(gff) * gin;"
  , "  const float *w2 = weights + 2 * static_cast<std::size_t>(gff) * gin;"
  , "  const float *ba = bias;"
  , "  const float *bb = bias + gff;"
  , "  const float *b2 = bias + 2 * gff;"
  , "  std::vector<float> a(gff), g(gff), gg(gff), hbuf(gff);"
  , "  jitml_matmul_forward(a.data(), x, wa, ba, gin, gff, 1);"
  , "  jitml_matmul_forward(g.data(), x, wb, bb, gin, gff, 1);"
  , "  for (int i = 0; i < gff; ++i) { gg[i] = jitml_gelu(g[i]); hbuf[i] = a[i] * gg[i]; }"
  , "  jitml_matmul_forward(out, hbuf.data(), w2, b2, gff, gout, 1);"
  , "  float *dwa = dw;"
  , "  float *dwb = dw + static_cast<std::size_t>(gff) * gin;"
  , "  float *dw2 = dw + 2 * static_cast<std::size_t>(gff) * gin;"
  , "  float *dba = db;"
  , "  float *dbb = db + gff;"
  , "  float *db2 = db + 2 * gff;"
  , "  jitml_matmul_backward_weights(dw2, db2, dy, hbuf.data(), gff, gout, 1);"
  , "  std::vector<float> dh(gff);"
  , "  jitml_matmul_backward_data(dh.data(), dy, w2, gff, gout, 1);"
  , "  std::vector<float> da(gff), dg(gff);"
  , "  for (int i = 0; i < gff; ++i) {"
  , "    da[i] = dh[i] * gg[i];"
  , "    dg[i] = dh[i] * a[i] * jitml_gelu_deriv(g[i]);"
  , "  }"
  , "  jitml_matmul_backward_weights(dwa, dba, da.data(), x, gin, gff, 1);"
  , "  jitml_matmul_backward_weights(dwb, dbb, dg.data(), x, gin, gff, 1);"
  , "  std::vector<float> dxa(gin), dxb(gin);"
  , "  jitml_matmul_backward_data(dxa.data(), da.data(), wa, gin, gff, 1);"
  , "  jitml_matmul_backward_data(dxb.data(), dg.data(), wb, gin, gff, 1);"
  , "  for (int i = 0; i < gin; ++i) { dx[i] = dxa[i] + dxb[i]; }"
  , "}"
  , ""
  , "// Normalization (batch / layer / group). flavor: 0=batch, 1=layerwise,"
  , "// 2=group. gamma=weights, beta=bias (length channels). Mirrors the oracle's"
  , "// biased (divide-by-m) variance and per-group reduction exactly."
  , "static void jitml_norm_train("
  , "    float *out, float *dx, float *dw, float *db,"
  , "    const float *x, const float *gamma, const float *beta, const float *dy,"
  , "    int flavor, int channels, int spatial, int groups, float eps, int len) {"
  , "  std::vector<int> groupOf(len, 0);"
  , "  int numGroups = 1;"
  , "  if (flavor == 1) { numGroups = 1; for (int i = 0; i < len; ++i) { groupOf[i] = 0; } }"
  , "  else if (flavor == 2) {"
  , "    int gsz = groups > 0 ? channels / groups : channels;"
  , "    if (gsz <= 0) { gsz = 1; }"
  , "    numGroups = groups > 0 ? groups : 1;"
  , "    for (int i = 0; i < len; ++i) { groupOf[i] = (i / spatial) / gsz; }"
  , "  } else {"
  , "    numGroups = channels;"
  , "    for (int i = 0; i < len; ++i) { groupOf[i] = i % channels; }"
  , "  }"
  , "  std::vector<float> mu(numGroups, 0.0f), var(numGroups, 0.0f), rstd(numGroups, 0.0f);"
  , "  std::vector<int> cnt(numGroups, 0);"
  , "  for (int i = 0; i < len; ++i) { mu[groupOf[i]] += x[i]; cnt[groupOf[i]] += 1; }"
  , "  for (int gi = 0; gi < numGroups; ++gi) { if (cnt[gi] > 0) { mu[gi] /= static_cast<float>(cnt[gi]); } }"
  , "  for (int i = 0; i < len; ++i) { float d = x[i] - mu[groupOf[i]]; var[groupOf[i]] += d * d; }"
  , "  for (int gi = 0; gi < numGroups; ++gi) {"
  , "    if (cnt[gi] > 0) { var[gi] /= static_cast<float>(cnt[gi]); }"
  , "    rstd[gi] = 1.0f / std::sqrt(var[gi] + eps);"
  , "  }"
  , "  std::vector<float> xhat(len);"
  , "  for (int i = 0; i < len; ++i) { int gi = groupOf[i]; xhat[i] = (x[i] - mu[gi]) * rstd[gi]; }"
  , "  for (int i = 0; i < len; ++i) {"
  , "    int c = flavor == 0 ? (i % channels) : (i / spatial);"
  , "    out[i] = gamma[c] * xhat[i] + beta[c];"
  , "  }"
  , "  std::vector<float> ghat(len);"
  , "  for (int i = 0; i < len; ++i) {"
  , "    int c = flavor == 0 ? (i % channels) : (i / spatial);"
  , "    ghat[i] = dy[i] * gamma[c];"
  , "  }"
  , "  std::vector<float> meanG(numGroups, 0.0f), meanGX(numGroups, 0.0f);"
  , "  for (int i = 0; i < len; ++i) { int gi = groupOf[i]; meanG[gi] += ghat[i]; meanGX[gi] += ghat[i] * xhat[i]; }"
  , "  for (int gi = 0; gi < numGroups; ++gi) {"
  , "    if (cnt[gi] > 0) { meanG[gi] /= static_cast<float>(cnt[gi]); meanGX[gi] /= static_cast<float>(cnt[gi]); }"
  , "  }"
  , "  for (int i = 0; i < len; ++i) {"
  , "    int gi = groupOf[i];"
  , "    dx[i] = rstd[gi] * (ghat[i] - meanG[gi] - xhat[i] * meanGX[gi]);"
  , "  }"
  , "  for (int c = 0; c < channels; ++c) { dw[c] = 0.0f; db[c] = 0.0f; }"
  , "  for (int i = 0; i < len; ++i) {"
  , "    int c = flavor == 0 ? (i % channels) : (i / spatial);"
  , "    dw[c] += dy[i] * xhat[i];"
  , "    db[c] += dy[i];"
  , "  }"
  , "}"
  , ""
  , "// Patch embedding: gather each P*P*C patch (pixel-row-major idx ="
  , "// ((y*W)+x)*C+c), project e = W p + b (cpp -> D), scatter dp back to dX."
  , "static void jitml_patch_train("
  , "    float *out, float *dx, float *dw, float *db,"
  , "    const float *x, const float *weights, const float *bias, const float *dy,"
  , "    int cC, int cH, int cW, int cP, int stride, int cD) {"
  , "  int cpp = cC * cP * cP;"
  , "  int nY = (cH - cP) / stride + 1;"
  , "  int nX = (cW - cP) / stride + 1;"
  , "  int inN = cC * cH * cW;"
  , "  for (int i = 0; i < cD * cpp; ++i) { dw[i] = 0.0f; }"
  , "  for (int i = 0; i < cD; ++i) { db[i] = 0.0f; }"
  , "  for (int i = 0; i < inN; ++i) { dx[i] = 0.0f; }"
  , "  std::vector<float> p(cpp), dwp(static_cast<std::size_t>(cD) * cpp), dbp(cD), dp(cpp);"
  , "  std::vector<int> idxs(cpp);"
  , "  int patchIdx = 0;"
  , "  for (int yi = 0; yi < nY; ++yi) {"
  , "    for (int xi = 0; xi < nX; ++xi) {"
  , "      int y0 = yi * stride;"
  , "      int x0 = xi * stride;"
  , "      int k = 0;"
  , "      for (int dyp = 0; dyp < cP; ++dyp) {"
  , "        for (int dxp = 0; dxp < cP; ++dxp) {"
  , "          for (int c = 0; c < cC; ++c) {"
  , "            int idx = ((y0 + dyp) * cW + (x0 + dxp)) * cC + c;"
  , "            idxs[k] = idx;"
  , "            p[k] = x[idx];"
  , "            k += 1;"
  , "          }"
  , "        }"
  , "      }"
  , "      jitml_matmul_forward(out + static_cast<std::size_t>(patchIdx) * cD, p.data(), weights, bias, cpp, cD, 1);"
  , "      const float *dEp = dy + static_cast<std::size_t>(patchIdx) * cD;"
  , "      jitml_matmul_backward_weights(dwp.data(), dbp.data(), dEp, p.data(), cpp, cD, 1);"
  , "      for (int j = 0; j < cD * cpp; ++j) { dw[j] += dwp[j]; }"
  , "      for (int j = 0; j < cD; ++j) { db[j] += dbp[j]; }"
  , "      jitml_matmul_backward_data(dp.data(), dEp, weights, cpp, cD, 1);"
  , "      for (int j = 0; j < cpp; ++j) { dx[idxs[j]] += dp[j]; }"
  , "      patchIdx += 1;"
  , "    }"
  , "  }"
  , "}"
  , ""
  , "// Multi-head self-attention with output projection and residual add:"
  , "// y_i = x_i + W_O concat_h( sum_t softmax_t(sc q_i.k_t) v_t )."
  , "static void jitml_attention_train("
  , "    float *out, float *dx, float *dw, float *db,"
  , "    const float *x, const float *weights, const float *bias, const float *dy,"
  , "    int sN, int dModel, int heads, int causal) {"
  , "  int dh = dModel / heads;"
  , "  float sc = 1.0f / std::sqrt(static_cast<float>(dh));"
  , "  int dd = dModel * dModel;"
  , "  const float *wQ = weights;"
  , "  const float *wK = weights + dd;"
  , "  const float *wV = weights + 2 * dd;"
  , "  const float *wO = weights + 3 * dd;"
  , "  const float *bQ = bias;"
  , "  const float *bK = bias + dModel;"
  , "  const float *bV = bias + 2 * dModel;"
  , "  const float *bO = bias + 3 * dModel;"
  , "  std::vector<float> qs(static_cast<std::size_t>(sN) * dModel);"
  , "  std::vector<float> ks(static_cast<std::size_t>(sN) * dModel);"
  , "  std::vector<float> vs(static_cast<std::size_t>(sN) * dModel);"
  , "  for (int i = 0; i < sN; ++i) {"
  , "    jitml_matmul_forward(qs.data() + static_cast<std::size_t>(i) * dModel, x + static_cast<std::size_t>(i) * dModel, wQ, bQ, dModel, dModel, 1);"
  , "    jitml_matmul_forward(ks.data() + static_cast<std::size_t>(i) * dModel, x + static_cast<std::size_t>(i) * dModel, wK, bK, dModel, dModel, 1);"
  , "    jitml_matmul_forward(vs.data() + static_cast<std::size_t>(i) * dModel, x + static_cast<std::size_t>(i) * dModel, wV, bV, dModel, dModel, 1);"
  , "  }"
  , "  std::vector<float> cs(static_cast<std::size_t>(sN) * dModel, 0.0f);"
  , "  std::vector<float> ps(static_cast<std::size_t>(heads) * sN * sN, 0.0f);"
  , "  for (int hd = 0; hd < heads; ++hd) {"
  , "    for (int i = 0; i < sN; ++i) {"
  , "      std::vector<float> sco(sN);"
  , "      float mx = -INFINITY;"
  , "      for (int t = 0; t < sN; ++t) {"
  , "        float v;"
  , "        if (causal != 0 && t > i) { v = -INFINITY; }"
  , "        else {"
  , "          float dot = 0.0f;"
  , "          for (int e = 0; e < dh; ++e) { dot += qs[static_cast<std::size_t>(i) * dModel + hd * dh + e] * ks[static_cast<std::size_t>(t) * dModel + hd * dh + e]; }"
  , "          v = sc * dot;"
  , "        }"
  , "        sco[t] = v;"
  , "        if (v > mx) { mx = v; }"
  , "      }"
  , "      float denom = 0.0f;"
  , "      for (int t = 0; t < sN; ++t) { float ex = std::isinf(sco[t]) && sco[t] < 0.0f ? 0.0f : std::exp(sco[t] - mx); sco[t] = ex; denom += ex; }"
  , "      for (int t = 0; t < sN; ++t) { sco[t] = denom > 0.0f ? sco[t] / denom : 1.0f / static_cast<float>(sN); }"
  , "      for (int t = 0; t < sN; ++t) { ps[(static_cast<std::size_t>(hd) * sN + i) * sN + t] = sco[t]; }"
  , "      for (int e = 0; e < dh; ++e) {"
  , "        float acc = 0.0f;"
  , "        for (int t = 0; t < sN; ++t) { acc += sco[t] * vs[static_cast<std::size_t>(t) * dModel + hd * dh + e]; }"
  , "        cs[static_cast<std::size_t>(i) * dModel + hd * dh + e] = acc;"
  , "      }"
  , "    }"
  , "  }"
  , "  for (int i = 0; i < sN; ++i) {"
  , "    std::vector<float> oi(dModel);"
  , "    jitml_matmul_forward(oi.data(), cs.data() + static_cast<std::size_t>(i) * dModel, wO, bO, dModel, dModel, 1);"
  , "    for (int e = 0; e < dModel; ++e) { out[static_cast<std::size_t>(i) * dModel + e] = x[static_cast<std::size_t>(i) * dModel + e] + oi[e]; }"
  , "  }"
  , "  float *dwQ = dw;"
  , "  float *dwK = dw + dd;"
  , "  float *dwV = dw + 2 * dd;"
  , "  float *dwO = dw + 3 * dd;"
  , "  float *dbQ = db;"
  , "  float *dbK = db + dModel;"
  , "  float *dbV = db + 2 * dModel;"
  , "  float *dbO = db + 3 * dModel;"
  , "  for (int j = 0; j < 4 * dd; ++j) { dw[j] = 0.0f; }"
  , "  for (int j = 0; j < 4 * dModel; ++j) { db[j] = 0.0f; }"
  , "  std::vector<float> dC(static_cast<std::size_t>(sN) * dModel);"
  , "  std::vector<float> tW(dd), tB(dModel);"
  , "  for (int i = 0; i < sN; ++i) {"
  , "    const float *dOi = dy + static_cast<std::size_t>(i) * dModel;"
  , "    jitml_matmul_backward_weights(tW.data(), tB.data(), dOi, cs.data() + static_cast<std::size_t>(i) * dModel, dModel, dModel, 1);"
  , "    for (int j = 0; j < dd; ++j) { dwO[j] += tW[j]; }"
  , "    for (int j = 0; j < dModel; ++j) { dbO[j] += tB[j]; }"
  , "    jitml_matmul_backward_data(dC.data() + static_cast<std::size_t>(i) * dModel, dOi, wO, dModel, dModel, 1);"
  , "  }"
  , "  std::vector<float> dQs(static_cast<std::size_t>(sN) * dModel, 0.0f);"
  , "  std::vector<float> dKs(static_cast<std::size_t>(sN) * dModel, 0.0f);"
  , "  std::vector<float> dVs(static_cast<std::size_t>(sN) * dModel, 0.0f);"
  , "  for (int hd = 0; hd < heads; ++hd) {"
  , "    for (int t = 0; t < sN; ++t) {"
  , "      for (int e = 0; e < dh; ++e) {"
  , "        float acc = 0.0f;"
  , "        for (int i = 0; i < sN; ++i) { acc += ps[(static_cast<std::size_t>(hd) * sN + i) * sN + t] * dC[static_cast<std::size_t>(i) * dModel + hd * dh + e]; }"
  , "        dVs[static_cast<std::size_t>(t) * dModel + hd * dh + e] = acc;"
  , "      }"
  , "    }"
  , "    for (int i = 0; i < sN; ++i) {"
  , "      std::vector<float> dP(sN), dA(sN);"
  , "      for (int t = 0; t < sN; ++t) {"
  , "        float acc = 0.0f;"
  , "        for (int e = 0; e < dh; ++e) { acc += dC[static_cast<std::size_t>(i) * dModel + hd * dh + e] * vs[static_cast<std::size_t>(t) * dModel + hd * dh + e]; }"
  , "        dP[t] = acc;"
  , "      }"
  , "      float m = 0.0f;"
  , "      for (int t = 0; t < sN; ++t) { m += ps[(static_cast<std::size_t>(hd) * sN + i) * sN + t] * dP[t]; }"
  , "      for (int t = 0; t < sN; ++t) { dA[t] = ps[(static_cast<std::size_t>(hd) * sN + i) * sN + t] * (dP[t] - m); }"
  , "      for (int e = 0; e < dh; ++e) {"
  , "        float accq = 0.0f;"
  , "        for (int t = 0; t < sN; ++t) { accq += sc * dA[t] * ks[static_cast<std::size_t>(t) * dModel + hd * dh + e]; }"
  , "        dQs[static_cast<std::size_t>(i) * dModel + hd * dh + e] = accq;"
  , "      }"
  , "      for (int t = 0; t < sN; ++t) {"
  , "        for (int e = 0; e < dh; ++e) { dKs[static_cast<std::size_t>(t) * dModel + hd * dh + e] += sc * dA[t] * qs[static_cast<std::size_t>(i) * dModel + hd * dh + e]; }"
  , "      }"
  , "    }"
  , "  }"
  , "  for (int i = 0; i < sN; ++i) {"
  , "    std::vector<float> tw(dd), tb(dModel);"
  , "    jitml_matmul_backward_weights(tw.data(), tb.data(), dQs.data() + static_cast<std::size_t>(i) * dModel, x + static_cast<std::size_t>(i) * dModel, dModel, dModel, 1);"
  , "    for (int j = 0; j < dd; ++j) { dwQ[j] += tw[j]; }"
  , "    for (int j = 0; j < dModel; ++j) { dbQ[j] += tb[j]; }"
  , "    jitml_matmul_backward_weights(tw.data(), tb.data(), dKs.data() + static_cast<std::size_t>(i) * dModel, x + static_cast<std::size_t>(i) * dModel, dModel, dModel, 1);"
  , "    for (int j = 0; j < dd; ++j) { dwK[j] += tw[j]; }"
  , "    for (int j = 0; j < dModel; ++j) { dbK[j] += tb[j]; }"
  , "    jitml_matmul_backward_weights(tw.data(), tb.data(), dVs.data() + static_cast<std::size_t>(i) * dModel, x + static_cast<std::size_t>(i) * dModel, dModel, dModel, 1);"
  , "    for (int j = 0; j < dd; ++j) { dwV[j] += tw[j]; }"
  , "    for (int j = 0; j < dModel; ++j) { dbV[j] += tb[j]; }"
  , "    std::vector<float> dxq(dModel), dxk(dModel), dxv(dModel);"
  , "    jitml_matmul_backward_data(dxq.data(), dQs.data() + static_cast<std::size_t>(i) * dModel, wQ, dModel, dModel, 1);"
  , "    jitml_matmul_backward_data(dxk.data(), dKs.data() + static_cast<std::size_t>(i) * dModel, wK, dModel, dModel, 1);"
  , "    jitml_matmul_backward_data(dxv.data(), dVs.data() + static_cast<std::size_t>(i) * dModel, wV, dModel, dModel, 1);"
  , "    for (int e = 0; e < dModel; ++e) {"
  , "      dx[static_cast<std::size_t>(i) * dModel + e] = dy[static_cast<std::size_t>(i) * dModel + e] + dxq[e] + dxk[e] + dxv[e];"
  , "    }"
  , "  }"
  , "}"
  , ""
  , "// Residual node: z = Winner x + bInner; a = act_inner(z);"
  , "// sx = (proj ? Wp x + bp : x); ypre = sx + scale * a; y = act_final(ypre)."
  , "static void jitml_residual_train("
  , "    float *out, float *dx, float *dw, float *db,"
  , "    const float *x, const float *weights, const float *bias, const float *dy,"
  , "    int aIn, int aOut, int hasProj, int innerAct, int finalAct, float scale) {"
  , "  const float *wInner = weights;"
  , "  const float *bInner = bias;"
  , "  const float *wp = hasProj != 0 ? weights + static_cast<std::size_t>(aOut) * aIn : nullptr;"
  , "  const float *bp = hasProj != 0 ? bias + aOut : nullptr;"
  , "  std::vector<float> z(aOut), a(aOut), sx(aOut), ypre(aOut);"
  , "  jitml_matmul_forward(z.data(), x, wInner, bInner, aIn, aOut, 1);"
  , "  for (int i = 0; i < aOut; ++i) { a[i] = jitml_act_fwd(innerAct, z[i]); }"
  , "  if (hasProj != 0) { jitml_matmul_forward(sx.data(), x, wp, bp, aIn, aOut, 1); }"
  , "  else { for (int i = 0; i < aOut; ++i) { sx[i] = x[i]; } }"
  , "  for (int i = 0; i < aOut; ++i) { ypre[i] = sx[i] + scale * a[i]; }"
  , "  for (int i = 0; i < aOut; ++i) { out[i] = jitml_act_fwd(finalAct, ypre[i]); }"
  , "  std::vector<float> d(aOut), dPre(aOut);"
  , "  for (int i = 0; i < aOut; ++i) { d[i] = jitml_act_bwd(finalAct, out[i], dy[i]); }"
  , "  for (int i = 0; i < aOut; ++i) { dPre[i] = scale * jitml_act_bwd(innerAct, a[i], d[i]); }"
  , "  std::vector<float> dxF(aIn);"
  , "  jitml_matmul_backward_data(dxF.data(), dPre.data(), wInner, aIn, aOut, 1);"
  , "  jitml_matmul_backward_weights(dw, db, dPre.data(), x, aIn, aOut, 1);"
  , "  if (hasProj == 0) {"
  , "    for (int i = 0; i < aIn; ++i) { dx[i] = dxF[i] + d[i]; }"
  , "  } else {"
  , "    std::vector<float> dxS(aIn);"
  , "    jitml_matmul_backward_data(dxS.data(), d.data(), wp, aIn, aOut, 1);"
  , "    jitml_matmul_backward_weights(dw + static_cast<std::size_t>(aOut) * aIn, db + aOut, d.data(), x, aIn, aOut, 1);"
  , "    for (int i = 0; i < aIn; ++i) { dx[i] = dxF[i] + dxS[i]; }"
  , "  }"
  , "}"
  ]

-- | Chunk C: the unified @jitml_op_train@ opcode entry, which fails closed on
-- an opcode this artifact does not implement.
layerTrainingOpTrainEntry :: [Text]
layerTrainingOpTrainEntry =
  [ "// Unified correct-operator device training entry. Returns (out, dX, dW, dB)"
  , "// with dW/dB in the operator's packed segment order. Geometry travels in the"
  , "// int `geom` array and float `fparams` array; opcode selects the operator."
  , "//"
  , "// The return value is the executed-opcode status: 0 when this artifact ran"
  , "// the requested operator, non-zero when it did not. An unrecognised opcode"
  , "// used to fall through a `default: break`, which returned the caller's"
  , "// untouched output and gradient buffers — indistinguishable from a kernel"
  , "// that ran and produced zeros. It now fails closed, and the host turns the"
  , "// status into a typed error naming the opcode."
  , "extern \"C\" int jitml_op_train("
  , "    int opcode, const int *geom, int geom_len,"
  , "    const float *fparams, int fparams_len,"
  , "    float *out, float *dx, float *dw, float *db,"
  , "    const float *x, const float *weights, const float *bias, const float *dy,"
  , "    int xlen, int outlen, int wlen, int blen) {"
  , "  (void)geom_len; (void)fparams_len; (void)outlen; (void)wlen; (void)blen;"
  , "  switch (opcode) {"
  , "    case 10:"
  , "      jitml_geglu_train(out, dx, dw, db, x, weights, bias, dy, geom[0], geom[1], geom[2]);"
  , "      return 0;"
  , "    case 11:"
  , "      jitml_norm_train(out, dx, dw, db, x, weights, bias, dy, geom[0], geom[1], geom[2], geom[3], fparams[0], xlen);"
  , "      return 0;"
  , "    case 12:"
  , "      jitml_patch_train(out, dx, dw, db, x, weights, bias, dy, geom[0], geom[1], geom[2], geom[3], geom[4], geom[5]);"
  , "      return 0;"
  , "    case 13:"
  , "      jitml_attention_train(out, dx, dw, db, x, weights, bias, dy, geom[0], geom[1], geom[2], geom[3]);"
  , "      return 0;"
  , "    case 14:"
  , "      jitml_residual_train(out, dx, dw, db, x, weights, bias, dy, geom[0], geom[1], geom[2], geom[3], geom[4], fparams[0]);"
  , "      return 0;"
  , "    case 15:"
  , "      jitml_pool_train(out, dx, x, dy, geom[0], geom[1], geom[2], geom[3], geom[4], geom[5], geom[6], geom[7], geom[8], geom[9]);"
  , "      return 0;"
  , "    case 16:"
  , "      jitml_scale_train(out, dx, x, dy, xlen, fparams[0]);"
  , "      return 0;"
  , "    default:"
  , "      return 1;"
  , "  }"
  , "}"
  ]
