{-# LANGUAGE OverloadedStrings #-}

module JitML.Codegen.Metal
  ( renderMetalPackage
  )
where

import Data.Text qualified as Text

import JitML.Cache.Key (KernelSpec (..), Kind, TuningChoice (..), kindText)
import JitML.Codegen.SourceFile (SourceFile (..))

renderMetalPackage :: KernelSpec -> Kind -> TuningChoice -> [SourceFile]
renderMetalPackage kernelSpec kind tuningChoice =
  [ SourceFile "Package.swift" packageSwift
  , SourceFile "Sources/JitMLMetal/JitMLMetal.swift" (swiftSource kernelSpec kind tuningChoice)
  , SourceFile "Sources/JitMLMetal/Kernels.metal" metalKernel
  ]

packageSwift :: Text.Text
packageSwift =
  Text.unlines
    [ "// swift-tools-version: 5.10"
    , "import PackageDescription"
    , ""
    , "let package = Package("
    , "  name: \"JitMLMetal\","
    , "  platforms: [.macOS(.v14)],"
    , "  products: [.library(name: \"JitMLMetal\", type: .dynamic, targets: [\"JitMLMetal\"])],"
    , "  targets: [.target(name: \"JitMLMetal\", resources: [.process(\"Kernels.metal\")])]"
    , ")"
    ]

swiftSource :: KernelSpec -> Kind -> TuningChoice -> Text.Text
swiftSource kernelSpec kind tuningChoice =
  Text.unlines
    [ "// Generated by jitml. Do not check generated Swift / Metal source into git."
    , "import Foundation"
    , "import Metal"
    , ""
    , "public enum JitMLGeneratedKernel {"
    , "  public static let kernelSpec = " <> swiftString (kernelSpecPayload kernelSpec)
    , "  public static let kernelKind = " <> swiftString (kindText kind)
    , "  public static let tuningChoice = " <> swiftString (unTuningChoice tuningChoice)
    , "  public static let commandQueueDiscipline = \"single-stream-launch-order\""
    , "}"
    ]

metalKernel :: Text.Text
metalKernel =
  Text.unlines
    [ "#include <metal_stdlib>"
    , "using namespace metal;"
    , ""
    , "kernel void jitml_kernel("
    , "    device float *out [[buffer(0)]],"
    , "    const device float *input [[buffer(1)]],"
    , "    uint id [[thread_position_in_grid]]) {"
    , "  out[id] = input[id];"
    , "}"
    ]

swiftString :: Text.Text -> Text.Text
swiftString value =
  "\"" <> Text.concatMap escape value <> "\""

escape :: Char -> Text.Text
escape '"' = "\\\""
escape '\\' = "\\\\"
escape '\n' = "\\n"
escape char = Text.singleton char
