{-# LANGUAGE OverloadedStrings #-}

module JitML.Codegen.Metal
  ( renderMetalPackage
  , renderMetalFamilyPackage
  , threadgroupSizeFor
  )
where

import Data.Text (Text)
import Data.Text qualified as Text

import JitML.Cache.Key (KernelSpec (..), Kind, TuningChoice (..), kindText)
import JitML.Codegen.KernelFamily (KernelFamily (..), familyName)
import JitML.Codegen.SourceFile (SourceFile (..))

renderMetalPackage :: KernelSpec -> Kind -> TuningChoice -> [SourceFile]
renderMetalPackage = renderMetalFamilyPackage Identity

renderMetalFamilyPackage
  :: KernelFamily -> KernelSpec -> Kind -> TuningChoice -> [SourceFile]
renderMetalFamilyPackage family kernelSpec kind tuningChoice =
  [ SourceFile "Package.swift" packageSwift
  , SourceFile
      "Sources/JitMLMetal/JitMLMetal.swift"
      (swiftSource family kernelSpec kind tuningChoice)
  ]

-- | Plain dynamic-library target: no `.metal` resource. The Metal Shading
-- Language is embedded in the generated Swift and JIT-compiled at runtime via
-- `MTLDevice.makeLibrary(source:options:)`, so the build needs only the
-- CommandLineTools `swiftc` (no offline `metal` compiler, no full Xcode).
packageSwift :: Text
packageSwift =
  Text.unlines
    [ "// swift-tools-version: 5.10"
    , "import PackageDescription"
    , ""
    , "let package = Package("
    , "  name: \"JitMLMetal\","
    , "  platforms: [.macOS(.v14)],"
    , "  products: [.library(name: \"JitMLMetal\", type: .dynamic, targets: [\"JitMLMetal\"])],"
    , "  targets: [.target(name: \"JitMLMetal\")]"
    , ")"
    ]

swiftSource :: KernelFamily -> KernelSpec -> Kind -> TuningChoice -> Text
swiftSource family kernelSpec kind tuningChoice =
  Text.unlines
    [ "// Generated by jitml. Do not check generated Swift / Metal source into git."
    , "import Darwin"
    , "import Metal"
    , ""
    , "// Metal Shading Language, embedded as a raw string and JIT-compiled at"
    , "// runtime via MTLDevice.makeLibrary(source:options:). No offline `metal`"
    , "// compiler, no .metallib, no resource bundle."
    , "private let jitmlMetalSource = #\"\"\""
    , metalKernel family
    , "\"\"\"#"
    , ""
    , "public enum JitMLGeneratedKernel {"
    , "  public static let kernelSpec = " <> swiftString (kernelSpecPayload kernelSpec)
    , "  public static let kernelKind = " <> swiftString (kindText kind)
    , "  public static let tuningChoice = " <> swiftString (unTuningChoice tuningChoice)
    , "  public static let kernelFamily = " <> swiftString (familyName family)
    , "  public static let threadgroupSize = " <> Text.pack (show (threadgroupSizeFor family))
    , "  public static let commandQueueDiscipline = \"single-stream-launch-order\""
    , "}"
    , ""
    , "private let jitmlKernelFamilyCString: UnsafeMutablePointer<CChar> = strdup("
        <> swiftString (familyName family)
        <> ")!"
    , ""
    , "@_cdecl(\"jitml_kernel_family_name\")"
    , "public func jitmlKernelFamilyName() -> UnsafePointer<CChar> {"
    , "  return UnsafePointer<CChar>(jitmlKernelFamilyCString)"
    , "}"
    , ""
    , "@_cdecl(\"jitml_kernel_output_count\")"
    , "public func jitmlKernelOutputCount(_ n: UInt) -> UInt {"
    , "  " <> metalOutputCountExpression family
    , "}"
    , ""
    , metalRuntimeLauncher
    , ""
    , "// Host-callable C ABI mirroring the CUDA / oneDNN substrates:"
    , "//   jitml_kernel(out, input, n) and"
    , "//   jitml_weighted_kernel(out, input, n, weights, wn)."
    , "// The host (Haskell FFI) owns the input / output buffers; the launcher"
    , "// copies them into shared MTLBuffers, dispatches on the default device in"
    , "// single-stream launch order, waits, and copies the result back."
    , "@_cdecl(\"jitml_kernel\")"
    , "public func jitmlKernel("
    , "    _ out: UnsafeMutablePointer<Float>,"
    , "    _ input: UnsafePointer<Float>,"
    , "    _ n: Int) {"
    , "  let outCount = Int(jitmlKernelOutputCount(UInt(n)))"
    , "  jitmlRun("
    , "    functionName: \"jitml_kernel\","
    , "    out: out, outCount: outCount,"
    , "    input: input, inCount: n,"
    , "    weights: nil, weightsCount: 0)"
    , "}"
    , ""
    , "@_cdecl(\"jitml_weighted_kernel\")"
    , "public func jitmlWeightedKernel("
    , "    _ out: UnsafeMutablePointer<Float>,"
    , "    _ input: UnsafePointer<Float>,"
    , "    _ n: Int,"
    , "    _ weights: UnsafePointer<Float>,"
    , "    _ wn: Int) {"
    , "  let outCount = Int(jitmlKernelOutputCount(UInt(n)))"
    , "  jitmlRun("
    , "    functionName: \"jitml_weighted_kernel\","
    , "    out: out, outCount: outCount,"
    , "    input: input, inCount: n,"
    , "    weights: weights, weightsCount: wn)"
    , "}"
    ]

-- | The shared Metal launcher rendered into every generated package. It owns a
-- single `MTLDevice` + `MTLCommandQueue` and JIT-compiles the embedded Metal
-- Shading Language at runtime via `MTLDevice.makeLibrary(source:options:)` with
-- fast-math disabled (determinism contract). Kernel launches use one command
-- buffer per call in submission order, honouring the `single-stream-launch-order`
-- determinism discipline.
metalRuntimeLauncher :: Text
metalRuntimeLauncher =
  Text.unlines
    [ "// File-private globals + free functions (no Swift class). Every generated"
    , "// kernel dylib shares the module name `JitMLMetal`, so a named class would"
    , "// register the same Objective-C class metadata in every dylib and collide"
    , "// when a daemon `dlopen`s many kernels into one process. Free functions over"
    , "// `let` globals avoid that collision. Globals are lazily, thread-safely"
    , "// initialised on first use."
    , "private let jitmlDevice: MTLDevice? = MTLCreateSystemDefaultDevice()"
    , "private let jitmlQueue: MTLCommandQueue? = jitmlDevice?.makeCommandQueue()"
    , ""
    , "// JIT-compile the embedded MSL at runtime. Fast-math is disabled for the"
    , "// determinism contract; `mathMode = .safe` is the macOS 15+ spelling, with"
    , "// the deprecated `fastMathEnabled` fallback for the `.macOS(.v14)` floor."
    , "private let jitmlLibrary: MTLLibrary? = {"
    , "  guard let device = jitmlDevice else { return nil }"
    , "  let options = MTLCompileOptions()"
    , "  if #available(macOS 15.0, *) { options.mathMode = .safe } else { options.fastMathEnabled = false }"
    , "  return try? device.makeLibrary(source: jitmlMetalSource, options: options)"
    , "}()"
    , ""
    , "private func jitmlPipeline(_ name: String) -> MTLComputePipelineState? {"
    , "  guard let device = jitmlDevice, let library = jitmlLibrary,"
    , "        let function = library.makeFunction(name: name),"
    , "        let state = try? device.makeComputePipelineState(function: function)"
    , "  else { return nil }"
    , "  return state"
    , "}"
    , ""
    , "private func jitmlRun(functionName: String,"
    , "                      out: UnsafeMutablePointer<Float>, outCount: Int,"
    , "                      input: UnsafePointer<Float>, inCount: Int,"
    , "                      weights: UnsafePointer<Float>?, weightsCount: Int) {"
    , "  // Fail closed: zero the output so a missing device / pipeline never"
    , "  // returns uninitialised host memory."
    , "  for i in 0..<outCount { out[i] = 0 }"
    , "  guard let device = jitmlDevice, let queue = jitmlQueue,"
    , "        let pipeline = jitmlPipeline(functionName),"
    , "        let commandBuffer = queue.makeCommandBuffer(),"
    , "        let encoder = commandBuffer.makeComputeCommandEncoder()"
    , "  else { return }"
    , ""
    , "  let floatStride = MemoryLayout<Float>.stride"
    , "  let inBytes = max(inCount, 1) * floatStride"
    , "  let outBytes = max(outCount, 1) * floatStride"
    , "  guard let inputBuffer = device.makeBuffer(bytes: input, length: inBytes, options: .storageModeShared),"
    , "        let outputBuffer = device.makeBuffer(length: outBytes, options: .storageModeShared)"
    , "  else { encoder.endEncoding(); return }"
    , ""
    , "  encoder.setComputePipelineState(pipeline)"
    , "  encoder.setBuffer(outputBuffer, offset: 0, index: 0)"
    , "  encoder.setBuffer(inputBuffer, offset: 0, index: 1)"
    , "  var elementCount = UInt32(inCount)"
    , "  encoder.setBytes(&elementCount, length: MemoryLayout<UInt32>.stride, index: 3)"
    , "  if let weights = weights {"
    , "    let weightBytes = max(weightsCount, 1) * floatStride"
    , "    if let weightBuffer = device.makeBuffer(bytes: weights, length: weightBytes, options: .storageModeShared) {"
    , "      encoder.setBuffer(weightBuffer, offset: 0, index: 2)"
    , "    }"
    , "    var weightLen = UInt32(weightsCount)"
    , "    encoder.setBytes(&weightLen, length: MemoryLayout<UInt32>.stride, index: 4)"
    , "  }"
    , ""
    , "  // Dispatch one thread per input element, in full threadgroups whose"
    , "  // width is a multiple of the 32-lane simd width, so simdgroup"
    , "  // reductions always tile the grid on 32-lane boundaries; the kernels"
    , "  // bound-check against the element count passed at buffer index 3."
    , "  let simdWidth = 32"
    , "  let maxThreadgroup = max(simdWidth, (pipeline.maxTotalThreadsPerThreadgroup / simdWidth) * simdWidth)"
    , "  let desired = ((max(inCount, 1) + simdWidth - 1) / simdWidth) * simdWidth"
    , "  let threadgroupWidth = max(simdWidth, min(maxThreadgroup, desired))"
    , "  let groups = (max(inCount, 1) + threadgroupWidth - 1) / threadgroupWidth"
    , "  encoder.dispatchThreadgroups("
    , "    MTLSize(width: groups, height: 1, depth: 1),"
    , "    threadsPerThreadgroup: MTLSize(width: threadgroupWidth, height: 1, depth: 1))"
    , "  encoder.endEncoding()"
    , "  commandBuffer.commit()"
    , "  commandBuffer.waitUntilCompleted()"
    , ""
    , "  memcpy(out, outputBuffer.contents(), outCount * floatStride)"
    , "}"
    ]

metalKernel :: KernelFamily -> Text
metalKernel family =
  Text.unlines
    [ "#include <metal_stdlib>"
    , "using namespace metal;"
    , ""
    , unweightedBody family
    , ""
    , weightedBody family
    ]

-- | Unweighted `jitml_kernel`. Every thread bound-checks against the element
-- count at buffer index 3 so the launcher can dispatch full (32-aligned)
-- threadgroups without reading or writing out of range.
unweightedBody :: KernelFamily -> Text
unweightedBody Reduction =
  Text.unlines
    [ "// Simdgroup reduction with deterministic single-stream launch order."
    , "// Padding lanes contribute 0.0f; lane 0 of each simdgroup whose base index"
    , "// is in range writes one partial, matching ceil(n / 32) outputs."
    , "kernel void jitml_kernel("
    , "    device float *out [[buffer(0)]],"
    , "    const device float *input [[buffer(1)]],"
    , "    constant uint &n [[buffer(3)]],"
    , "    uint id [[thread_position_in_grid]],"
    , "    uint tid_in_simd [[thread_index_in_simdgroup]]) {"
    , "  float v = (id < n) ? input[id] : 0.0f;"
    , "  v = simd_sum(v);"
    , "  uint base = id - tid_in_simd;"
    , "  if (tid_in_simd == 0u && base < n) { out[base / 32u] = v; }"
    , "}"
    ]
unweightedBody _family =
  Text.unlines
    [ "// Identity-class elementwise copy, bounded by the element count."
    , "kernel void jitml_kernel("
    , "    device float *out [[buffer(0)]],"
    , "    const device float *input [[buffer(1)]],"
    , "    constant uint &n [[buffer(3)]],"
    , "    uint id [[thread_position_in_grid]]) {"
    , "  if (id >= n) { return; }"
    , "  out[id] = input[id];"
    , "}"
    ]

-- | Weighted `jitml_weighted_kernel`. Sprint 14.5 lands the per-family
-- weighted Metal bodies, mirroring the CUDA `weightedFamilyImpl` math so the
-- cross-substrate parity cohort (Phase 15) compares like for like. Every body
-- shares the same buffer binding contract (out=0, input=1, weights=2, n=3,
-- wn=4) and per-thread bound check; only the compute differs by family.
weightedBody :: KernelFamily -> Text
weightedBody family =
  Text.unlines
    [ "kernel void jitml_weighted_kernel("
    , "    device float *out [[buffer(0)]],"
    , "    const device float *input [[buffer(1)]],"
    , "    const device float *weights [[buffer(2)]],"
    , "    constant uint &n [[buffer(3)]],"
    , "    constant uint &wn [[buffer(4)]],"
    , "    uint id [[thread_position_in_grid]]) {"
    , "  if (id >= n) { return; }"
    , weightedFamilyCompute family
    , "}"
    ]

-- | Per-family weighted compute, mirroring `JitML.Codegen.Cuda.weightedFamilyImpl`.
weightedFamilyCompute :: KernelFamily -> Text
weightedFamilyCompute Dense2D =
  -- out[i] = sum_j input[j] * W[j*n + i] (padded / truncated to n x n).
  Text.unlines
    [ "  float acc = 0.0f;"
    , "  for (uint j = 0u; j < n; ++j) {"
    , "    uint widx = j * n + id;"
    , "    float w = (widx < wn) ? weights[widx] : 0.0f;"
    , "    acc += input[j] * w;"
    , "  }"
    , "  out[id] = acc;"
    ]
weightedFamilyCompute Conv2DKernel = conv1x1WeightedCompute
weightedFamilyCompute Conv3DKernel = conv1x1WeightedCompute
weightedFamilyCompute BatchNormKernel =
  -- weights = [scale(n), shift(n), mean(n), variance(n)] with no-op defaults.
  Text.unlines
    [ "  float scale = (id < wn) ? weights[id] : 1.0f;"
    , "  float shift = (n + id < wn) ? weights[n + id] : 0.0f;"
    , "  float mean = (2u * n + id < wn) ? weights[2u * n + id] : 0.0f;"
    , "  float var = (3u * n + id < wn) ? weights[3u * n + id] : 1.0f;"
    , "  float eps = 1.0e-5f;"
    , "  out[id] = (input[id] - mean) / sqrt(var + eps) * scale + shift;"
    ]
weightedFamilyCompute LayerNormKernel =
  -- weights = [scale(n), shift(n)]; normalise over the input's own mean/var.
  Text.unlines
    [ "  float sum = 0.0f;"
    , "  for (uint j = 0u; j < n; ++j) { sum += input[j]; }"
    , "  float mean = sum / float(n);"
    , "  float varSum = 0.0f;"
    , "  for (uint j = 0u; j < n; ++j) { float d = input[j] - mean; varSum += d * d; }"
    , "  float var = varSum / float(n);"
    , "  float eps = 1.0e-5f;"
    , "  float scale = (id < wn) ? weights[id] : 1.0f;"
    , "  float shift = (n + id < wn) ? weights[n + id] : 0.0f;"
    , "  out[id] = ((input[id] - mean) / sqrt(var + eps)) * scale + shift;"
    ]
weightedFamilyCompute EmbeddingKernel =
  -- weights = row-major embedding table (table_rows * n); input supplies indices.
  Text.unlines
    [ "  if (wn == 0u) { out[id] = input[id]; return; }"
    , "  uint table_rows = wn / n;"
    , "  if (table_rows == 0u) { table_rows = 1u; }"
    , "  float fidx = input[id] < 0.0f ? 0.0f : input[id];"
    , "  uint row = (uint) fidx % table_rows;"
    , "  uint off = row * n + id;"
    , "  out[id] = (off < wn) ? weights[off] : 0.0f;"
    ]
weightedFamilyCompute MultiHeadAttentionKernel =
  -- weights = three n*n blocks (Wq, Wk, Wv);
  -- out[i] = sum_j (q[j] * k[j] * Wv[j*n+i]), q = input·Wq, k = input·Wk.
  -- No softmax (determinism contract: fixed-precision reduction only).
  Text.unlines
    [ "  uint block_size = n * n;"
    , "  float v = 0.0f;"
    , "  for (uint j = 0u; j < n; ++j) {"
    , "    float qsum = 0.0f;"
    , "    float ksum = 0.0f;"
    , "    for (uint k = 0u; k < n; ++k) {"
    , "      uint qi = k * n + j;"
    , "      uint ki = block_size + k * n + j;"
    , "      float wq = (qi < wn) ? weights[qi] : 0.0f;"
    , "      float wk = (ki < wn) ? weights[ki] : 0.0f;"
    , "      qsum += input[k] * wq;"
    , "      ksum += input[k] * wk;"
    , "    }"
    , "    uint vi = 2u * block_size + j * n + id;"
    , "    float wv = (vi < wn) ? weights[vi] : 0.0f;"
    , "    v += qsum * ksum * wv;"
    , "  }"
    , "  out[id] = v;"
    ]
weightedFamilyCompute _family =
  -- Identity / Reduction have no natural weight parameter: copy input through.
  "  out[id] = input[id];"

-- | 1x1 convolution: scale every position by the single filter coefficient
-- (defaulting to 1.0 when no weights are supplied). Shared by Conv2D / Conv3D.
conv1x1WeightedCompute :: Text
conv1x1WeightedCompute =
  Text.unlines
    [ "  float w = (wn > 0u) ? weights[0] : 1.0f;"
    , "  out[id] = input[id] * w;"
    ]

threadgroupSizeFor :: KernelFamily -> Int
threadgroupSizeFor Identity = 256
threadgroupSizeFor Reduction = 64
threadgroupSizeFor Dense2D = 128
threadgroupSizeFor Conv2DKernel = 256
threadgroupSizeFor Conv3DKernel = 256
threadgroupSizeFor BatchNormKernel = 128
threadgroupSizeFor LayerNormKernel = 128
threadgroupSizeFor MultiHeadAttentionKernel = 128
threadgroupSizeFor EmbeddingKernel = 64

metalOutputCountExpression :: KernelFamily -> Text
metalOutputCountExpression Reduction = "return n == 0 ? 0 : ((n - 1) / 32 + 1)"
metalOutputCountExpression _ = "return n"

swiftString :: Text -> Text
swiftString value =
  "\"" <> Text.concatMap escape value <> "\""

escape :: Char -> Text
escape '"' = "\\\""
escape '\\' = "\\\\"
escape '\n' = "\\n"
escape char = Text.singleton char
