{-# LANGUAGE OverloadedStrings #-}

module JitML.Codegen.Metal
  ( renderMetalPackage
  , renderMetalFamilyPackage
  , threadgroupSizeFor
  )
where

import Data.Text (Text)
import Data.Text qualified as Text

import JitML.Cache.Key (KernelSpec (..), Kind, TuningChoice (..), kindText)
import JitML.Codegen.KernelFamily (KernelFamily (..), familyName)
import JitML.Codegen.SourceFile (SourceFile (..))

renderMetalPackage :: KernelSpec -> Kind -> TuningChoice -> [SourceFile]
renderMetalPackage = renderMetalFamilyPackage Identity

renderMetalFamilyPackage
  :: KernelFamily -> KernelSpec -> Kind -> TuningChoice -> [SourceFile]
renderMetalFamilyPackage family kernelSpec kind tuningChoice =
  [ SourceFile "Package.swift" packageSwift
  , SourceFile
      "Sources/JitMLMetal/JitMLMetal.swift"
      (swiftSource family kernelSpec kind tuningChoice)
  , SourceFile "Sources/JitMLMetal/Kernels.metal" (metalKernel family)
  ]

packageSwift :: Text
packageSwift =
  Text.unlines
    [ "// swift-tools-version: 5.10"
    , "import PackageDescription"
    , ""
    , "let package = Package("
    , "  name: \"JitMLMetal\","
    , "  platforms: [.macOS(.v14)],"
    , "  products: [.library(name: \"JitMLMetal\", type: .dynamic, targets: [\"JitMLMetal\"])],"
    , "  targets: [.target(name: \"JitMLMetal\", resources: [.process(\"Kernels.metal\")])]"
    , ")"
    ]

swiftSource :: KernelFamily -> KernelSpec -> Kind -> TuningChoice -> Text
swiftSource family kernelSpec kind tuningChoice =
  Text.unlines
    [ "// Generated by jitml. Do not check generated Swift / Metal source into git."
    , "import Darwin"
    , "import Foundation"
    , "import Metal"
    , ""
    , "public enum JitMLGeneratedKernel {"
    , "  public static let kernelSpec = " <> swiftString (kernelSpecPayload kernelSpec)
    , "  public static let kernelKind = " <> swiftString (kindText kind)
    , "  public static let tuningChoice = " <> swiftString (unTuningChoice tuningChoice)
    , "  public static let kernelFamily = " <> swiftString (familyName family)
    , "  public static let threadgroupSize = " <> Text.pack (show (threadgroupSizeFor family))
    , "  public static let commandQueueDiscipline = \"single-stream-launch-order\""
    , "}"
    , ""
    , "private let jitmlKernelFamilyCString: UnsafeMutablePointer<CChar> = strdup("
        <> swiftString (familyName family)
        <> ")!"
    , ""
    , "@_cdecl(\"jitml_kernel_family_name\")"
    , "public func jitmlKernelFamilyName() -> UnsafePointer<CChar> {"
    , "  return UnsafePointer<CChar>(jitmlKernelFamilyCString)"
    , "}"
    , ""
    , "@_cdecl(\"jitml_kernel_output_count\")"
    , "public func jitmlKernelOutputCount(_ n: UInt) -> UInt {"
    , "  " <> metalOutputCountExpression family
    , "}"
    ]

metalKernel :: KernelFamily -> Text
metalKernel family =
  Text.unlines
    [ "#include <metal_stdlib>"
    , "using namespace metal;"
    , ""
    , metalBody family
    ]

metalBody :: KernelFamily -> Text
metalBody Identity =
  Text.unlines
    [ "kernel void jitml_kernel("
    , "    device float *out [[buffer(0)]],"
    , "    const device float *input [[buffer(1)]],"
    , "    uint id [[thread_position_in_grid]]) {"
    , "  out[id] = input[id];"
    , "}"
    ]
metalBody Reduction =
  Text.unlines
    [ "// Simdgroup reduction with deterministic single-stream launch order."
    , "kernel void jitml_kernel("
    , "    device float *out [[buffer(0)]],"
    , "    const device float *input [[buffer(1)]],"
    , "    uint id [[thread_position_in_grid]],"
    , "    uint tid_in_simd [[thread_index_in_simdgroup]]) {"
    , "  float v = input[id];"
    , "  v = simd_sum(v);"
    , "  if (tid_in_simd == 0) { out[id / 32u] = v; }"
    , "}"
    ]
metalBody Dense2D = metalBody Identity
metalBody Conv2DKernel = metalBody Identity
metalBody Conv3DKernel = metalBody Identity
metalBody BatchNormKernel = metalBody Identity
metalBody LayerNormKernel = metalBody Identity
metalBody MultiHeadAttentionKernel = metalBody Identity
metalBody EmbeddingKernel = metalBody Identity

threadgroupSizeFor :: KernelFamily -> Int
threadgroupSizeFor Identity = 256
threadgroupSizeFor Reduction = 64
threadgroupSizeFor Dense2D = 128
threadgroupSizeFor Conv2DKernel = 256
threadgroupSizeFor Conv3DKernel = 256
threadgroupSizeFor BatchNormKernel = 128
threadgroupSizeFor LayerNormKernel = 128
threadgroupSizeFor MultiHeadAttentionKernel = 128
threadgroupSizeFor EmbeddingKernel = 64

metalOutputCountExpression :: KernelFamily -> Text
metalOutputCountExpression Reduction = "return n == 0 ? 0 : ((n - 1) / 32 + 1)"
metalOutputCountExpression _ = "return n"

swiftString :: Text -> Text
swiftString value =
  "\"" <> Text.concatMap escape value <> "\""

escape :: Char -> Text
escape '"' = "\\\""
escape '\\' = "\\\\"
escape '\n' = "\\n"
escape char = Text.singleton char
