{-# LANGUAGE OverloadedStrings #-}

-- | Sprint 13.8 / 13.9 — nvcc-emitted forward/backward CUDA kernels for
-- the 'JitML.Numerics.Mlp' feed-forward network. This is the first real
-- step toward replacing the pure-Haskell backward pass with device
-- kernels (the single open item enumerated in Sprints 13.8 and 13.9
-- Remaining Work): the algorithmic contract — @y = W2 (tanh (W1 x + b1))
-- + b2@ and its manual reverse-mode gradient — is preserved, but the
-- arithmetic now runs on the GPU through generated CUDA.
--
-- The emitted @kernel.cu@ exposes two @extern \"C\"@ host wrappers that
-- own device allocation + host↔device copies:
--
--   * @jitml_mlp_forward@ — computes @hidden_pre@, @hidden_act = tanh
--     hidden_pre@, and @output = W2 hidden_act + b2@.
--   * @jitml_mlp_backward@ — given @dL/dy@, the forward @hidden_act@, the
--     input, and @W2@, computes the parameter gradients @gW1 / gB1 / gW2
--     / gB2@ exactly as 'JitML.Numerics.Mlp.mlpBackward'.
--
-- Each device thread accumulates its own reduction in a sequential loop
-- (no atomics, no warp-shuffle), so the result is bit-deterministic
-- run-to-run on the same device per the determinism contract. CUDA
-- single-precision arithmetic does not reproduce the host's @Double@
-- bit-for-bit; the backends test asserts agreement within a float
-- tolerance, and run-to-run device determinism exactly.
module JitML.Codegen.MlpCuda
  ( mlpCudaKernelSpec
  , renderMlpCudaSource
  )
where

import Data.Text (Text)
import Data.Text qualified as Text

import JitML.Cache.Key (KernelSpec (..))
import JitML.Codegen.SourceFile (SourceFile (..))

-- | The kernel-spec identifier for the MLP forward/backward CUDA kernel.
-- Distinct from the per-'KernelFamily' specs so it occupies its own JIT
-- cache slot.
mlpCudaKernelSpec :: KernelSpec
mlpCudaKernelSpec = KernelSpec "mlp-forward-backward-tanh-linear"

-- | The generated CUDA source files (one @kernel.cu@, matching the nvcc
-- compile command in "JitML.Engines.Engine").
renderMlpCudaSource :: [SourceFile]
renderMlpCudaSource = [SourceFile "kernel.cu" mlpCudaSource]

mlpCudaSource :: Text
mlpCudaSource =
  Text.unlines
    [ "// Generated by jitml. Do not check generated CUDA source into git."
    , "#include <cstddef>"
    , "#include <cstdio>"
    , "#include <cstdlib>"
    , "#include <cmath>"
    , "#include <cuda_runtime.h>"
    , ""
    , "static const char *jitml_mlp_rng_policy = \"host-seeded-no-curand\";"
    , "// determinism: --use_fast_math=false; TF32 disabled; per-thread sequential reductions"
    , ""
    , deviceHelpers
    , ""
    , forwardKernels
    , ""
    , backwardKernels
    , ""
    , forwardWrapper
    , ""
    , backwardWrapper
    , ""
    , batchedGradientKernels
    , ""
    , batchedOutputKernel
    , ""
    , batchedForwardWrapper
    , ""
    , batchedGradientWrapper
    , ""
    , batchedInputGradientKernels
    , ""
    , batchedInputGradientWrapper
    ]

deviceHelpers :: Text
deviceHelpers =
  Text.unlines
    [ "static void jitml_mlp_check(cudaError_t status, const char *op) {"
    , "  if (status != cudaSuccess) {"
    , "    std::fprintf(stderr, \"jitml mlp cuda error during %s: %s\\n\", op, cudaGetErrorString(status));"
    , "    std::abort();"
    , "  }"
    , "}"
    , ""
    , "static float *jitml_mlp_to_device(const float *host, std::size_t n) {"
    , "  if (n == 0) { return nullptr; }"
    , "  float *dev = nullptr;"
    , "  jitml_mlp_check(cudaMalloc(reinterpret_cast<void **>(&dev), n * sizeof(float)), \"cudaMalloc\");"
    , "  jitml_mlp_check(cudaMemcpy(dev, host, n * sizeof(float), cudaMemcpyHostToDevice), \"cudaMemcpy h2d\");"
    , "  return dev;"
    , "}"
    , ""
    , "static float *jitml_mlp_device_alloc(std::size_t n) {"
    , "  if (n == 0) { return nullptr; }"
    , "  float *dev = nullptr;"
    , "  jitml_mlp_check(cudaMalloc(reinterpret_cast<void **>(&dev), n * sizeof(float)), \"cudaMalloc out\");"
    , "  return dev;"
    , "}"
    , ""
    , "static void jitml_mlp_from_device(float *host, const float *dev, std::size_t n) {"
    , "  if (n == 0) { return; }"
    , "  jitml_mlp_check(cudaMemcpy(host, dev, n * sizeof(float), cudaMemcpyDeviceToHost), \"cudaMemcpy d2h\");"
    , "}"
    , ""
    , "static void jitml_mlp_free(float *ptr) { if (ptr != nullptr) { cudaFree(ptr); } }"
    ]

forwardKernels :: Text
forwardKernels =
  Text.unlines
    [ "// hidden_pre[i] = b1[i] + sum_j W1[i*inputs + j] * input[j]"
    , "// hidden_act[i] = tanh(hidden_pre[i])   (one thread per hidden unit)"
    , "static __global__ void jitml_mlp_hidden_kernel("
    , "    float *hidden_pre, float *hidden_act,"
    , "    const float *input, const float *w1, const float *b1,"
    , "    int inputs, int hidden) {"
    , "  int i = blockIdx.x * blockDim.x + threadIdx.x;"
    , "  if (i >= hidden) { return; }"
    , "  float acc = b1[i];"
    , "  for (int j = 0; j < inputs; ++j) {"
    , "    acc += w1[i * inputs + j] * input[j];"
    , "  }"
    , "  hidden_pre[i] = acc;"
    , "  hidden_act[i] = tanhf(acc);"
    , "}"
    , ""
    , "// output[k] = b2[k] + sum_i W2[k*hidden + i] * hidden_act[i]"
    , "static __global__ void jitml_mlp_output_kernel("
    , "    float *output, const float *hidden_act,"
    , "    const float *w2, const float *b2,"
    , "    int hidden, int outputs) {"
    , "  int k = blockIdx.x * blockDim.x + threadIdx.x;"
    , "  if (k >= outputs) { return; }"
    , "  float acc = b2[k];"
    , "  for (int i = 0; i < hidden; ++i) {"
    , "    acc += w2[k * hidden + i] * hidden_act[i];"
    , "  }"
    , "  output[k] = acc;"
    , "}"
    ]

backwardKernels :: Text
backwardKernels =
  Text.unlines
    [ "// gB2[k] = dL/dy[k];  gW2[k*hidden + i] = dL/dy[k] * hidden_act[i]"
    , "static __global__ void jitml_mlp_grad_output_kernel("
    , "    float *g_w2, float *g_b2,"
    , "    const float *d_l_dy, const float *hidden_act,"
    , "    int hidden, int outputs) {"
    , "  int k = blockIdx.x * blockDim.x + threadIdx.x;"
    , "  if (k >= outputs) { return; }"
    , "  float dy = d_l_dy[k];"
    , "  g_b2[k] = dy;"
    , "  for (int i = 0; i < hidden; ++i) {"
    , "    g_w2[k * hidden + i] = dy * hidden_act[i];"
    , "  }"
    , "}"
    , ""
    , "// d_act[i] = sum_k W2[k*hidden + i] * dL/dy[k]"
    , "// d_pre[i] = d_act[i] * (1 - hidden_act[i]^2)"
    , "// gB1[i] = d_pre[i];  gW1[i*inputs + j] = d_pre[i] * input[j]"
    , "static __global__ void jitml_mlp_grad_hidden_kernel("
    , "    float *g_w1, float *g_b1,"
    , "    const float *d_l_dy, const float *input,"
    , "    const float *hidden_act, const float *w2,"
    , "    int inputs, int hidden, int outputs) {"
    , "  int i = blockIdx.x * blockDim.x + threadIdx.x;"
    , "  if (i >= hidden) { return; }"
    , "  float d_act = 0.0f;"
    , "  for (int k = 0; k < outputs; ++k) {"
    , "    d_act += w2[k * hidden + i] * d_l_dy[k];"
    , "  }"
    , "  float h = hidden_act[i];"
    , "  float d_pre = d_act * (1.0f - h * h);"
    , "  g_b1[i] = d_pre;"
    , "  for (int j = 0; j < inputs; ++j) {"
    , "    g_w1[i * inputs + j] = d_pre * input[j];"
    , "  }"
    , "}"
    ]

forwardWrapper :: Text
forwardWrapper =
  Text.unlines
    [ "extern \"C\" void jitml_mlp_forward("
    , "    float *hidden_pre, float *hidden_act, float *output,"
    , "    const float *input, const float *w1, const float *b1,"
    , "    const float *w2, const float *b2,"
    , "    int inputs, int hidden, int outputs) {"
    , "  if (hidden <= 0 || outputs <= 0) { return; }"
    , "  std::size_t w1n = static_cast<std::size_t>(hidden) * static_cast<std::size_t>(inputs);"
    , "  std::size_t w2n = static_cast<std::size_t>(outputs) * static_cast<std::size_t>(hidden);"
    , "  float *d_input = jitml_mlp_to_device(input, static_cast<std::size_t>(inputs));"
    , "  float *d_w1 = jitml_mlp_to_device(w1, w1n);"
    , "  float *d_b1 = jitml_mlp_to_device(b1, static_cast<std::size_t>(hidden));"
    , "  float *d_w2 = jitml_mlp_to_device(w2, w2n);"
    , "  float *d_b2 = jitml_mlp_to_device(b2, static_cast<std::size_t>(outputs));"
    , "  float *d_hidden_pre = jitml_mlp_device_alloc(static_cast<std::size_t>(hidden));"
    , "  float *d_hidden_act = jitml_mlp_device_alloc(static_cast<std::size_t>(hidden));"
    , "  float *d_output = jitml_mlp_device_alloc(static_cast<std::size_t>(outputs));"
    , "  dim3 block(256);"
    , "  dim3 grid_hidden(static_cast<unsigned int>((hidden + 255) / 256));"
    , "  jitml_mlp_hidden_kernel<<<grid_hidden, block>>>("
    , "      d_hidden_pre, d_hidden_act, d_input, d_w1, d_b1, inputs, hidden);"
    , "  jitml_mlp_check(cudaGetLastError(), \"hidden launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"hidden sync\");"
    , "  dim3 grid_output(static_cast<unsigned int>((outputs + 255) / 256));"
    , "  jitml_mlp_output_kernel<<<grid_output, block>>>("
    , "      d_output, d_hidden_act, d_w2, d_b2, hidden, outputs);"
    , "  jitml_mlp_check(cudaGetLastError(), \"output launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"output sync\");"
    , "  jitml_mlp_from_device(hidden_pre, d_hidden_pre, static_cast<std::size_t>(hidden));"
    , "  jitml_mlp_from_device(hidden_act, d_hidden_act, static_cast<std::size_t>(hidden));"
    , "  jitml_mlp_from_device(output, d_output, static_cast<std::size_t>(outputs));"
    , "  jitml_mlp_free(d_input); jitml_mlp_free(d_w1); jitml_mlp_free(d_b1);"
    , "  jitml_mlp_free(d_w2); jitml_mlp_free(d_b2);"
    , "  jitml_mlp_free(d_hidden_pre); jitml_mlp_free(d_hidden_act); jitml_mlp_free(d_output);"
    , "}"
    ]

backwardWrapper :: Text
backwardWrapper =
  Text.unlines
    [ "extern \"C\" void jitml_mlp_backward("
    , "    float *g_w1, float *g_b1, float *g_w2, float *g_b2,"
    , "    const float *d_l_dy, const float *input,"
    , "    const float *hidden_act, const float *w2,"
    , "    int inputs, int hidden, int outputs) {"
    , "  if (hidden <= 0 || outputs <= 0) { return; }"
    , "  std::size_t w1n = static_cast<std::size_t>(hidden) * static_cast<std::size_t>(inputs);"
    , "  std::size_t w2n = static_cast<std::size_t>(outputs) * static_cast<std::size_t>(hidden);"
    , "  float *d_dy = jitml_mlp_to_device(d_l_dy, static_cast<std::size_t>(outputs));"
    , "  float *d_input = jitml_mlp_to_device(input, static_cast<std::size_t>(inputs));"
    , "  float *d_hidden_act = jitml_mlp_to_device(hidden_act, static_cast<std::size_t>(hidden));"
    , "  float *d_w2 = jitml_mlp_to_device(w2, w2n);"
    , "  float *d_g_w1 = jitml_mlp_device_alloc(w1n);"
    , "  float *d_g_b1 = jitml_mlp_device_alloc(static_cast<std::size_t>(hidden));"
    , "  float *d_g_w2 = jitml_mlp_device_alloc(w2n);"
    , "  float *d_g_b2 = jitml_mlp_device_alloc(static_cast<std::size_t>(outputs));"
    , "  dim3 block(256);"
    , "  dim3 grid_output(static_cast<unsigned int>((outputs + 255) / 256));"
    , "  jitml_mlp_grad_output_kernel<<<grid_output, block>>>("
    , "      d_g_w2, d_g_b2, d_dy, d_hidden_act, hidden, outputs);"
    , "  jitml_mlp_check(cudaGetLastError(), \"grad output launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"grad output sync\");"
    , "  dim3 grid_hidden(static_cast<unsigned int>((hidden + 255) / 256));"
    , "  jitml_mlp_grad_hidden_kernel<<<grid_hidden, block>>>("
    , "      d_g_w1, d_g_b1, d_dy, d_input, d_hidden_act, d_w2, inputs, hidden, outputs);"
    , "  jitml_mlp_check(cudaGetLastError(), \"grad hidden launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"grad hidden sync\");"
    , "  jitml_mlp_from_device(g_w1, d_g_w1, w1n);"
    , "  jitml_mlp_from_device(g_b1, d_g_b1, static_cast<std::size_t>(hidden));"
    , "  jitml_mlp_from_device(g_w2, d_g_w2, w2n);"
    , "  jitml_mlp_from_device(g_b2, d_g_b2, static_cast<std::size_t>(outputs));"
    , "  jitml_mlp_free(d_dy); jitml_mlp_free(d_input); jitml_mlp_free(d_hidden_act);"
    , "  jitml_mlp_free(d_w2);"
    , "  jitml_mlp_free(d_g_w1); jitml_mlp_free(d_g_b1); jitml_mlp_free(d_g_w2); jitml_mlp_free(d_g_b2);"
    , "}"
    ]

-- | Sprint 13.8 — batched forward + summed-gradient backward device
-- kernels. The fused @jitml_mlp_batch_gradient@ wrapper (below) computes
-- one minibatch's gradient — summed over the @batch@ rows — in a single
-- device round-trip, amortising host↔device copies over the whole batch
-- (the trainer hot-path adoption these kernels enable). Layouts are
-- row-major: @input@ is @batch × inputs@, @d_l_dy@ is @batch × outputs@,
-- @hidden_act@ is @batch × hidden@. Each gradient element is reduced by a
-- single thread with sequential sums over the batch (no atomics), so the
-- summed gradient is bit-deterministic run-to-run on the same device.
batchedGradientKernels :: Text
batchedGradientKernels =
  Text.unlines
    [ "// hidden_act[b][i] = tanh(b1[i] + sum_j W1[i][j] * input[b][j])"
    , "static __global__ void jitml_mlp_batch_hidden_kernel("
    , "    float *hidden_act, const float *input, const float *w1, const float *b1,"
    , "    int inputs, int hidden, int batch) {"
    , "  std::size_t idx = static_cast<std::size_t>(blockIdx.x) * blockDim.x + threadIdx.x;"
    , "  std::size_t total = static_cast<std::size_t>(batch) * static_cast<std::size_t>(hidden);"
    , "  if (idx >= total) { return; }"
    , "  int b = static_cast<int>(idx / hidden);"
    , "  int i = static_cast<int>(idx % hidden);"
    , "  float acc = b1[i];"
    , "  for (int j = 0; j < inputs; ++j) {"
    , "    acc += w1[i * inputs + j] * input[b * inputs + j];"
    , "  }"
    , "  hidden_act[b * hidden + i] = tanhf(acc);"
    , "}"
    , ""
    , "// gB2[k] = sum_b dy[b][k];  gW2[k][i] = sum_b dy[b][k] * hidden_act[b][i]"
    , "static __global__ void jitml_mlp_batch_grad_output_kernel("
    , "    float *g_w2, float *g_b2, const float *d_l_dy, const float *hidden_act,"
    , "    int hidden, int outputs, int batch) {"
    , "  int k = blockIdx.x * blockDim.x + threadIdx.x;"
    , "  if (k >= outputs) { return; }"
    , "  float gb = 0.0f;"
    , "  for (int b = 0; b < batch; ++b) { gb += d_l_dy[b * outputs + k]; }"
    , "  g_b2[k] = gb;"
    , "  for (int i = 0; i < hidden; ++i) {"
    , "    float gw = 0.0f;"
    , "    for (int b = 0; b < batch; ++b) {"
    , "      gw += d_l_dy[b * outputs + k] * hidden_act[b * hidden + i];"
    , "    }"
    , "    g_w2[k * hidden + i] = gw;"
    , "  }"
    , "}"
    , ""
    , "// d_pre[b][i] = (sum_k W2[k][i]*dy[b][k]) * (1 - hidden_act[b][i]^2)"
    , "// gB1[i] = sum_b d_pre[b][i];  gW1[i][j] = sum_b d_pre[b][i] * input[b][j]"
    , "static __global__ void jitml_mlp_batch_grad_hidden_kernel("
    , "    float *g_w1, float *g_b1, const float *d_l_dy, const float *input,"
    , "    const float *hidden_act, const float *w2,"
    , "    int inputs, int hidden, int outputs, int batch) {"
    , "  int i = blockIdx.x * blockDim.x + threadIdx.x;"
    , "  if (i >= hidden) { return; }"
    , "  float gb1 = 0.0f;"
    , "  for (int j = 0; j < inputs; ++j) { g_w1[i * inputs + j] = 0.0f; }"
    , "  for (int b = 0; b < batch; ++b) {"
    , "    float d_act = 0.0f;"
    , "    for (int k = 0; k < outputs; ++k) {"
    , "      d_act += w2[k * hidden + i] * d_l_dy[b * outputs + k];"
    , "    }"
    , "    float h = hidden_act[b * hidden + i];"
    , "    float d_pre = d_act * (1.0f - h * h);"
    , "    gb1 += d_pre;"
    , "    for (int j = 0; j < inputs; ++j) {"
    , "      g_w1[i * inputs + j] += d_pre * input[b * inputs + j];"
    , "    }"
    , "  }"
    , "  g_b1[i] = gb1;"
    , "}"
    ]

-- | Batched output kernel: @output[b][k] = b2[k] + sum_i W2[k][i] *
-- hidden_act[b][i]@ (one thread per @(b, k)@). Pairs with
-- 'batchedGradientKernels'' batched hidden kernel to form the batched
-- forward pass.
batchedOutputKernel :: Text
batchedOutputKernel =
  Text.unlines
    [ "static __global__ void jitml_mlp_batch_output_kernel("
    , "    float *output, const float *hidden_act, const float *w2, const float *b2,"
    , "    int hidden, int outputs, int batch) {"
    , "  std::size_t idx = static_cast<std::size_t>(blockIdx.x) * blockDim.x + threadIdx.x;"
    , "  std::size_t total = static_cast<std::size_t>(batch) * static_cast<std::size_t>(outputs);"
    , "  if (idx >= total) { return; }"
    , "  int b = static_cast<int>(idx / outputs);"
    , "  int k = static_cast<int>(idx % outputs);"
    , "  float acc = b2[k];"
    , "  for (int i = 0; i < hidden; ++i) {"
    , "    acc += w2[k * hidden + i] * hidden_act[b * hidden + i];"
    , "  }"
    , "  output[b * outputs + k] = acc;"
    , "}"
    ]

-- | Batched forward wrapper: runs the network forward over the whole
-- minibatch in one device round-trip and returns the per-sample outputs
-- (@batch × outputs@ row-major). Used by a CUDA trainer to obtain the
-- minibatch's policy/value outputs (for the loss gradient) before the
-- matching 'batchedGradientWrapper' backward call.
batchedForwardWrapper :: Text
batchedForwardWrapper =
  Text.unlines
    [ "extern \"C\" void jitml_mlp_forward_batch("
    , "    float *output, const float *input,"
    , "    const float *w1, const float *b1, const float *w2, const float *b2,"
    , "    int inputs, int hidden, int outputs, int batch) {"
    , "  if (hidden <= 0 || outputs <= 0 || batch <= 0) { return; }"
    , "  std::size_t in_n = static_cast<std::size_t>(batch) * static_cast<std::size_t>(inputs);"
    , "  std::size_t out_n = static_cast<std::size_t>(batch) * static_cast<std::size_t>(outputs);"
    , "  std::size_t hact_n = static_cast<std::size_t>(batch) * static_cast<std::size_t>(hidden);"
    , "  std::size_t w1n = static_cast<std::size_t>(hidden) * static_cast<std::size_t>(inputs);"
    , "  std::size_t w2n = static_cast<std::size_t>(outputs) * static_cast<std::size_t>(hidden);"
    , "  float *d_input = jitml_mlp_to_device(input, in_n);"
    , "  float *d_w1 = jitml_mlp_to_device(w1, w1n);"
    , "  float *d_b1 = jitml_mlp_to_device(b1, static_cast<std::size_t>(hidden));"
    , "  float *d_w2 = jitml_mlp_to_device(w2, w2n);"
    , "  float *d_b2 = jitml_mlp_to_device(b2, static_cast<std::size_t>(outputs));"
    , "  float *d_hidden_act = jitml_mlp_device_alloc(hact_n);"
    , "  float *d_output = jitml_mlp_device_alloc(out_n);"
    , "  dim3 block(256);"
    , "  dim3 grid_hidden(static_cast<unsigned int>((hact_n + 255) / 256));"
    , "  jitml_mlp_batch_hidden_kernel<<<grid_hidden, block>>>("
    , "      d_hidden_act, d_input, d_w1, d_b1, inputs, hidden, batch);"
    , "  jitml_mlp_check(cudaGetLastError(), \"batch forward hidden launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"batch forward hidden sync\");"
    , "  dim3 grid_output(static_cast<unsigned int>((out_n + 255) / 256));"
    , "  jitml_mlp_batch_output_kernel<<<grid_output, block>>>("
    , "      d_output, d_hidden_act, d_w2, d_b2, hidden, outputs, batch);"
    , "  jitml_mlp_check(cudaGetLastError(), \"batch forward output launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"batch forward output sync\");"
    , "  jitml_mlp_from_device(output, d_output, out_n);"
    , "  jitml_mlp_free(d_input); jitml_mlp_free(d_w1); jitml_mlp_free(d_b1);"
    , "  jitml_mlp_free(d_w2); jitml_mlp_free(d_b2);"
    , "  jitml_mlp_free(d_hidden_act); jitml_mlp_free(d_output);"
    , "}"
    ]

batchedGradientWrapper :: Text
batchedGradientWrapper =
  Text.unlines
    [ "extern \"C\" void jitml_mlp_batch_gradient("
    , "    float *g_w1, float *g_b1, float *g_w2, float *g_b2,"
    , "    const float *input, const float *d_l_dy,"
    , "    const float *w1, const float *b1, const float *w2,"
    , "    int inputs, int hidden, int outputs, int batch) {"
    , "  if (hidden <= 0 || outputs <= 0 || batch <= 0) { return; }"
    , "  std::size_t in_n = static_cast<std::size_t>(batch) * static_cast<std::size_t>(inputs);"
    , "  std::size_t dy_n = static_cast<std::size_t>(batch) * static_cast<std::size_t>(outputs);"
    , "  std::size_t hact_n = static_cast<std::size_t>(batch) * static_cast<std::size_t>(hidden);"
    , "  std::size_t w1n = static_cast<std::size_t>(hidden) * static_cast<std::size_t>(inputs);"
    , "  std::size_t w2n = static_cast<std::size_t>(outputs) * static_cast<std::size_t>(hidden);"
    , "  float *d_input = jitml_mlp_to_device(input, in_n);"
    , "  float *d_dy = jitml_mlp_to_device(d_l_dy, dy_n);"
    , "  float *d_w1 = jitml_mlp_to_device(w1, w1n);"
    , "  float *d_b1 = jitml_mlp_to_device(b1, static_cast<std::size_t>(hidden));"
    , "  float *d_w2 = jitml_mlp_to_device(w2, w2n);"
    , "  float *d_hidden_act = jitml_mlp_device_alloc(hact_n);"
    , "  float *d_g_w1 = jitml_mlp_device_alloc(w1n);"
    , "  float *d_g_b1 = jitml_mlp_device_alloc(static_cast<std::size_t>(hidden));"
    , "  float *d_g_w2 = jitml_mlp_device_alloc(w2n);"
    , "  float *d_g_b2 = jitml_mlp_device_alloc(static_cast<std::size_t>(outputs));"
    , "  dim3 block(256);"
    , "  dim3 grid_hidden_fwd(static_cast<unsigned int>((hact_n + 255) / 256));"
    , "  jitml_mlp_batch_hidden_kernel<<<grid_hidden_fwd, block>>>("
    , "      d_hidden_act, d_input, d_w1, d_b1, inputs, hidden, batch);"
    , "  jitml_mlp_check(cudaGetLastError(), \"batch hidden launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"batch hidden sync\");"
    , "  dim3 grid_output(static_cast<unsigned int>((outputs + 255) / 256));"
    , "  jitml_mlp_batch_grad_output_kernel<<<grid_output, block>>>("
    , "      d_g_w2, d_g_b2, d_dy, d_hidden_act, hidden, outputs, batch);"
    , "  jitml_mlp_check(cudaGetLastError(), \"batch grad output launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"batch grad output sync\");"
    , "  dim3 grid_hidden(static_cast<unsigned int>((hidden + 255) / 256));"
    , "  jitml_mlp_batch_grad_hidden_kernel<<<grid_hidden, block>>>("
    , "      d_g_w1, d_g_b1, d_dy, d_input, d_hidden_act, d_w2, inputs, hidden, outputs, batch);"
    , "  jitml_mlp_check(cudaGetLastError(), \"batch grad hidden launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"batch grad hidden sync\");"
    , "  jitml_mlp_from_device(g_w1, d_g_w1, w1n);"
    , "  jitml_mlp_from_device(g_b1, d_g_b1, static_cast<std::size_t>(hidden));"
    , "  jitml_mlp_from_device(g_w2, d_g_w2, w2n);"
    , "  jitml_mlp_from_device(g_b2, d_g_b2, static_cast<std::size_t>(outputs));"
    , "  jitml_mlp_free(d_input); jitml_mlp_free(d_dy); jitml_mlp_free(d_w1);"
    , "  jitml_mlp_free(d_b1); jitml_mlp_free(d_w2); jitml_mlp_free(d_hidden_act);"
    , "  jitml_mlp_free(d_g_w1); jitml_mlp_free(d_g_b1); jitml_mlp_free(d_g_w2); jitml_mlp_free(d_g_b2);"
    , "}"
    ]

-- | Sprint 13.8 — batched device /input/-gradient kernels. The
-- @jitml_mlp_input_gradient_batch@ wrapper (below) computes @dL/dx@ for
-- every sample in a minibatch in one device round-trip:
-- @dL/dx = W1^T @ ((W2^T @ dL/dy) * (1 - tanh(hidden_pre)^2))@. Unlike the
-- parameter gradient (summed over the batch), the input gradient is
-- per-sample (each sample has its own @dL/dx@), so the output is
-- @batch × inputs@. This is the missing primitive for the continuous
-- actor-critic deterministic-policy gradient (@dQ/da@ = the action-slice
-- of the critic's input gradient). Per-thread sequential reductions →
-- bit-deterministic run-to-run on the same device.
batchedInputGradientKernels :: Text
batchedInputGradientKernels =
  Text.unlines
    [ "// d_pre[b][i] = (sum_k W2[k][i] * dL/dy[b][k]) * (1 - hidden_act[b][i]^2)"
    , "static __global__ void jitml_mlp_dhidden_pre_batch_kernel("
    , "    float *d_hidden_pre, const float *d_l_dy, const float *hidden_act,"
    , "    const float *w2, int hidden, int outputs, int batch) {"
    , "  std::size_t idx = static_cast<std::size_t>(blockIdx.x) * blockDim.x + threadIdx.x;"
    , "  std::size_t total = static_cast<std::size_t>(batch) * static_cast<std::size_t>(hidden);"
    , "  if (idx >= total) { return; }"
    , "  int b = static_cast<int>(idx / hidden);"
    , "  int i = static_cast<int>(idx % hidden);"
    , "  float d_act = 0.0f;"
    , "  for (int k = 0; k < outputs; ++k) {"
    , "    d_act += w2[k * hidden + i] * d_l_dy[b * outputs + k];"
    , "  }"
    , "  float h = hidden_act[b * hidden + i];"
    , "  d_hidden_pre[b * hidden + i] = d_act * (1.0f - h * h);"
    , "}"
    , ""
    , "// dx[b][j] = sum_i W1[i][j] * d_hidden_pre[b][i]"
    , "static __global__ void jitml_mlp_dx_batch_kernel("
    , "    float *dx, const float *d_hidden_pre, const float *w1,"
    , "    int inputs, int hidden, int batch) {"
    , "  std::size_t idx = static_cast<std::size_t>(blockIdx.x) * blockDim.x + threadIdx.x;"
    , "  std::size_t total = static_cast<std::size_t>(batch) * static_cast<std::size_t>(inputs);"
    , "  if (idx >= total) { return; }"
    , "  int b = static_cast<int>(idx / inputs);"
    , "  int j = static_cast<int>(idx % inputs);"
    , "  float acc = 0.0f;"
    , "  for (int i = 0; i < hidden; ++i) {"
    , "    acc += w1[i * inputs + j] * d_hidden_pre[b * hidden + i];"
    , "  }"
    , "  dx[b * inputs + j] = acc;"
    , "}"
    ]

batchedInputGradientWrapper :: Text
batchedInputGradientWrapper =
  Text.unlines
    [ "extern \"C\" void jitml_mlp_input_gradient_batch("
    , "    float *dx, const float *input, const float *d_l_dy,"
    , "    const float *w1, const float *b1, const float *w2,"
    , "    int inputs, int hidden, int outputs, int batch) {"
    , "  if (hidden <= 0 || outputs <= 0 || inputs <= 0 || batch <= 0) { return; }"
    , "  std::size_t in_n = static_cast<std::size_t>(batch) * static_cast<std::size_t>(inputs);"
    , "  std::size_t dy_n = static_cast<std::size_t>(batch) * static_cast<std::size_t>(outputs);"
    , "  std::size_t hact_n = static_cast<std::size_t>(batch) * static_cast<std::size_t>(hidden);"
    , "  std::size_t w1n = static_cast<std::size_t>(hidden) * static_cast<std::size_t>(inputs);"
    , "  std::size_t w2n = static_cast<std::size_t>(outputs) * static_cast<std::size_t>(hidden);"
    , "  float *d_input = jitml_mlp_to_device(input, in_n);"
    , "  float *d_dy = jitml_mlp_to_device(d_l_dy, dy_n);"
    , "  float *d_w1 = jitml_mlp_to_device(w1, w1n);"
    , "  float *d_b1 = jitml_mlp_to_device(b1, static_cast<std::size_t>(hidden));"
    , "  float *d_w2 = jitml_mlp_to_device(w2, w2n);"
    , "  float *d_hidden_act = jitml_mlp_device_alloc(hact_n);"
    , "  float *d_hidden_pre = jitml_mlp_device_alloc(hact_n);"
    , "  float *d_dx = jitml_mlp_device_alloc(in_n);"
    , "  dim3 block(256);"
    , "  dim3 grid_hidden(static_cast<unsigned int>((hact_n + 255) / 256));"
    , "  jitml_mlp_batch_hidden_kernel<<<grid_hidden, block>>>("
    , "      d_hidden_act, d_input, d_w1, d_b1, inputs, hidden, batch);"
    , "  jitml_mlp_check(cudaGetLastError(), \"input-grad hidden launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"input-grad hidden sync\");"
    , "  jitml_mlp_dhidden_pre_batch_kernel<<<grid_hidden, block>>>("
    , "      d_hidden_pre, d_dy, d_hidden_act, d_w2, hidden, outputs, batch);"
    , "  jitml_mlp_check(cudaGetLastError(), \"input-grad dpre launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"input-grad dpre sync\");"
    , "  dim3 grid_input(static_cast<unsigned int>((in_n + 255) / 256));"
    , "  jitml_mlp_dx_batch_kernel<<<grid_input, block>>>("
    , "      d_dx, d_hidden_pre, d_w1, inputs, hidden, batch);"
    , "  jitml_mlp_check(cudaGetLastError(), \"input-grad dx launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"input-grad dx sync\");"
    , "  jitml_mlp_from_device(dx, d_dx, in_n);"
    , "  jitml_mlp_free(d_input); jitml_mlp_free(d_dy); jitml_mlp_free(d_w1);"
    , "  jitml_mlp_free(d_b1); jitml_mlp_free(d_w2);"
    , "  jitml_mlp_free(d_hidden_act); jitml_mlp_free(d_hidden_pre); jitml_mlp_free(d_dx);"
    , "}"
    ]
