{-# LANGUAGE OverloadedStrings #-}

-- | Sprint 13.8 / 13.9 — nvcc-emitted forward/backward CUDA kernels for
-- the 'JitML.Numerics.Mlp' feed-forward network. This is the first real
-- step toward replacing the pure-Haskell backward pass with device
-- kernels (the single open item enumerated in Sprints 13.8 and 13.9
-- Remaining Work): the algorithmic contract — @y = W2 (tanh (W1 x + b1))
-- + b2@ and its manual reverse-mode gradient — is preserved, but the
-- arithmetic now runs on the GPU through generated CUDA.
--
-- The emitted @kernel.cu@ exposes two @extern \"C\"@ host wrappers that
-- own device allocation + host↔device copies:
--
--   * @jitml_mlp_forward@ — computes @hidden_pre@, @hidden_act = tanh
--     hidden_pre@, and @output = W2 hidden_act + b2@.
--   * @jitml_mlp_backward@ — given @dL/dy@, the forward @hidden_act@, the
--     input, and @W2@, computes the parameter gradients @gW1 / gB1 / gW2
--     / gB2@ exactly as 'JitML.Numerics.Mlp.mlpBackward'.
--
-- CUDA keeps persistent device copies of the parameter tensors keyed by
-- content hash and shape. Inputs, outputs, and gradients remain per-call
-- buffers, but W1/B1/W2/B2 upload once per fixed-parameter phase and are
-- reused by the forward, batch-forward, batch-gradient, and input-gradient
-- wrappers until the host weights change.
--
-- Each device thread accumulates its own reduction in a sequential loop
-- (no atomics, no warp-shuffle), so the result is bit-deterministic
-- run-to-run on the same device per the determinism contract. CUDA
-- single-precision arithmetic does not reproduce the host's @Double@
-- bit-for-bit; the backends test asserts agreement within a float
-- tolerance, and run-to-run device determinism exactly.
--
-- Against the /other/ Linux lane the bar is higher and exact. Sprint `265.1`
-- renders the activation through 'mlpCudaActivation' rather than CUDA's
-- @tanhf@, so this artifact and the @linux-cpu@ oneDNN artifact evaluate one
-- function one way. Every element-wise accumulation order already matched, so
-- with the activation aligned the two lanes agree __bit for bit__ on the
-- batched parameter gradient, and @jitml-backends --linux-cuda@ carries a
-- standing case that fails closed if they drift apart again.
module JitML.Codegen.MlpCuda
  ( mlpCudaKernelSpec
  , renderMlpCudaSource
  , mlpCudaActivation
  )
where

import Data.Text (Text)
import Data.Text qualified as Text

import JitML.Cache.Key (KernelSpec (..))
import JitML.Codegen.SourceFile (SourceFile (..))

-- | The kernel-spec identifier for the MLP forward/backward CUDA kernel.
-- Distinct from the per-'KernelFamily' specs so it occupies its own JIT
-- cache slot.
mlpCudaKernelSpec :: KernelSpec
mlpCudaKernelSpec = KernelSpec "mlp-forward-backward-tanh-linear"

-- | The generated CUDA source files (one @kernel.cu@, matching the nvcc
-- compile command in "JitML.Engines.Engine").
renderMlpCudaSource :: [SourceFile]
renderMlpCudaSource = [SourceFile "kernel.cu" mlpCudaSource]

mlpCudaSource :: Text
mlpCudaSource =
  Text.unlines
    [ "// Generated by jitml. Do not check generated CUDA source into git."
    , "#include <cstddef>"
    , "#include <cstdint>"
    , "#include <cstdio>"
    , "#include <cstdlib>"
    , "#include <cmath>"
    , "#include <cuda_runtime.h>"
    , ""
    , "static const char *jitml_mlp_rng_policy = \"host-seeded-no-curand\";"
    , -- Sprint `78.1` — the compile-line arguments are named by the artifact's
      -- toolchain fingerprint, which reads them off the compile command. This
      -- comment used to restate `--use_fast_math=false`, which no compile line
      -- passes.
      "// determinism: no device-side atomics; per-thread sequential reductions"
    , ""
    , deviceHelpers
    , ""
    , activationHelpers
    , ""
    , forwardKernels
    , ""
    , backwardKernels
    , ""
    , forwardWrapper
    , ""
    , backwardWrapper
    , ""
    , batchedGradientKernels
    , ""
    , batchedOutputKernel
    , ""
    , batchedForwardWrapper
    , ""
    , batchedGradientWrapper
    , ""
    , batchedInputGradientKernels
    , ""
    , batchedInputGradientWrapper
    ]

deviceHelpers :: Text
deviceHelpers =
  Text.unlines
    [ "static void jitml_mlp_check(cudaError_t status, const char *op) {"
    , "  if (status != cudaSuccess) {"
    , "    std::fprintf(stderr, \"jitml mlp cuda error during %s: %s\\n\", op, cudaGetErrorString(status));"
    , "    std::abort();"
    , "  }"
    , "}"
    , ""
    , "struct jitml_mlp_cached_buffer {"
    , "  std::uint64_t hash;"
    , "  std::size_t n;"
    , "  float *dev;"
    , "  bool valid;"
    , "};"
    , ""
    , "static jitml_mlp_cached_buffer jitml_mlp_weight_cache[4] = {"
    , "  {0u, 0u, nullptr, false},"
    , "  {0u, 0u, nullptr, false},"
    , "  {0u, 0u, nullptr, false},"
    , "  {0u, 0u, nullptr, false}"
    , "};"
    , ""
    , "static void jitml_mlp_clear_weight_cache() {"
    , "  for (int i = 0; i < 4; ++i) {"
    , "    if (jitml_mlp_weight_cache[i].dev != nullptr) {"
    , "      (void)cudaFree(jitml_mlp_weight_cache[i].dev);"
    , "      jitml_mlp_weight_cache[i].dev = nullptr;"
    , "    }"
    , "    jitml_mlp_weight_cache[i].hash = 0u;"
    , "    jitml_mlp_weight_cache[i].n = 0u;"
    , "    jitml_mlp_weight_cache[i].valid = false;"
    , "  }"
    , "}"
    , ""
    , "static float *jitml_mlp_to_device(const float *host, std::size_t n) {"
    , "  if (n == 0) { return nullptr; }"
    , "  float *dev = nullptr;"
    , "  cudaError_t status = cudaMalloc(reinterpret_cast<void **>(&dev), n * sizeof(float));"
    , "  if (status != cudaSuccess) {"
    , "    jitml_mlp_clear_weight_cache();"
    , "    status = cudaMalloc(reinterpret_cast<void **>(&dev), n * sizeof(float));"
    , "  }"
    , "  jitml_mlp_check(status, \"cudaMalloc\");"
    , "  jitml_mlp_check(cudaMemcpy(dev, host, n * sizeof(float), cudaMemcpyHostToDevice), \"cudaMemcpy h2d\");"
    , "  return dev;"
    , "}"
    , ""
    , "static float *jitml_mlp_device_alloc(std::size_t n) {"
    , "  if (n == 0) { return nullptr; }"
    , "  float *dev = nullptr;"
    , "  cudaError_t status = cudaMalloc(reinterpret_cast<void **>(&dev), n * sizeof(float));"
    , "  if (status != cudaSuccess) {"
    , "    jitml_mlp_clear_weight_cache();"
    , "    status = cudaMalloc(reinterpret_cast<void **>(&dev), n * sizeof(float));"
    , "  }"
    , "  jitml_mlp_check(status, \"cudaMalloc out\");"
    , "  return dev;"
    , "}"
    , ""
    , "static void jitml_mlp_from_device(float *host, const float *dev, std::size_t n) {"
    , "  if (n == 0) { return; }"
    , "  jitml_mlp_check(cudaMemcpy(host, dev, n * sizeof(float), cudaMemcpyDeviceToHost), \"cudaMemcpy d2h\");"
    , "}"
    , ""
    , "static void jitml_mlp_free(float *ptr) { if (ptr != nullptr) { cudaFree(ptr); } }"
    , ""
    , "static std::uint64_t jitml_mlp_hash_floats(const float *host, std::size_t n) {"
    , "  const unsigned char *bytes = reinterpret_cast<const unsigned char *>(host);"
    , "  std::uint64_t hash = 1469598103934665603ull;"
    , "  for (std::size_t i = 0; i < n * sizeof(float); ++i) {"
    , "    hash ^= static_cast<std::uint64_t>(bytes[i]);"
    , "    hash *= 1099511628211ull;"
    , "  }"
    , "  return hash;"
    , "}"
    , ""
    , "static float *jitml_mlp_weight_to_device(int slot, const float *host, std::size_t n, const char *op) {"
    , "  if (n == 0) { return nullptr; }"
    , "  std::uint64_t hash = jitml_mlp_hash_floats(host, n);"
    , "  jitml_mlp_cached_buffer *entry = &jitml_mlp_weight_cache[slot];"
    , "  if (entry->valid && entry->n == n && entry->hash == hash && entry->dev != nullptr) {"
    , "    return entry->dev;"
    , "  }"
    , "  if (entry->dev != nullptr) {"
    , "    jitml_mlp_check(cudaFree(entry->dev), \"cudaFree stale cached weight\");"
    , "    entry->dev = nullptr;"
    , "  }"
    , "  cudaError_t status = cudaMalloc(reinterpret_cast<void **>(&entry->dev), n * sizeof(float));"
    , "  if (status != cudaSuccess) {"
    , "    jitml_mlp_clear_weight_cache();"
    , "    status = cudaMalloc(reinterpret_cast<void **>(&entry->dev), n * sizeof(float));"
    , "  }"
    , "  jitml_mlp_check(status, op);"
    , "  jitml_mlp_check(cudaMemcpy(entry->dev, host, n * sizeof(float), cudaMemcpyHostToDevice), \"cudaMemcpy cached weight h2d\");"
    , "  entry->hash = hash;"
    , "  entry->n = n;"
    , "  entry->valid = true;"
    , "  return entry->dev;"
    , "}"
    ]

-- | The device function name both lanes' activation resolves to on this lane.
--
-- Sprint `265.1` — exported so the cross-lane bit-identity case can assert the
-- rendered kernels call it rather than CUDA's @tanhf@.
mlpCudaActivation :: Text
mlpCudaActivation = "jitml_mlp_tanhf"

-- | One activation, evaluated one way on both Linux lanes.
--
-- Sprint `265.1` — @src/JitML/Codegen/MlpOneDnn.hs@ emits @std::tanh@, which on
-- a @float@ argument is glibc's @sysdeps/ieee754/flt-32@ @tanhf@; this lane
-- emitted CUDA's libdevice @tanhf@. Two implementations of one function agree to
-- about a float ulp and therefore disagree, and because @MlpOneDnn@ declares its
-- reduction order "matches the CUDA batch-grad reduction order" and
-- @JitML.Engines.Engine@ passes @--fmad=false@ precisely so the lanes round
-- alike, that disagreement was the one remaining source of cross-lane drift in
-- the batched parameter gradient — measured at 9.54e-7 absolute while each lane
-- sat 4.19e-7 from a float64 oracle.
--
-- The alignment is one-sided by construction: Sprint `263.1` pins the
-- @linux-cpu@ artifact's SHA-256 in 45 of the 55 committed lane-fragment rows,
-- so that lane's rendered text stays byte-identical and this lane moves. What
-- moves it is glibc's own algorithm rather than an approximation of its output,
-- because glibc's @tanhf@ is __not__ correctly rounded: against a
-- correctly-rounded reference it differs on 118,674,314 of 4,278,190,080 floats,
-- 44.4% of them in @[0.1, 1]@. Computing a more accurate tanh would not have
-- matched it; reproducing its operation sequence does.
--
-- That reproduction is exact because nvcc is invoked with no fast-math argument,
-- @--fmad=false@, and default correctly-rounded division, so each float
-- operation below rounds exactly as the host's does. Verified exhaustively over
-- every finite float, twice: in pure C under @-ffp-contract=off@, and on the
-- device under this lane's own compile arguments — 0 mismatches out of
-- 4,278,190,080, against 129,743,420 (3.03%, worst 1.79e-7 absolute) for CUDA's
-- native @tanhf@.
activationHelpers :: Text
activationHelpers =
  Text.unlines
    [ "// Sprint 265.1 — glibc's flt-32 expm1f/tanhf algorithm, rendered so this"
    , "// lane evaluates the same activation the linux-cpu artifact's std::tanh"
    , "// does, bit for bit. nvcc is given no fast-math argument, --fmad=false,"
    , "// and default correctly-rounded division, so each operation below rounds"
    , "// as the host's does and an identical sequence yields an identical float."
    , "__device__ __forceinline__ float jitml_mlp_expm1f(float x) {"
    , "  const float one = 1.0f;"
    , "  const float huge_v = 1.0e+30f;"
    , "  const float tiny_v = 1.0e-30f;"
    , "  const float o_threshold = 8.8721679688e+01f;"
    , "  const float ln2_hi = 6.9313812256e-01f;"
    , "  const float ln2_lo = 9.0580006145e-06f;"
    , "  const float invln2 = 1.4426950216e+00f;"
    , "  const float Q1 = -3.3333335072e-02f;"
    , "  const float Q2 = 1.5873016091e-03f;"
    , "  const float Q3 = -7.9365076090e-05f;"
    , "  const float Q4 = 4.0082177293e-06f;"
    , "  const float Q5 = -2.0109921195e-07f;"
    , "  float y, hi, lo, c, t, e, hxs, hfx, r1, twopk;"
    , "  int k = 0;"
    , "  int xsb;"
    , "  unsigned int hx = static_cast<unsigned int>(__float_as_int(x));"
    , "  xsb = static_cast<int>(hx & 0x80000000u);"
    , "  hx &= 0x7fffffffu;"
    , "  c = 0.0f;"
    , "  hi = 0.0f;"
    , "  lo = 0.0f;"
    , "  if (hx >= 0x4195b844u) {"
    , "    if (hx >= 0x42b17218u) {"
    , "      if (hx > 0x7f800000u) { return x + x; }"
    , "      if (hx == 0x7f800000u) { return (xsb == 0) ? x : -1.0f; }"
    , "      if (x > o_threshold) { return huge_v * huge_v; }"
    , "    }"
    , "    if (xsb != 0) {"
    , "      if (x + tiny_v < 0.0f) { return tiny_v - one; }"
    , "    }"
    , "  }"
    , "  if (hx > 0x3eb17218u) {"
    , "    if (hx < 0x3F851592u) {"
    , "      if (xsb == 0) { hi = x - ln2_hi; lo = ln2_lo; k = 1; }"
    , "      else { hi = x + ln2_hi; lo = -ln2_lo; k = -1; }"
    , "    } else {"
    , "      k = static_cast<int>(invln2 * x + ((xsb == 0) ? 0.5f : -0.5f));"
    , "      t = static_cast<float>(k);"
    , "      hi = x - t * ln2_hi;"
    , "      lo = t * ln2_lo;"
    , "    }"
    , "    x = hi - lo;"
    , "    c = (hi - x) - lo;"
    , "  } else if (hx < 0x33000000u) {"
    , "    t = huge_v + x;"
    , "    return x - (t - (huge_v + x));"
    , "  } else {"
    , "    k = 0;"
    , "  }"
    , "  hfx = 0.5f * x;"
    , "  hxs = x * hfx;"
    , "  r1 = one + hxs * (Q1 + hxs * (Q2 + hxs * (Q3 + hxs * (Q4 + hxs * Q5))));"
    , "  t = 3.0f - r1 * hfx;"
    , "  e = hxs * ((r1 - t) / (6.0f - x * t));"
    , "  if (k == 0) { return x - (x * e - hxs); }"
    , "  twopk = __int_as_float((0x7f + k) << 23);"
    , "  e = (x * (e - c) - c);"
    , "  e -= hxs;"
    , "  if (k == -1) { return 0.5f * (x - e) - 0.5f; }"
    , "  if (k == 1) {"
    , "    if (x < -0.25f) { return -2.0f * (e - (x + 0.5f)); }"
    , "    else { return one + 2.0f * (x - e); }"
    , "  }"
    , "  if (k <= -2 || k > 56) {"
    , "    y = one - (e - x);"
    , "    if (k == 128) { y = y * 2.0f * 0x1p127f; }"
    , "    else { y = y * twopk; }"
    , "    return y - one;"
    , "  }"
    , "  if (k < 23) {"
    , "    t = __int_as_float(static_cast<int>(0x3f800000u - (0x1000000u >> k)));"
    , "    y = t - (e - x);"
    , "    y = y * twopk;"
    , "  } else {"
    , "    t = __int_as_float(static_cast<int>((0x7f - k) << 23));"
    , "    y = x - (e + t);"
    , "    y += one;"
    , "    y = y * twopk;"
    , "  }"
    , "  return y;"
    , "}"
    , ""
    , "__device__ __forceinline__ float " <> mlpCudaActivation <> "(float x) {"
    , "  const float one = 1.0f;"
    , "  const float tiny_v = 1.0e-30f;"
    , "  float t, z;"
    , "  int jx = __float_as_int(x);"
    , "  int ix = jx & 0x7fffffff;"
    , "  if (ix >= 0x7f800000) {"
    , "    if (jx >= 0) { return one / x + one; }"
    , "    else { return one / x - one; }"
    , "  }"
    , "  if (ix < 0x41b00000) {"
    , "    if (ix < 0x24000000) { return x * (one + x); }"
    , "    if (ix >= 0x3f800000) {"
    , "      t = jitml_mlp_expm1f(2.0f * fabsf(x));"
    , "      z = one - 2.0f / (t + 2.0f);"
    , "    } else {"
    , "      t = jitml_mlp_expm1f(-2.0f * fabsf(x));"
    , "      z = -t / (t + 2.0f);"
    , "    }"
    , "  } else {"
    , "    z = one - tiny_v;"
    , "  }"
    , "  return (jx >= 0) ? z : -z;"
    , "}"
    ]

forwardKernels :: Text
forwardKernels =
  Text.unlines
    [ "// hidden_pre[i] = b1[i] + sum_j W1[i*inputs + j] * input[j]"
    , "// hidden_act[i] = tanh(hidden_pre[i])   (one thread per hidden unit)"
    , "static __global__ void jitml_mlp_hidden_kernel("
    , "    float *hidden_pre, float *hidden_act,"
    , "    const float *input, const float *w1, const float *b1,"
    , "    int inputs, int hidden) {"
    , "  int i = blockIdx.x * blockDim.x + threadIdx.x;"
    , "  if (i >= hidden) { return; }"
    , "  float acc = b1[i];"
    , "  for (int j = 0; j < inputs; ++j) {"
    , "    acc += w1[i * inputs + j] * input[j];"
    , "  }"
    , "  hidden_pre[i] = acc;"
    , "  hidden_act[i] = " <> mlpCudaActivation <> "(acc);"
    , "}"
    , ""
    , "// output[k] = b2[k] + sum_i W2[k*hidden + i] * hidden_act[i]"
    , "static __global__ void jitml_mlp_output_kernel("
    , "    float *output, const float *hidden_act,"
    , "    const float *w2, const float *b2,"
    , "    int hidden, int outputs) {"
    , "  int k = blockIdx.x * blockDim.x + threadIdx.x;"
    , "  if (k >= outputs) { return; }"
    , "  float acc = b2[k];"
    , "  for (int i = 0; i < hidden; ++i) {"
    , "    acc += w2[k * hidden + i] * hidden_act[i];"
    , "  }"
    , "  output[k] = acc;"
    , "}"
    ]

backwardKernels :: Text
backwardKernels =
  Text.unlines
    [ "// gB2[k] = dL/dy[k];  gW2[k*hidden + i] = dL/dy[k] * hidden_act[i]"
    , "static __global__ void jitml_mlp_grad_output_kernel("
    , "    float *g_w2, float *g_b2,"
    , "    const float *d_l_dy, const float *hidden_act,"
    , "    int hidden, int outputs) {"
    , "  int k = blockIdx.x * blockDim.x + threadIdx.x;"
    , "  if (k >= outputs) { return; }"
    , "  float dy = d_l_dy[k];"
    , "  g_b2[k] = dy;"
    , "  for (int i = 0; i < hidden; ++i) {"
    , "    g_w2[k * hidden + i] = dy * hidden_act[i];"
    , "  }"
    , "}"
    , ""
    , "// d_act[i] = sum_k W2[k*hidden + i] * dL/dy[k]"
    , "// d_pre[i] = d_act[i] * (1 - hidden_act[i]^2)"
    , "// gB1[i] = d_pre[i];  gW1[i*inputs + j] = d_pre[i] * input[j]"
    , "static __global__ void jitml_mlp_grad_hidden_kernel("
    , "    float *g_w1, float *g_b1,"
    , "    const float *d_l_dy, const float *input,"
    , "    const float *hidden_act, const float *w2,"
    , "    int inputs, int hidden, int outputs) {"
    , "  int i = blockIdx.x * blockDim.x + threadIdx.x;"
    , "  if (i >= hidden) { return; }"
    , "  float d_act = 0.0f;"
    , "  for (int k = 0; k < outputs; ++k) {"
    , "    d_act += w2[k * hidden + i] * d_l_dy[k];"
    , "  }"
    , "  float h = hidden_act[i];"
    , "  float d_pre = d_act * (1.0f - h * h);"
    , "  g_b1[i] = d_pre;"
    , "  for (int j = 0; j < inputs; ++j) {"
    , "    g_w1[i * inputs + j] = d_pre * input[j];"
    , "  }"
    , "}"
    ]

forwardWrapper :: Text
forwardWrapper =
  Text.unlines
    [ "// Sprint 229.1 — the artifact declares its own executed identity, so the"
    , "// device-execution witness reads what ran instead of inferring it. The MLP"
    , "// ABI has no per-family kernel; its identity is the shared MLP program tag,"
    , "// which is the same string the Apple metadata's `family` field carries."
    , "static const char *jitml_mlp_family = \"mlp-forward-backward-tanh-linear\";"
    , ""
    , "extern \"C\" const char *jitml_kernel_family_name(void) { return jitml_mlp_family; }"
    , ""
    , "extern \"C\" void jitml_mlp_forward("
    , "    float *hidden_pre, float *hidden_act, float *output,"
    , "    const float *input, const float *w1, const float *b1,"
    , "    const float *w2, const float *b2,"
    , "    int inputs, int hidden, int outputs) {"
    , "  if (hidden <= 0 || outputs <= 0) { return; }"
    , "  std::size_t w1n = static_cast<std::size_t>(hidden) * static_cast<std::size_t>(inputs);"
    , "  std::size_t w2n = static_cast<std::size_t>(outputs) * static_cast<std::size_t>(hidden);"
    , "  float *d_input = jitml_mlp_to_device(input, static_cast<std::size_t>(inputs));"
    , "  float *d_w1 = jitml_mlp_weight_to_device(0, w1, w1n, \"cudaMalloc cached w1\");"
    , "  float *d_b1 = jitml_mlp_weight_to_device(1, b1, static_cast<std::size_t>(hidden), \"cudaMalloc cached b1\");"
    , "  float *d_w2 = jitml_mlp_weight_to_device(2, w2, w2n, \"cudaMalloc cached w2\");"
    , "  float *d_b2 = jitml_mlp_weight_to_device(3, b2, static_cast<std::size_t>(outputs), \"cudaMalloc cached b2\");"
    , "  float *d_hidden_pre = jitml_mlp_device_alloc(static_cast<std::size_t>(hidden));"
    , "  float *d_hidden_act = jitml_mlp_device_alloc(static_cast<std::size_t>(hidden));"
    , "  float *d_output = jitml_mlp_device_alloc(static_cast<std::size_t>(outputs));"
    , "  dim3 block(256);"
    , "  dim3 grid_hidden(static_cast<unsigned int>((hidden + 255) / 256));"
    , "  jitml_mlp_hidden_kernel<<<grid_hidden, block>>>("
    , "      d_hidden_pre, d_hidden_act, d_input, d_w1, d_b1, inputs, hidden);"
    , "  jitml_mlp_check(cudaGetLastError(), \"hidden launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"hidden sync\");"
    , "  dim3 grid_output(static_cast<unsigned int>((outputs + 255) / 256));"
    , "  jitml_mlp_output_kernel<<<grid_output, block>>>("
    , "      d_output, d_hidden_act, d_w2, d_b2, hidden, outputs);"
    , "  jitml_mlp_check(cudaGetLastError(), \"output launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"output sync\");"
    , "  jitml_mlp_from_device(hidden_pre, d_hidden_pre, static_cast<std::size_t>(hidden));"
    , "  jitml_mlp_from_device(hidden_act, d_hidden_act, static_cast<std::size_t>(hidden));"
    , "  jitml_mlp_from_device(output, d_output, static_cast<std::size_t>(outputs));"
    , "  jitml_mlp_free(d_input);"
    , "  jitml_mlp_free(d_hidden_pre); jitml_mlp_free(d_hidden_act); jitml_mlp_free(d_output);"
    , "}"
    ]

backwardWrapper :: Text
backwardWrapper =
  Text.unlines
    [ "extern \"C\" void jitml_mlp_backward("
    , "    float *g_w1, float *g_b1, float *g_w2, float *g_b2,"
    , "    const float *d_l_dy, const float *input,"
    , "    const float *hidden_act, const float *w2,"
    , "    int inputs, int hidden, int outputs) {"
    , "  if (hidden <= 0 || outputs <= 0) { return; }"
    , "  std::size_t w1n = static_cast<std::size_t>(hidden) * static_cast<std::size_t>(inputs);"
    , "  std::size_t w2n = static_cast<std::size_t>(outputs) * static_cast<std::size_t>(hidden);"
    , "  float *d_dy = jitml_mlp_to_device(d_l_dy, static_cast<std::size_t>(outputs));"
    , "  float *d_input = jitml_mlp_to_device(input, static_cast<std::size_t>(inputs));"
    , "  float *d_hidden_act = jitml_mlp_to_device(hidden_act, static_cast<std::size_t>(hidden));"
    , "  float *d_w2 = jitml_mlp_weight_to_device(2, w2, w2n, \"cudaMalloc cached w2\");"
    , "  float *d_g_w1 = jitml_mlp_device_alloc(w1n);"
    , "  float *d_g_b1 = jitml_mlp_device_alloc(static_cast<std::size_t>(hidden));"
    , "  float *d_g_w2 = jitml_mlp_device_alloc(w2n);"
    , "  float *d_g_b2 = jitml_mlp_device_alloc(static_cast<std::size_t>(outputs));"
    , "  dim3 block(256);"
    , "  dim3 grid_output(static_cast<unsigned int>((outputs + 255) / 256));"
    , "  jitml_mlp_grad_output_kernel<<<grid_output, block>>>("
    , "      d_g_w2, d_g_b2, d_dy, d_hidden_act, hidden, outputs);"
    , "  jitml_mlp_check(cudaGetLastError(), \"grad output launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"grad output sync\");"
    , "  dim3 grid_hidden(static_cast<unsigned int>((hidden + 255) / 256));"
    , "  jitml_mlp_grad_hidden_kernel<<<grid_hidden, block>>>("
    , "      d_g_w1, d_g_b1, d_dy, d_input, d_hidden_act, d_w2, inputs, hidden, outputs);"
    , "  jitml_mlp_check(cudaGetLastError(), \"grad hidden launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"grad hidden sync\");"
    , "  jitml_mlp_from_device(g_w1, d_g_w1, w1n);"
    , "  jitml_mlp_from_device(g_b1, d_g_b1, static_cast<std::size_t>(hidden));"
    , "  jitml_mlp_from_device(g_w2, d_g_w2, w2n);"
    , "  jitml_mlp_from_device(g_b2, d_g_b2, static_cast<std::size_t>(outputs));"
    , "  jitml_mlp_free(d_dy); jitml_mlp_free(d_input); jitml_mlp_free(d_hidden_act);"
    , "  jitml_mlp_free(d_g_w1); jitml_mlp_free(d_g_b1); jitml_mlp_free(d_g_w2); jitml_mlp_free(d_g_b2);"
    , "}"
    ]

-- | Sprint 13.8 — batched forward + summed-gradient backward device
-- kernels. The fused @jitml_mlp_batch_gradient@ wrapper (below) computes
-- one minibatch's gradient — summed over the @batch@ rows — in a single
-- device round-trip, amortising host↔device copies over the whole batch
-- (the trainer hot-path adoption these kernels enable). Layouts are
-- row-major: @input@ is @batch × inputs@, @d_l_dy@ is @batch × outputs@,
-- @hidden_act@ is @batch × hidden@. Each gradient element is reduced by a
-- single thread with sequential sums over the batch (no atomics), so the
-- summed gradient is bit-deterministic run-to-run on the same device.
batchedGradientKernels :: Text
batchedGradientKernels =
  Text.unlines
    [ "// hidden_act[b][i] = tanh(b1[i] + sum_j W1[i][j] * input[b][j])"
    , "static __global__ void jitml_mlp_batch_hidden_kernel("
    , "    float *hidden_act, const float *input, const float *w1, const float *b1,"
    , "    int inputs, int hidden, int batch) {"
    , "  std::size_t idx = static_cast<std::size_t>(blockIdx.x) * blockDim.x + threadIdx.x;"
    , "  std::size_t total = static_cast<std::size_t>(batch) * static_cast<std::size_t>(hidden);"
    , "  if (idx >= total) { return; }"
    , "  int b = static_cast<int>(idx / hidden);"
    , "  int i = static_cast<int>(idx % hidden);"
    , "  float acc = b1[i];"
    , "  for (int j = 0; j < inputs; ++j) {"
    , "    acc += w1[i * inputs + j] * input[b * inputs + j];"
    , "  }"
    , "  hidden_act[b * hidden + i] = " <> mlpCudaActivation <> "(acc);"
    , "}"
    , ""
    , "// gB2[k] = sum_b dy[b][k]"
    , "static __global__ void jitml_mlp_batch_grad_b2_kernel("
    , "    float *g_b2, const float *d_l_dy, int outputs, int batch) {"
    , "  int k = blockIdx.x * blockDim.x + threadIdx.x;"
    , "  if (k >= outputs) { return; }"
    , "  float gb = 0.0f;"
    , "  for (int b = 0; b < batch; ++b) { gb += d_l_dy[b * outputs + k]; }"
    , "  g_b2[k] = gb;"
    , "}"
    , ""
    , "// gW2[k][i] = sum_b dy[b][k] * hidden_act[b][i]"
    , "static __global__ void jitml_mlp_batch_grad_w2_kernel("
    , "    float *g_w2, const float *d_l_dy, const float *hidden_act,"
    , "    int hidden, int outputs, int batch) {"
    , "  std::size_t idx = static_cast<std::size_t>(blockIdx.x) * blockDim.x + threadIdx.x;"
    , "  std::size_t total = static_cast<std::size_t>(outputs) * static_cast<std::size_t>(hidden);"
    , "  if (idx >= total) { return; }"
    , "  int k = static_cast<int>(idx / hidden);"
    , "  int i = static_cast<int>(idx % hidden);"
    , "  float gw = 0.0f;"
    , "  for (int b = 0; b < batch; ++b) {"
    , "    gw += d_l_dy[b * outputs + k] * hidden_act[b * hidden + i];"
    , "  }"
    , "  g_w2[k * hidden + i] = gw;"
    , "}"
    , ""
    , "// gB1[i] = sum_b d_pre[b][i]"
    , "static __global__ void jitml_mlp_batch_grad_b1_kernel("
    , "    float *g_b1, const float *d_l_dy, const float *hidden_act,"
    , "    const float *w2, int hidden, int outputs, int batch) {"
    , "  int i = blockIdx.x * blockDim.x + threadIdx.x;"
    , "  if (i >= hidden) { return; }"
    , "  float gb1 = 0.0f;"
    , "  for (int b = 0; b < batch; ++b) {"
    , "    float d_act = 0.0f;"
    , "    for (int k = 0; k < outputs; ++k) {"
    , "      d_act += w2[k * hidden + i] * d_l_dy[b * outputs + k];"
    , "    }"
    , "    float h = hidden_act[b * hidden + i];"
    , "    gb1 += d_act * (1.0f - h * h);"
    , "  }"
    , "  g_b1[i] = gb1;"
    , "}"
    , ""
    , "// gW1[i][j] = sum_b d_pre[b][i] * input[b][j]"
    , "static __global__ void jitml_mlp_batch_grad_w1_kernel("
    , "    float *g_w1, const float *d_l_dy, const float *input,"
    , "    const float *hidden_act, const float *w2,"
    , "    int inputs, int hidden, int outputs, int batch) {"
    , "  std::size_t idx = static_cast<std::size_t>(blockIdx.x) * blockDim.x + threadIdx.x;"
    , "  std::size_t total = static_cast<std::size_t>(hidden) * static_cast<std::size_t>(inputs);"
    , "  if (idx >= total) { return; }"
    , "  int i = static_cast<int>(idx / inputs);"
    , "  int j = static_cast<int>(idx % inputs);"
    , "  float gw = 0.0f;"
    , "  for (int b = 0; b < batch; ++b) {"
    , "    float d_act = 0.0f;"
    , "    for (int k = 0; k < outputs; ++k) {"
    , "      d_act += w2[k * hidden + i] * d_l_dy[b * outputs + k];"
    , "    }"
    , "    float h = hidden_act[b * hidden + i];"
    , "    float d_pre = d_act * (1.0f - h * h);"
    , "    gw += d_pre * input[b * inputs + j];"
    , "  }"
    , "  g_w1[i * inputs + j] = gw;"
    , "}"
    ]

-- | Batched output kernel: @output[b][k] = b2[k] + sum_i W2[k][i] *
-- hidden_act[b][i]@ (one thread per @(b, k)@). Pairs with
-- 'batchedGradientKernels'' batched hidden kernel to form the batched
-- forward pass.
batchedOutputKernel :: Text
batchedOutputKernel =
  Text.unlines
    [ "static __global__ void jitml_mlp_batch_output_kernel("
    , "    float *output, const float *hidden_act, const float *w2, const float *b2,"
    , "    int hidden, int outputs, int batch) {"
    , "  std::size_t idx = static_cast<std::size_t>(blockIdx.x) * blockDim.x + threadIdx.x;"
    , "  std::size_t total = static_cast<std::size_t>(batch) * static_cast<std::size_t>(outputs);"
    , "  if (idx >= total) { return; }"
    , "  int b = static_cast<int>(idx / outputs);"
    , "  int k = static_cast<int>(idx % outputs);"
    , "  float acc = b2[k];"
    , "  for (int i = 0; i < hidden; ++i) {"
    , "    acc += w2[k * hidden + i] * hidden_act[b * hidden + i];"
    , "  }"
    , "  output[b * outputs + k] = acc;"
    , "}"
    ]

-- | Batched forward wrapper: runs the network forward over the whole
-- minibatch in one device round-trip and returns the per-sample outputs
-- (@batch × outputs@ row-major). Used by a CUDA trainer to obtain the
-- minibatch's policy/value outputs (for the loss gradient) before the
-- matching 'batchedGradientWrapper' backward call.
batchedForwardWrapper :: Text
batchedForwardWrapper =
  Text.unlines
    [ "extern \"C\" void jitml_mlp_forward_batch("
    , "    float *output, const float *input,"
    , "    const float *w1, const float *b1, const float *w2, const float *b2,"
    , "    int inputs, int hidden, int outputs, int batch) {"
    , "  if (hidden <= 0 || outputs <= 0 || batch <= 0) { return; }"
    , "  std::size_t in_n = static_cast<std::size_t>(batch) * static_cast<std::size_t>(inputs);"
    , "  std::size_t out_n = static_cast<std::size_t>(batch) * static_cast<std::size_t>(outputs);"
    , "  std::size_t hact_n = static_cast<std::size_t>(batch) * static_cast<std::size_t>(hidden);"
    , "  std::size_t w1n = static_cast<std::size_t>(hidden) * static_cast<std::size_t>(inputs);"
    , "  std::size_t w2n = static_cast<std::size_t>(outputs) * static_cast<std::size_t>(hidden);"
    , "  float *d_input = jitml_mlp_to_device(input, in_n);"
    , "  float *d_w1 = jitml_mlp_weight_to_device(0, w1, w1n, \"cudaMalloc cached w1\");"
    , "  float *d_b1 = jitml_mlp_weight_to_device(1, b1, static_cast<std::size_t>(hidden), \"cudaMalloc cached b1\");"
    , "  float *d_w2 = jitml_mlp_weight_to_device(2, w2, w2n, \"cudaMalloc cached w2\");"
    , "  float *d_b2 = jitml_mlp_weight_to_device(3, b2, static_cast<std::size_t>(outputs), \"cudaMalloc cached b2\");"
    , "  float *d_hidden_act = jitml_mlp_device_alloc(hact_n);"
    , "  float *d_output = jitml_mlp_device_alloc(out_n);"
    , "  dim3 block(256);"
    , "  dim3 grid_hidden(static_cast<unsigned int>((hact_n + 255) / 256));"
    , "  jitml_mlp_batch_hidden_kernel<<<grid_hidden, block>>>("
    , "      d_hidden_act, d_input, d_w1, d_b1, inputs, hidden, batch);"
    , "  jitml_mlp_check(cudaGetLastError(), \"batch forward hidden launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"batch forward hidden sync\");"
    , "  dim3 grid_output(static_cast<unsigned int>((out_n + 255) / 256));"
    , "  jitml_mlp_batch_output_kernel<<<grid_output, block>>>("
    , "      d_output, d_hidden_act, d_w2, d_b2, hidden, outputs, batch);"
    , "  jitml_mlp_check(cudaGetLastError(), \"batch forward output launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"batch forward output sync\");"
    , "  jitml_mlp_from_device(output, d_output, out_n);"
    , "  jitml_mlp_free(d_input);"
    , "  jitml_mlp_free(d_hidden_act); jitml_mlp_free(d_output);"
    , "}"
    ]

batchedGradientWrapper :: Text
batchedGradientWrapper =
  Text.unlines
    [ "extern \"C\" void jitml_mlp_batch_gradient("
    , "    float *g_w1, float *g_b1, float *g_w2, float *g_b2,"
    , "    const float *input, const float *d_l_dy,"
    , "    const float *w1, const float *b1, const float *w2,"
    , "    int inputs, int hidden, int outputs, int batch) {"
    , "  if (hidden <= 0 || outputs <= 0 || batch <= 0) { return; }"
    , "  std::size_t in_n = static_cast<std::size_t>(batch) * static_cast<std::size_t>(inputs);"
    , "  std::size_t dy_n = static_cast<std::size_t>(batch) * static_cast<std::size_t>(outputs);"
    , "  std::size_t hact_n = static_cast<std::size_t>(batch) * static_cast<std::size_t>(hidden);"
    , "  std::size_t w1n = static_cast<std::size_t>(hidden) * static_cast<std::size_t>(inputs);"
    , "  std::size_t w2n = static_cast<std::size_t>(outputs) * static_cast<std::size_t>(hidden);"
    , "  float *d_input = jitml_mlp_to_device(input, in_n);"
    , "  float *d_dy = jitml_mlp_to_device(d_l_dy, dy_n);"
    , "  float *d_w1 = jitml_mlp_weight_to_device(0, w1, w1n, \"cudaMalloc cached w1\");"
    , "  float *d_b1 = jitml_mlp_weight_to_device(1, b1, static_cast<std::size_t>(hidden), \"cudaMalloc cached b1\");"
    , "  float *d_w2 = jitml_mlp_weight_to_device(2, w2, w2n, \"cudaMalloc cached w2\");"
    , "  float *d_hidden_act = jitml_mlp_device_alloc(hact_n);"
    , "  float *d_g_w1 = jitml_mlp_device_alloc(w1n);"
    , "  float *d_g_b1 = jitml_mlp_device_alloc(static_cast<std::size_t>(hidden));"
    , "  float *d_g_w2 = jitml_mlp_device_alloc(w2n);"
    , "  float *d_g_b2 = jitml_mlp_device_alloc(static_cast<std::size_t>(outputs));"
    , "  dim3 block(256);"
    , "  dim3 grid_hidden_fwd(static_cast<unsigned int>((hact_n + 255) / 256));"
    , "  jitml_mlp_batch_hidden_kernel<<<grid_hidden_fwd, block>>>("
    , "      d_hidden_act, d_input, d_w1, d_b1, inputs, hidden, batch);"
    , "  jitml_mlp_check(cudaGetLastError(), \"batch hidden launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"batch hidden sync\");"
    , "  dim3 grid_output(static_cast<unsigned int>((outputs + 255) / 256));"
    , "  jitml_mlp_batch_grad_b2_kernel<<<grid_output, block>>>("
    , "      d_g_b2, d_dy, outputs, batch);"
    , "  jitml_mlp_check(cudaGetLastError(), \"batch grad b2 launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"batch grad b2 sync\");"
    , "  dim3 grid_w2(static_cast<unsigned int>((w2n + 255) / 256));"
    , "  jitml_mlp_batch_grad_w2_kernel<<<grid_w2, block>>>("
    , "      d_g_w2, d_dy, d_hidden_act, hidden, outputs, batch);"
    , "  jitml_mlp_check(cudaGetLastError(), \"batch grad w2 launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"batch grad w2 sync\");"
    , "  dim3 grid_hidden(static_cast<unsigned int>((hidden + 255) / 256));"
    , "  jitml_mlp_batch_grad_b1_kernel<<<grid_hidden, block>>>("
    , "      d_g_b1, d_dy, d_hidden_act, d_w2, hidden, outputs, batch);"
    , "  jitml_mlp_check(cudaGetLastError(), \"batch grad b1 launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"batch grad b1 sync\");"
    , "  dim3 grid_w1(static_cast<unsigned int>((w1n + 255) / 256));"
    , "  jitml_mlp_batch_grad_w1_kernel<<<grid_w1, block>>>("
    , "      d_g_w1, d_dy, d_input, d_hidden_act, d_w2, inputs, hidden, outputs, batch);"
    , "  jitml_mlp_check(cudaGetLastError(), \"batch grad w1 launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"batch grad w1 sync\");"
    , "  jitml_mlp_from_device(g_w1, d_g_w1, w1n);"
    , "  jitml_mlp_from_device(g_b1, d_g_b1, static_cast<std::size_t>(hidden));"
    , "  jitml_mlp_from_device(g_w2, d_g_w2, w2n);"
    , "  jitml_mlp_from_device(g_b2, d_g_b2, static_cast<std::size_t>(outputs));"
    , "  jitml_mlp_free(d_input); jitml_mlp_free(d_dy); jitml_mlp_free(d_hidden_act);"
    , "  jitml_mlp_free(d_g_w1); jitml_mlp_free(d_g_b1); jitml_mlp_free(d_g_w2); jitml_mlp_free(d_g_b2);"
    , "}"
    ]

-- | Sprint 13.8 — batched device /input/-gradient kernels. The
-- @jitml_mlp_input_gradient_batch@ wrapper (below) computes @dL/dx@ for
-- every sample in a minibatch in one device round-trip:
-- @dL/dx = W1^T @ ((W2^T @ dL/dy) * (1 - tanh(hidden_pre)^2))@. Unlike the
-- parameter gradient (summed over the batch), the input gradient is
-- per-sample (each sample has its own @dL/dx@), so the output is
-- @batch × inputs@. This is the missing primitive for the continuous
-- actor-critic deterministic-policy gradient (@dQ/da@ = the action-slice
-- of the critic's input gradient). Per-thread sequential reductions →
-- bit-deterministic run-to-run on the same device.
batchedInputGradientKernels :: Text
batchedInputGradientKernels =
  Text.unlines
    [ "// d_pre[b][i] = (sum_k W2[k][i] * dL/dy[b][k]) * (1 - hidden_act[b][i]^2)"
    , "static __global__ void jitml_mlp_dhidden_pre_batch_kernel("
    , "    float *d_hidden_pre, const float *d_l_dy, const float *hidden_act,"
    , "    const float *w2, int hidden, int outputs, int batch) {"
    , "  std::size_t idx = static_cast<std::size_t>(blockIdx.x) * blockDim.x + threadIdx.x;"
    , "  std::size_t total = static_cast<std::size_t>(batch) * static_cast<std::size_t>(hidden);"
    , "  if (idx >= total) { return; }"
    , "  int b = static_cast<int>(idx / hidden);"
    , "  int i = static_cast<int>(idx % hidden);"
    , "  float d_act = 0.0f;"
    , "  for (int k = 0; k < outputs; ++k) {"
    , "    d_act += w2[k * hidden + i] * d_l_dy[b * outputs + k];"
    , "  }"
    , "  float h = hidden_act[b * hidden + i];"
    , "  d_hidden_pre[b * hidden + i] = d_act * (1.0f - h * h);"
    , "}"
    , ""
    , "// dx[b][j] = sum_i W1[i][j] * d_hidden_pre[b][i]"
    , "static __global__ void jitml_mlp_dx_batch_kernel("
    , "    float *dx, const float *d_hidden_pre, const float *w1,"
    , "    int inputs, int hidden, int batch) {"
    , "  std::size_t idx = static_cast<std::size_t>(blockIdx.x) * blockDim.x + threadIdx.x;"
    , "  std::size_t total = static_cast<std::size_t>(batch) * static_cast<std::size_t>(inputs);"
    , "  if (idx >= total) { return; }"
    , "  int b = static_cast<int>(idx / inputs);"
    , "  int j = static_cast<int>(idx % inputs);"
    , "  float acc = 0.0f;"
    , "  for (int i = 0; i < hidden; ++i) {"
    , "    acc += w1[i * inputs + j] * d_hidden_pre[b * hidden + i];"
    , "  }"
    , "  dx[b * inputs + j] = acc;"
    , "}"
    ]

batchedInputGradientWrapper :: Text
batchedInputGradientWrapper =
  Text.unlines
    [ "extern \"C\" void jitml_mlp_input_gradient_batch("
    , "    float *dx, const float *input, const float *d_l_dy,"
    , "    const float *w1, const float *b1, const float *w2,"
    , "    int inputs, int hidden, int outputs, int batch) {"
    , "  if (hidden <= 0 || outputs <= 0 || inputs <= 0 || batch <= 0) { return; }"
    , "  std::size_t in_n = static_cast<std::size_t>(batch) * static_cast<std::size_t>(inputs);"
    , "  std::size_t dy_n = static_cast<std::size_t>(batch) * static_cast<std::size_t>(outputs);"
    , "  std::size_t hact_n = static_cast<std::size_t>(batch) * static_cast<std::size_t>(hidden);"
    , "  std::size_t w1n = static_cast<std::size_t>(hidden) * static_cast<std::size_t>(inputs);"
    , "  std::size_t w2n = static_cast<std::size_t>(outputs) * static_cast<std::size_t>(hidden);"
    , "  float *d_input = jitml_mlp_to_device(input, in_n);"
    , "  float *d_dy = jitml_mlp_to_device(d_l_dy, dy_n);"
    , "  float *d_w1 = jitml_mlp_weight_to_device(0, w1, w1n, \"cudaMalloc cached w1\");"
    , "  float *d_b1 = jitml_mlp_weight_to_device(1, b1, static_cast<std::size_t>(hidden), \"cudaMalloc cached b1\");"
    , "  float *d_w2 = jitml_mlp_weight_to_device(2, w2, w2n, \"cudaMalloc cached w2\");"
    , "  float *d_hidden_act = jitml_mlp_device_alloc(hact_n);"
    , "  float *d_hidden_pre = jitml_mlp_device_alloc(hact_n);"
    , "  float *d_dx = jitml_mlp_device_alloc(in_n);"
    , "  dim3 block(256);"
    , "  dim3 grid_hidden(static_cast<unsigned int>((hact_n + 255) / 256));"
    , "  jitml_mlp_batch_hidden_kernel<<<grid_hidden, block>>>("
    , "      d_hidden_act, d_input, d_w1, d_b1, inputs, hidden, batch);"
    , "  jitml_mlp_check(cudaGetLastError(), \"input-grad hidden launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"input-grad hidden sync\");"
    , "  jitml_mlp_dhidden_pre_batch_kernel<<<grid_hidden, block>>>("
    , "      d_hidden_pre, d_dy, d_hidden_act, d_w2, hidden, outputs, batch);"
    , "  jitml_mlp_check(cudaGetLastError(), \"input-grad dpre launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"input-grad dpre sync\");"
    , "  dim3 grid_input(static_cast<unsigned int>((in_n + 255) / 256));"
    , "  jitml_mlp_dx_batch_kernel<<<grid_input, block>>>("
    , "      d_dx, d_hidden_pre, d_w1, inputs, hidden, batch);"
    , "  jitml_mlp_check(cudaGetLastError(), \"input-grad dx launch\");"
    , "  jitml_mlp_check(cudaDeviceSynchronize(), \"input-grad dx sync\");"
    , "  jitml_mlp_from_device(dx, d_dx, in_n);"
    , "  jitml_mlp_free(d_input); jitml_mlp_free(d_dy);"
    , "  jitml_mlp_free(d_hidden_act); jitml_mlp_free(d_hidden_pre); jitml_mlp_free(d_dx);"
    , "}"
    ]
