{-# LANGUAGE OverloadedStrings #-}

-- | Sprint (backend-parity) — the Apple-Silicon (Metal lane) MLP
-- forward/backward kernel source, mirroring "JitML.Codegen.MlpCuda" as embedded
-- Metal Shading Language JIT-compiled at runtime via
-- @MTLDevice.makeLibrary(source:options:)@ (fast-math off), built through the
-- CommandLineTools @swift build@ — no offline @metal@ compiler, no Xcode, no VM
-- (see CLAUDE.md → Apple Silicon headless JIT). The emitted @\@_cdecl@ ABI is
-- identical to the CUDA / oneDNN backends (the @jitml_mlp_*@ symbols), so
-- "JitML.Numerics.MlpDevice" marshals to it unchanged.
--
-- ⚠ UNVERIFIED ON THIS HOST. This module emits Swift + MSL as text; it compiles
-- as Haskell, but the generated Metal program can only be compiled and executed
-- on an apple-silicon Mac. It is a faithful port of the verified CUDA kernels
-- ("JitML.Codegen.MlpCuda") — the MSL math mirrors the CUDA @__global__@
-- bodies and the launchers mirror the CUDA host wrappers — but it MUST be
-- validated on the @-p apple-silicon@ lane (which runs host-native on a Mac)
-- before it is trusted. The MSL kernels use per-thread sequential reductions
-- (no atomics) and single-stream launch order for the determinism contract.
module JitML.Codegen.MlpMetal
  ( mlpMetalKernelSpec
  , renderMlpMetalSource
  )
where

import Data.Text (Text)
import Data.Text qualified as Text

import JitML.Cache.Key (KernelSpec (..))
import JitML.Codegen.SourceFile (SourceFile (..))

-- | Kernel-spec identifier for the MLP forward/backward Metal kernel. The cache
-- key disambiguates by substrate + toolchain fingerprint.
mlpMetalKernelSpec :: KernelSpec
mlpMetalKernelSpec = KernelSpec "mlp-forward-backward-tanh-linear"

-- | The generated Swift package (Package.swift + the JitMLMetal Swift source
-- with embedded MSL), matching the @swift build --package-path@ command in
-- "JitML.Engines.Engine".
renderMlpMetalSource :: [SourceFile]
renderMlpMetalSource =
  [ SourceFile "Package.swift" packageSwift
  , SourceFile "Sources/JitMLMetal/JitMLMetal.swift" swiftSource
  ]

packageSwift :: Text
packageSwift =
  Text.unlines
    [ "// swift-tools-version: 5.10"
    , "import PackageDescription"
    , ""
    , "let package = Package("
    , "  name: \"JitMLMetal\","
    , "  platforms: [.macOS(.v14)],"
    , "  products: [.library(name: \"JitMLMetal\", type: .dynamic, targets: [\"JitMLMetal\"])],"
    , "  targets: [.target(name: \"JitMLMetal\")]"
    , ")"
    ]

swiftSource :: Text
swiftSource =
  Text.unlines
    [ "// Generated by jitml. Do not check generated Swift / Metal source into git."
    , "// UNVERIFIED until run on an apple-silicon Mac (-p apple-silicon lane)."
    , "import Darwin"
    , "import Metal"
    , ""
    , "private let jitmlMetalSource = #\"\"\""
    , metalKernels
    , "\"\"\"#"
    , ""
    , "private let jitmlDevice: MTLDevice? = MTLCreateSystemDefaultDevice()"
    , "private let jitmlQueue: MTLCommandQueue? = jitmlDevice?.makeCommandQueue()"
    , ""
    , "private let jitmlLibrary: MTLLibrary? = {"
    , "  guard let device = jitmlDevice else { return nil }"
    , "  let options = MTLCompileOptions()"
    , "  if #available(macOS 15.0, *) { options.mathMode = .safe } else { options.fastMathEnabled = false }"
    , "  return try? device.makeLibrary(source: jitmlMetalSource, options: options)"
    , "}()"
    , ""
    , "private func jitmlPipeline(_ name: String) -> MTLComputePipelineState? {"
    , "  guard let device = jitmlDevice, let library = jitmlLibrary,"
    , "        let function = library.makeFunction(name: name),"
    , "        let state = try? device.makeComputePipelineState(function: function)"
    , "  else { return nil }"
    , "  return state"
    , "}"
    , ""
    , "// A shared MTLBuffer for a flat Float array (storageModeShared so the host"
    , "// pointer copy is a plain memcpy). length is clamped to >= 1 element."
    , "private func jitmlBuffer(_ device: MTLDevice, _ ptr: UnsafePointer<Float>?, _ count: Int) -> MTLBuffer? {"
    , "  let bytes = max(count, 1) * MemoryLayout<Float>.stride"
    , "  if let ptr = ptr { return device.makeBuffer(bytes: ptr, length: bytes, options: .storageModeShared) }"
    , "  return device.makeBuffer(length: bytes, options: .storageModeShared)"
    , "}"
    , ""
    , "// Dispatch `total` threads (one per output element) in 32-aligned"
    , "// threadgroups for `pipeline`, with `buffers` bound at successive indices"
    , "// from 0 and `ints` bound as `constant int&` at indices after the buffers."
    , "// Determinism: single command buffer per call, waitUntilCompleted, MSL"
    , "// kernels bound-check on the element count and reduce sequentially."
    , "private func jitmlDispatch(_ name: String, _ total: Int,"
    , "                           _ buffers: [MTLBuffer], _ ints: [Int]) {"
    , "  guard let queue = jitmlQueue, let pipeline = jitmlPipeline(name),"
    , "        let commandBuffer = queue.makeCommandBuffer(),"
    , "        let encoder = commandBuffer.makeComputeCommandEncoder()"
    , "  else { return }"
    , "  encoder.setComputePipelineState(pipeline)"
    , "  for (i, b) in buffers.enumerated() { encoder.setBuffer(b, offset: 0, index: i) }"
    , "  var locals = ints.map { Int32($0) }"
    , "  for i in 0..<locals.count {"
    , "    encoder.setBytes(&locals[i], length: MemoryLayout<Int32>.stride, index: buffers.count + i)"
    , "  }"
    , "  let simdWidth = 32"
    , "  let maxTg = max(simdWidth, (pipeline.maxTotalThreadsPerThreadgroup / simdWidth) * simdWidth)"
    , "  let desired = ((max(total, 1) + simdWidth - 1) / simdWidth) * simdWidth"
    , "  let tgWidth = max(simdWidth, min(maxTg, desired))"
    , "  let groups = (max(total, 1) + tgWidth - 1) / tgWidth"
    , "  encoder.dispatchThreadgroups(MTLSize(width: groups, height: 1, depth: 1),"
    , "    threadsPerThreadgroup: MTLSize(width: tgWidth, height: 1, depth: 1))"
    , "  encoder.endEncoding()"
    , "  commandBuffer.commit()"
    , "  commandBuffer.waitUntilCompleted()"
    , "}"
    , ""
    , forwardCdecl
    , ""
    , backwardCdecl
    , ""
    , forwardBatchCdecl
    , ""
    , batchGradientCdecl
    , ""
    , inputGradientBatchCdecl
    ]

-- | MSL kernels mirroring the CUDA @__global__@ bodies in
-- "JitML.Codegen.MlpCuda" one-for-one. Buffer index conventions are local to
-- each kernel (bound by 'jitmlDispatch' in argument order, ints after buffers).
metalKernels :: Text
metalKernels =
  Text.unlines
    [ "#include <metal_stdlib>"
    , "using namespace metal;"
    , ""
    , "// hidden_pre[i] = b1[i] + sum_j W1[i*inputs+j]*input[j]; hidden_act = tanh."
    , "kernel void jitml_mlp_hidden("
    , "    device float *hidden_pre [[buffer(0)]], device float *hidden_act [[buffer(1)]],"
    , "    const device float *input [[buffer(2)]], const device float *w1 [[buffer(3)]],"
    , "    const device float *b1 [[buffer(4)]],"
    , "    constant int &inputs [[buffer(5)]], constant int &hidden [[buffer(6)]],"
    , "    uint gid [[thread_position_in_grid]]) {"
    , "  int i = int(gid); if (i >= hidden) { return; }"
    , "  float acc = b1[i];"
    , "  for (int j = 0; j < inputs; ++j) { acc += w1[i * inputs + j] * input[j]; }"
    , "  hidden_pre[i] = acc; hidden_act[i] = tanh(acc);"
    , "}"
    , ""
    , "// output[k] = b2[k] + sum_i W2[k*hidden+i]*hidden_act[i]."
    , "kernel void jitml_mlp_output("
    , "    device float *output [[buffer(0)]], const device float *hidden_act [[buffer(1)]],"
    , "    const device float *w2 [[buffer(2)]], const device float *b2 [[buffer(3)]],"
    , "    constant int &hidden [[buffer(4)]], constant int &outputs [[buffer(5)]],"
    , "    uint gid [[thread_position_in_grid]]) {"
    , "  int k = int(gid); if (k >= outputs) { return; }"
    , "  float acc = b2[k];"
    , "  for (int i = 0; i < hidden; ++i) { acc += w2[k * hidden + i] * hidden_act[i]; }"
    , "  output[k] = acc;"
    , "}"
    , ""
    , "// gB2[k] = dy[k]; gW2[k*hidden+i] = dy[k]*hidden_act[i]."
    , "kernel void jitml_mlp_grad_output("
    , "    device float *g_w2 [[buffer(0)]], device float *g_b2 [[buffer(1)]],"
    , "    const device float *d_l_dy [[buffer(2)]], const device float *hidden_act [[buffer(3)]],"
    , "    constant int &hidden [[buffer(4)]], constant int &outputs [[buffer(5)]],"
    , "    uint gid [[thread_position_in_grid]]) {"
    , "  int k = int(gid); if (k >= outputs) { return; }"
    , "  float dy = d_l_dy[k]; g_b2[k] = dy;"
    , "  for (int i = 0; i < hidden; ++i) { g_w2[k * hidden + i] = dy * hidden_act[i]; }"
    , "}"
    , ""
    , "// d_act[i] = sum_k W2[k*hidden+i]*dy[k]; d_pre = d_act*(1-h^2);"
    , "// gB1[i] = d_pre; gW1[i*inputs+j] = d_pre*input[j]."
    , "kernel void jitml_mlp_grad_hidden("
    , "    device float *g_w1 [[buffer(0)]], device float *g_b1 [[buffer(1)]],"
    , "    const device float *d_l_dy [[buffer(2)]], const device float *input [[buffer(3)]],"
    , "    const device float *hidden_act [[buffer(4)]], const device float *w2 [[buffer(5)]],"
    , "    constant int &inputs [[buffer(6)]], constant int &hidden [[buffer(7)]],"
    , "    constant int &outputs [[buffer(8)]], uint gid [[thread_position_in_grid]]) {"
    , "  int i = int(gid); if (i >= hidden) { return; }"
    , "  float d_act = 0.0f;"
    , "  for (int k = 0; k < outputs; ++k) { d_act += w2[k * hidden + i] * d_l_dy[k]; }"
    , "  float h = hidden_act[i]; float d_pre = d_act * (1.0f - h * h);"
    , "  g_b1[i] = d_pre;"
    , "  for (int j = 0; j < inputs; ++j) { g_w1[i * inputs + j] = d_pre * input[j]; }"
    , "}"
    , ""
    , "// Batched hidden activation: hidden_act[b*hidden+i] for one (b,i) per thread."
    , "kernel void jitml_mlp_batch_hidden("
    , "    device float *hidden_act [[buffer(0)]], const device float *input [[buffer(1)]],"
    , "    const device float *w1 [[buffer(2)]], const device float *b1 [[buffer(3)]],"
    , "    constant int &inputs [[buffer(4)]], constant int &hidden [[buffer(5)]],"
    , "    constant int &batch [[buffer(6)]], uint gid [[thread_position_in_grid]]) {"
    , "  int total = batch * hidden; int idx = int(gid); if (idx >= total) { return; }"
    , "  int b = idx / hidden; int i = idx % hidden; float acc = b1[i];"
    , "  for (int j = 0; j < inputs; ++j) { acc += w1[i * inputs + j] * input[b * inputs + j]; }"
    , "  hidden_act[b * hidden + i] = tanh(acc);"
    , "}"
    , ""
    , "// Batched output: output[b*outputs+k] for one (b,k) per thread."
    , "kernel void jitml_mlp_batch_output("
    , "    device float *output [[buffer(0)]], const device float *hidden_act [[buffer(1)]],"
    , "    const device float *w2 [[buffer(2)]], const device float *b2 [[buffer(3)]],"
    , "    constant int &hidden [[buffer(4)]], constant int &outputs [[buffer(5)]],"
    , "    constant int &batch [[buffer(6)]], uint gid [[thread_position_in_grid]]) {"
    , "  int total = batch * outputs; int idx = int(gid); if (idx >= total) { return; }"
    , "  int b = idx / outputs; int k = idx % outputs; float acc = b2[k];"
    , "  for (int i = 0; i < hidden; ++i) { acc += w2[k * hidden + i] * hidden_act[b * hidden + i]; }"
    , "  output[b * outputs + k] = acc;"
    , "}"
    , ""
    , "// Batched gradient over the batch, summed: g_b2[k], g_w2[k*hidden+i]."
    , "kernel void jitml_mlp_batch_grad_output("
    , "    device float *g_w2 [[buffer(0)]], device float *g_b2 [[buffer(1)]],"
    , "    const device float *d_l_dy [[buffer(2)]], const device float *hidden_act [[buffer(3)]],"
    , "    constant int &hidden [[buffer(4)]], constant int &outputs [[buffer(5)]],"
    , "    constant int &batch [[buffer(6)]], uint gid [[thread_position_in_grid]]) {"
    , "  int k = int(gid); if (k >= outputs) { return; }"
    , "  float gb = 0.0f;"
    , "  for (int b = 0; b < batch; ++b) { gb += d_l_dy[b * outputs + k]; }"
    , "  g_b2[k] = gb;"
    , "  for (int i = 0; i < hidden; ++i) {"
    , "    float gw = 0.0f;"
    , "    for (int b = 0; b < batch; ++b) { gw += d_l_dy[b * outputs + k] * hidden_act[b * hidden + i]; }"
    , "    g_w2[k * hidden + i] = gw;"
    , "  }"
    , "}"
    , ""
    , "// Batched gradient over the batch, summed: g_b1[i], g_w1[i*inputs+j]."
    , "kernel void jitml_mlp_batch_grad_hidden("
    , "    device float *g_w1 [[buffer(0)]], device float *g_b1 [[buffer(1)]],"
    , "    const device float *d_l_dy [[buffer(2)]], const device float *input [[buffer(3)]],"
    , "    const device float *hidden_act [[buffer(4)]], const device float *w2 [[buffer(5)]],"
    , "    constant int &inputs [[buffer(6)]], constant int &hidden [[buffer(7)]],"
    , "    constant int &outputs [[buffer(8)]], constant int &batch [[buffer(9)]],"
    , "    uint gid [[thread_position_in_grid]]) {"
    , "  int i = int(gid); if (i >= hidden) { return; }"
    , "  float gb1 = 0.0f;"
    , "  for (int j = 0; j < inputs; ++j) { g_w1[i * inputs + j] = 0.0f; }"
    , "  for (int b = 0; b < batch; ++b) {"
    , "    float d_act = 0.0f;"
    , "    for (int k = 0; k < outputs; ++k) { d_act += w2[k * hidden + i] * d_l_dy[b * outputs + k]; }"
    , "    float h = hidden_act[b * hidden + i]; float d_pre = d_act * (1.0f - h * h);"
    , "    gb1 += d_pre;"
    , "    for (int j = 0; j < inputs; ++j) { g_w1[i * inputs + j] += d_pre * input[b * inputs + j]; }"
    , "  }"
    , "  g_b1[i] = gb1;"
    , "}"
    , ""
    , "// d_pre[b*hidden+i] for the per-sample input gradient."
    , "kernel void jitml_mlp_dpre_batch("
    , "    device float *d_hidden_pre [[buffer(0)]], const device float *d_l_dy [[buffer(1)]],"
    , "    const device float *hidden_act [[buffer(2)]], const device float *w2 [[buffer(3)]],"
    , "    constant int &hidden [[buffer(4)]], constant int &outputs [[buffer(5)]],"
    , "    constant int &batch [[buffer(6)]], uint gid [[thread_position_in_grid]]) {"
    , "  int total = batch * hidden; int idx = int(gid); if (idx >= total) { return; }"
    , "  int b = idx / hidden; int i = idx % hidden; float d_act = 0.0f;"
    , "  for (int k = 0; k < outputs; ++k) { d_act += w2[k * hidden + i] * d_l_dy[b * outputs + k]; }"
    , "  float h = hidden_act[b * hidden + i];"
    , "  d_hidden_pre[b * hidden + i] = d_act * (1.0f - h * h);"
    , "}"
    , ""
    , "// dx[b*inputs+j] = sum_i W1[i*inputs+j] * d_hidden_pre[b*hidden+i]."
    , "kernel void jitml_mlp_dx_batch("
    , "    device float *dx [[buffer(0)]], const device float *d_hidden_pre [[buffer(1)]],"
    , "    const device float *w1 [[buffer(2)]],"
    , "    constant int &inputs [[buffer(3)]], constant int &hidden [[buffer(4)]],"
    , "    constant int &batch [[buffer(5)]], uint gid [[thread_position_in_grid]]) {"
    , "  int total = batch * inputs; int idx = int(gid); if (idx >= total) { return; }"
    , "  int b = idx / inputs; int j = idx % inputs; float acc = 0.0f;"
    , "  for (int i = 0; i < hidden; ++i) { acc += w1[i * inputs + j] * d_hidden_pre[b * hidden + i]; }"
    , "  dx[b * inputs + j] = acc;"
    , "}"
    ]

forwardCdecl :: Text
forwardCdecl =
  Text.unlines
    [ "@_cdecl(\"jitml_mlp_forward\")"
    , "public func jitmlMlpForward("
    , "    _ hidden_pre: UnsafeMutablePointer<Float>, _ hidden_act: UnsafeMutablePointer<Float>,"
    , "    _ output: UnsafeMutablePointer<Float>, _ input: UnsafePointer<Float>,"
    , "    _ w1: UnsafePointer<Float>, _ b1: UnsafePointer<Float>,"
    , "    _ w2: UnsafePointer<Float>, _ b2: UnsafePointer<Float>,"
    , "    _ inputs: Int32, _ hidden: Int32, _ outputs: Int32) {"
    , "  let ni = Int(inputs), nh = Int(hidden), no = Int(outputs)"
    , "  for i in 0..<nh { hidden_pre[i] = 0; hidden_act[i] = 0 }"
    , "  for k in 0..<no { output[k] = 0 }"
    , "  guard nh > 0, no > 0, let device = jitmlDevice,"
    , "        let bHpre = jitmlBuffer(device, nil, nh), let bHact = jitmlBuffer(device, nil, nh),"
    , "        let bOut = jitmlBuffer(device, nil, no), let bIn = jitmlBuffer(device, input, ni),"
    , "        let bW1 = jitmlBuffer(device, w1, nh * ni), let bB1 = jitmlBuffer(device, b1, nh),"
    , "        let bW2 = jitmlBuffer(device, w2, no * nh), let bB2 = jitmlBuffer(device, b2, no)"
    , "  else { return }"
    , "  jitmlDispatch(\"jitml_mlp_hidden\", nh, [bHpre, bHact, bIn, bW1, bB1], [ni, nh])"
    , "  jitmlDispatch(\"jitml_mlp_output\", no, [bOut, bHact, bW2, bB2], [nh, no])"
    , "  memcpy(hidden_pre, bHpre.contents(), nh * MemoryLayout<Float>.stride)"
    , "  memcpy(hidden_act, bHact.contents(), nh * MemoryLayout<Float>.stride)"
    , "  memcpy(output, bOut.contents(), no * MemoryLayout<Float>.stride)"
    , "}"
    ]

backwardCdecl :: Text
backwardCdecl =
  Text.unlines
    [ "@_cdecl(\"jitml_mlp_backward\")"
    , "public func jitmlMlpBackward("
    , "    _ g_w1: UnsafeMutablePointer<Float>, _ g_b1: UnsafeMutablePointer<Float>,"
    , "    _ g_w2: UnsafeMutablePointer<Float>, _ g_b2: UnsafeMutablePointer<Float>,"
    , "    _ d_l_dy: UnsafePointer<Float>, _ input: UnsafePointer<Float>,"
    , "    _ hidden_act: UnsafePointer<Float>, _ w2: UnsafePointer<Float>,"
    , "    _ inputs: Int32, _ hidden: Int32, _ outputs: Int32) {"
    , "  let ni = Int(inputs), nh = Int(hidden), no = Int(outputs)"
    , "  let w1n = nh * ni, w2n = no * nh"
    , "  for i in 0..<w1n { g_w1[i] = 0 }; for i in 0..<nh { g_b1[i] = 0 }"
    , "  for i in 0..<w2n { g_w2[i] = 0 }; for i in 0..<no { g_b2[i] = 0 }"
    , "  guard nh > 0, no > 0, let device = jitmlDevice,"
    , "        let bGW1 = jitmlBuffer(device, nil, w1n), let bGB1 = jitmlBuffer(device, nil, nh),"
    , "        let bGW2 = jitmlBuffer(device, nil, w2n), let bGB2 = jitmlBuffer(device, nil, no),"
    , "        let bDy = jitmlBuffer(device, d_l_dy, no), let bIn = jitmlBuffer(device, input, ni),"
    , "        let bHact = jitmlBuffer(device, hidden_act, nh), let bW2 = jitmlBuffer(device, w2, w2n)"
    , "  else { return }"
    , "  jitmlDispatch(\"jitml_mlp_grad_output\", no, [bGW2, bGB2, bDy, bHact], [nh, no])"
    , "  jitmlDispatch(\"jitml_mlp_grad_hidden\", nh, [bGW1, bGB1, bDy, bIn, bHact, bW2], [ni, nh, no])"
    , "  memcpy(g_w1, bGW1.contents(), w1n * MemoryLayout<Float>.stride)"
    , "  memcpy(g_b1, bGB1.contents(), nh * MemoryLayout<Float>.stride)"
    , "  memcpy(g_w2, bGW2.contents(), w2n * MemoryLayout<Float>.stride)"
    , "  memcpy(g_b2, bGB2.contents(), no * MemoryLayout<Float>.stride)"
    , "}"
    ]

forwardBatchCdecl :: Text
forwardBatchCdecl =
  Text.unlines
    [ "@_cdecl(\"jitml_mlp_forward_batch\")"
    , "public func jitmlMlpForwardBatch("
    , "    _ output: UnsafeMutablePointer<Float>, _ input: UnsafePointer<Float>,"
    , "    _ w1: UnsafePointer<Float>, _ b1: UnsafePointer<Float>,"
    , "    _ w2: UnsafePointer<Float>, _ b2: UnsafePointer<Float>,"
    , "    _ inputs: Int32, _ hidden: Int32, _ outputs: Int32, _ batch: Int32) {"
    , "  let ni = Int(inputs), nh = Int(hidden), no = Int(outputs), nb = Int(batch)"
    , "  for k in 0..<(nb * no) { output[k] = 0 }"
    , "  guard nh > 0, no > 0, nb > 0, let device = jitmlDevice,"
    , "        let bOut = jitmlBuffer(device, nil, nb * no), let bHact = jitmlBuffer(device, nil, nb * nh),"
    , "        let bIn = jitmlBuffer(device, input, nb * ni), let bW1 = jitmlBuffer(device, w1, nh * ni),"
    , "        let bB1 = jitmlBuffer(device, b1, nh), let bW2 = jitmlBuffer(device, w2, no * nh),"
    , "        let bB2 = jitmlBuffer(device, b2, no)"
    , "  else { return }"
    , "  jitmlDispatch(\"jitml_mlp_batch_hidden\", nb * nh, [bHact, bIn, bW1, bB1], [ni, nh, nb])"
    , "  jitmlDispatch(\"jitml_mlp_batch_output\", nb * no, [bOut, bHact, bW2, bB2], [nh, no, nb])"
    , "  memcpy(output, bOut.contents(), nb * no * MemoryLayout<Float>.stride)"
    , "}"
    ]

batchGradientCdecl :: Text
batchGradientCdecl =
  Text.unlines
    [ "@_cdecl(\"jitml_mlp_batch_gradient\")"
    , "public func jitmlMlpBatchGradient("
    , "    _ g_w1: UnsafeMutablePointer<Float>, _ g_b1: UnsafeMutablePointer<Float>,"
    , "    _ g_w2: UnsafeMutablePointer<Float>, _ g_b2: UnsafeMutablePointer<Float>,"
    , "    _ input: UnsafePointer<Float>, _ d_l_dy: UnsafePointer<Float>,"
    , "    _ w1: UnsafePointer<Float>, _ b1: UnsafePointer<Float>, _ w2: UnsafePointer<Float>,"
    , "    _ inputs: Int32, _ hidden: Int32, _ outputs: Int32, _ batch: Int32) {"
    , "  let ni = Int(inputs), nh = Int(hidden), no = Int(outputs), nb = Int(batch)"
    , "  let w1n = nh * ni, w2n = no * nh"
    , "  for i in 0..<w1n { g_w1[i] = 0 }; for i in 0..<nh { g_b1[i] = 0 }"
    , "  for i in 0..<w2n { g_w2[i] = 0 }; for i in 0..<no { g_b2[i] = 0 }"
    , "  guard nh > 0, no > 0, nb > 0, let device = jitmlDevice,"
    , "        let bGW1 = jitmlBuffer(device, nil, w1n), let bGB1 = jitmlBuffer(device, nil, nh),"
    , "        let bGW2 = jitmlBuffer(device, nil, w2n), let bGB2 = jitmlBuffer(device, nil, no),"
    , "        let bHact = jitmlBuffer(device, nil, nb * nh),"
    , "        let bIn = jitmlBuffer(device, input, nb * ni), let bDy = jitmlBuffer(device, d_l_dy, nb * no),"
    , "        let bW1 = jitmlBuffer(device, w1, w1n), let bB1 = jitmlBuffer(device, b1, nh),"
    , "        let bW2 = jitmlBuffer(device, w2, w2n)"
    , "  else { return }"
    , "  jitmlDispatch(\"jitml_mlp_batch_hidden\", nb * nh, [bHact, bIn, bW1, bB1], [ni, nh, nb])"
    , "  jitmlDispatch(\"jitml_mlp_batch_grad_output\", no, [bGW2, bGB2, bDy, bHact], [nh, no, nb])"
    , "  jitmlDispatch(\"jitml_mlp_batch_grad_hidden\", nh, [bGW1, bGB1, bDy, bIn, bHact, bW2], [ni, nh, no, nb])"
    , "  memcpy(g_w1, bGW1.contents(), w1n * MemoryLayout<Float>.stride)"
    , "  memcpy(g_b1, bGB1.contents(), nh * MemoryLayout<Float>.stride)"
    , "  memcpy(g_w2, bGW2.contents(), w2n * MemoryLayout<Float>.stride)"
    , "  memcpy(g_b2, bGB2.contents(), no * MemoryLayout<Float>.stride)"
    , "}"
    ]

inputGradientBatchCdecl :: Text
inputGradientBatchCdecl =
  Text.unlines
    [ "@_cdecl(\"jitml_mlp_input_gradient_batch\")"
    , "public func jitmlMlpInputGradientBatch("
    , "    _ dx: UnsafeMutablePointer<Float>, _ input: UnsafePointer<Float>,"
    , "    _ d_l_dy: UnsafePointer<Float>, _ w1: UnsafePointer<Float>,"
    , "    _ b1: UnsafePointer<Float>, _ w2: UnsafePointer<Float>,"
    , "    _ inputs: Int32, _ hidden: Int32, _ outputs: Int32, _ batch: Int32) {"
    , "  let ni = Int(inputs), nh = Int(hidden), no = Int(outputs), nb = Int(batch)"
    , "  for k in 0..<(nb * ni) { dx[k] = 0 }"
    , "  guard nh > 0, no > 0, ni > 0, nb > 0, let device = jitmlDevice,"
    , "        let bDx = jitmlBuffer(device, nil, nb * ni), let bHact = jitmlBuffer(device, nil, nb * nh),"
    , "        let bDpre = jitmlBuffer(device, nil, nb * nh),"
    , "        let bIn = jitmlBuffer(device, input, nb * ni), let bDy = jitmlBuffer(device, d_l_dy, nb * no),"
    , "        let bW1 = jitmlBuffer(device, w1, nh * ni), let bB1 = jitmlBuffer(device, b1, nh),"
    , "        let bW2 = jitmlBuffer(device, w2, no * nh)"
    , "  else { return }"
    , "  jitmlDispatch(\"jitml_mlp_batch_hidden\", nb * nh, [bHact, bIn, bW1, bB1], [ni, nh, nb])"
    , "  jitmlDispatch(\"jitml_mlp_dpre_batch\", nb * nh, [bDpre, bDy, bHact, bW2], [nh, no, nb])"
    , "  jitmlDispatch(\"jitml_mlp_dx_batch\", nb * ni, [bDx, bDpre, bW1], [ni, nh, nb])"
    , "  memcpy(dx, bDx.contents(), nb * ni * MemoryLayout<Float>.stride)"
    , "}"
    ]
