{-# LANGUAGE OverloadedStrings #-}

-- | Sprint (backend-parity) — the Linux-CPU (oneDNN lane) MLP forward/backward
-- kernel source, mirroring "JitML.Codegen.MlpCuda" but as plain deterministic
-- C++ that computes directly on the host @float@ buffers (no device alloc/copy
-- — the oneDNN lane runs on the CPU). The emitted @extern "C"@ ABI is byte-for-
-- byte identical to the CUDA one (same @jitml_mlp_*@ symbols and argument
-- order), so "JitML.Numerics.MlpDevice" marshals to it unchanged.
--
-- The kernel uses sequential reductions (no atomics, fixed @j@/@b@ iteration
-- order) so its output is bit-deterministic run-to-run on the same host, per
-- the determinism contract, and matches the pure 'JitML.Numerics.Mlp' network
-- within single precision. The file compiles through the existing oneDNN path
-- (@g++ -std=c++20 -O2 -fPIC -shared … kernel.cc -ldnnl@); it does not use
-- libdnnl itself — the MLP math is small dense loops, kept here for determinism.
module JitML.Codegen.MlpOneDnn
  ( mlpOneDnnKernelSpec
  , renderMlpOneDnnSource
  )
where

import Data.Text (Text)
import Data.Text qualified as Text

import JitML.Cache.Key (KernelSpec (..))
import JitML.Codegen.SourceFile (SourceFile (..))

-- | Kernel-spec identifier for the MLP forward/backward oneDNN kernel. Shares
-- the conceptual name with the CUDA kernel; the cache key disambiguates by
-- substrate + toolchain fingerprint, so it occupies its own JIT cache slot.
mlpOneDnnKernelSpec :: KernelSpec
mlpOneDnnKernelSpec = KernelSpec "mlp-forward-backward-tanh-linear"

-- | The generated oneDNN source files (one @kernel.cc@, matching the g++
-- compile command in "JitML.Engines.Engine").
renderMlpOneDnnSource :: [SourceFile]
renderMlpOneDnnSource = [SourceFile "kernel.cc" mlpOneDnnSource]

mlpOneDnnSource :: Text
mlpOneDnnSource =
  Text.unlines
    [ "// Generated by jitml. Do not check generated oneDNN MLP source into git."
    , "#include <cmath>"
    , "#include <cstddef>"
    , "#include <vector>"
    , ""
    , "static const char *jitml_mlp_rng_policy = \"host-seeded-no-curand\";"
    , "// determinism: sequential reductions (no atomics); fixed iteration order."
    , ""
    , forwardWrapper
    , ""
    , backwardWrapper
    , ""
    , forwardBatchWrapper
    , ""
    , batchGradientWrapper
    , ""
    , inputGradientBatchWrapper
    ]

forwardWrapper :: Text
forwardWrapper =
  Text.unlines
    [ "// hidden_pre[i] = b1[i] + sum_j W1[i*inputs+j]*input[j];"
    , "// hidden_act[i] = tanh(hidden_pre[i]);"
    , "// output[k] = b2[k] + sum_i W2[k*hidden+i]*hidden_act[i]."
    , "extern \"C\" void jitml_mlp_forward("
    , "    float *hidden_pre, float *hidden_act, float *output,"
    , "    const float *input, const float *w1, const float *b1,"
    , "    const float *w2, const float *b2,"
    , "    int inputs, int hidden, int outputs) {"
    , "  if (hidden <= 0 || outputs <= 0) { return; }"
    , "  for (int i = 0; i < hidden; ++i) {"
    , "    float acc = b1[i];"
    , "    for (int j = 0; j < inputs; ++j) { acc += w1[i * inputs + j] * input[j]; }"
    , "    hidden_pre[i] = acc;"
    , "    hidden_act[i] = std::tanh(acc);"
    , "  }"
    , "  for (int k = 0; k < outputs; ++k) {"
    , "    float acc = b2[k];"
    , "    for (int i = 0; i < hidden; ++i) { acc += w2[k * hidden + i] * hidden_act[i]; }"
    , "    output[k] = acc;"
    , "  }"
    , "}"
    ]

backwardWrapper :: Text
backwardWrapper =
  Text.unlines
    [ "// gB2[k] = dy[k];  gW2[k*hidden+i] = dy[k]*hidden_act[i];"
    , "// d_act[i] = sum_k W2[k*hidden+i]*dy[k];  d_pre[i] = d_act[i]*(1 - h^2);"
    , "// gB1[i] = d_pre[i];  gW1[i*inputs+j] = d_pre[i]*input[j]."
    , "extern \"C\" void jitml_mlp_backward("
    , "    float *g_w1, float *g_b1, float *g_w2, float *g_b2,"
    , "    const float *d_l_dy, const float *input,"
    , "    const float *hidden_act, const float *w2,"
    , "    int inputs, int hidden, int outputs) {"
    , "  if (hidden <= 0 || outputs <= 0) { return; }"
    , "  for (int k = 0; k < outputs; ++k) {"
    , "    float dy = d_l_dy[k];"
    , "    g_b2[k] = dy;"
    , "    for (int i = 0; i < hidden; ++i) { g_w2[k * hidden + i] = dy * hidden_act[i]; }"
    , "  }"
    , "  for (int i = 0; i < hidden; ++i) {"
    , "    float d_act = 0.0f;"
    , "    for (int k = 0; k < outputs; ++k) { d_act += w2[k * hidden + i] * d_l_dy[k]; }"
    , "    float h = hidden_act[i];"
    , "    float d_pre = d_act * (1.0f - h * h);"
    , "    g_b1[i] = d_pre;"
    , "    for (int j = 0; j < inputs; ++j) { g_w1[i * inputs + j] = d_pre * input[j]; }"
    , "  }"
    , "}"
    ]

forwardBatchWrapper :: Text
forwardBatchWrapper =
  Text.unlines
    [ "// output[b][k] = b2[k] + sum_i W2[k][i] * tanh(b1[i] + sum_j W1[i][j]*input[b][j])."
    , "extern \"C\" void jitml_mlp_forward_batch("
    , "    float *output, const float *input,"
    , "    const float *w1, const float *b1, const float *w2, const float *b2,"
    , "    int inputs, int hidden, int outputs, int batch) {"
    , "  if (hidden <= 0 || outputs <= 0 || batch <= 0) { return; }"
    , "  std::vector<float> hact(static_cast<std::size_t>(hidden));"
    , "  for (int b = 0; b < batch; ++b) {"
    , "    for (int i = 0; i < hidden; ++i) {"
    , "      float acc = b1[i];"
    , "      for (int j = 0; j < inputs; ++j) { acc += w1[i * inputs + j] * input[b * inputs + j]; }"
    , "      hact[i] = std::tanh(acc);"
    , "    }"
    , "    for (int k = 0; k < outputs; ++k) {"
    , "      float acc = b2[k];"
    , "      for (int i = 0; i < hidden; ++i) { acc += w2[k * hidden + i] * hact[i]; }"
    , "      output[b * outputs + k] = acc;"
    , "    }"
    , "  }"
    , "}"
    ]

batchGradientWrapper :: Text
batchGradientWrapper =
  Text.unlines
    [ "// Parameter gradient summed over the batch (matches the CUDA batch-grad"
    , "// reduction order: batch index b ascending)."
    , "extern \"C\" void jitml_mlp_batch_gradient("
    , "    float *g_w1, float *g_b1, float *g_w2, float *g_b2,"
    , "    const float *input, const float *d_l_dy,"
    , "    const float *w1, const float *b1, const float *w2,"
    , "    int inputs, int hidden, int outputs, int batch) {"
    , "  if (hidden <= 0 || outputs <= 0 || batch <= 0) { return; }"
    , "  std::size_t hact_n = static_cast<std::size_t>(batch) * static_cast<std::size_t>(hidden);"
    , "  std::vector<float> hact(hact_n);"
    , "  for (int b = 0; b < batch; ++b) {"
    , "    for (int i = 0; i < hidden; ++i) {"
    , "      float acc = b1[i];"
    , "      for (int j = 0; j < inputs; ++j) { acc += w1[i * inputs + j] * input[b * inputs + j]; }"
    , "      hact[static_cast<std::size_t>(b) * hidden + i] = std::tanh(acc);"
    , "    }"
    , "  }"
    , "  for (int k = 0; k < outputs; ++k) {"
    , "    float gb = 0.0f;"
    , "    for (int b = 0; b < batch; ++b) { gb += d_l_dy[b * outputs + k]; }"
    , "    g_b2[k] = gb;"
    , "    for (int i = 0; i < hidden; ++i) {"
    , "      float gw = 0.0f;"
    , "      for (int b = 0; b < batch; ++b) {"
    , "        gw += d_l_dy[b * outputs + k] * hact[static_cast<std::size_t>(b) * hidden + i];"
    , "      }"
    , "      g_w2[k * hidden + i] = gw;"
    , "    }"
    , "  }"
    , "  for (int i = 0; i < hidden; ++i) {"
    , "    float gb1 = 0.0f;"
    , "    for (int j = 0; j < inputs; ++j) { g_w1[i * inputs + j] = 0.0f; }"
    , "    for (int b = 0; b < batch; ++b) {"
    , "      float d_act = 0.0f;"
    , "      for (int k = 0; k < outputs; ++k) { d_act += w2[k * hidden + i] * d_l_dy[b * outputs + k]; }"
    , "      float h = hact[static_cast<std::size_t>(b) * hidden + i];"
    , "      float d_pre = d_act * (1.0f - h * h);"
    , "      gb1 += d_pre;"
    , "      for (int j = 0; j < inputs; ++j) { g_w1[i * inputs + j] += d_pre * input[b * inputs + j]; }"
    , "    }"
    , "    g_b1[i] = gb1;"
    , "  }"
    , "}"
    ]

inputGradientBatchWrapper :: Text
inputGradientBatchWrapper =
  Text.unlines
    [ "// Per-sample input gradient: dx[b][j] = sum_i W1[i][j] * d_pre[b][i],"
    , "// d_pre[b][i] = (sum_k W2[k][i]*dy[b][k]) * (1 - hidden_act[b][i]^2)."
    , "extern \"C\" void jitml_mlp_input_gradient_batch("
    , "    float *dx, const float *input, const float *d_l_dy,"
    , "    const float *w1, const float *b1, const float *w2,"
    , "    int inputs, int hidden, int outputs, int batch) {"
    , "  if (hidden <= 0 || outputs <= 0 || inputs <= 0 || batch <= 0) { return; }"
    , "  std::size_t hact_n = static_cast<std::size_t>(batch) * static_cast<std::size_t>(hidden);"
    , "  std::vector<float> hact(hact_n);"
    , "  std::vector<float> dpre(hact_n);"
    , "  for (int b = 0; b < batch; ++b) {"
    , "    for (int i = 0; i < hidden; ++i) {"
    , "      float acc = b1[i];"
    , "      for (int j = 0; j < inputs; ++j) { acc += w1[i * inputs + j] * input[b * inputs + j]; }"
    , "      hact[static_cast<std::size_t>(b) * hidden + i] = std::tanh(acc);"
    , "    }"
    , "  }"
    , "  for (int b = 0; b < batch; ++b) {"
    , "    for (int i = 0; i < hidden; ++i) {"
    , "      float d_act = 0.0f;"
    , "      for (int k = 0; k < outputs; ++k) { d_act += w2[k * hidden + i] * d_l_dy[b * outputs + k]; }"
    , "      float h = hact[static_cast<std::size_t>(b) * hidden + i];"
    , "      dpre[static_cast<std::size_t>(b) * hidden + i] = d_act * (1.0f - h * h);"
    , "    }"
    , "  }"
    , "  for (int b = 0; b < batch; ++b) {"
    , "    for (int j = 0; j < inputs; ++j) {"
    , "      float acc = 0.0f;"
    , "      for (int i = 0; i < hidden; ++i) {"
    , "        acc += w1[i * inputs + j] * dpre[static_cast<std::size_t>(b) * hidden + i];"
    , "      }"
    , "      dx[b * inputs + j] = acc;"
    , "    }"
    , "  }"
    , "}"
    ]
