{-# LANGUAGE OverloadedStrings #-}

module JitML.Codegen.OneDnn
  ( renderOneDnnSource
  , renderOneDnnFamilySource
  )
where

import Data.Text (Text)
import Data.Text qualified as Text

import JitML.Cache.Key (KernelSpec (..), Kind, TuningChoice (..), kindText)
import JitML.Codegen.KernelFamily (KernelFamily (..), familyName)
import JitML.Codegen.SourceFile (SourceFile (..))

renderOneDnnSource :: KernelSpec -> Kind -> TuningChoice -> [SourceFile]
renderOneDnnSource = renderOneDnnFamilySource Identity

renderOneDnnFamilySource
  :: KernelFamily -> KernelSpec -> Kind -> TuningChoice -> [SourceFile]
renderOneDnnFamilySource family kernelSpec kind tuningChoice =
  [ SourceFile "kernel.cc" (oneDnnSource family kernelSpec kind tuningChoice)
  ]

oneDnnSource :: KernelFamily -> KernelSpec -> Kind -> TuningChoice -> Text
oneDnnSource family kernelSpec kind tuningChoice =
  Text.unlines
    [ "// Generated by jitml. Do not check generated oneDNN source into git."
    , "#include <algorithm>"
    , "#include <cmath>"
    , "#include <cstddef>"
    , "#include <cstdint>"
    , ""
    , familyImpl family
    , ""
    , "static const char *jitml_kernel_spec = " <> cString (kernelSpecPayload kernelSpec) <> ";"
    , "static const char *jitml_kernel_kind = " <> cString (kindText kind) <> ";"
    , "static const char *jitml_tuning_choice = " <> cString (unTuningChoice tuningChoice) <> ";"
    , "static const char *jitml_kernel_family = " <> cString (familyName family) <> ";"
    , "static const int jitml_fixed_reduction_block = 256;"
    ]

familyImpl :: KernelFamily -> Text
familyImpl Identity =
  identityImpl
familyImpl Reduction =
  Text.unlines
    [ "// Deterministic block-stride reduction over n floats."
    , "extern \"C\" void jitml_kernel(float *out, const float *input, std::size_t n) {"
    , "  const std::size_t block = static_cast<std::size_t>(jitml_fixed_reduction_block_size());"
    , "  double accumulator = 0.0;"
    , "  for (std::size_t base = 0; base < n; base += block) {"
    , "    double partial = 0.0;"
    , "    const std::size_t bound = std::min(base + block, n);"
    , "    for (std::size_t i = base; i < bound; ++i) {"
    , "      partial += static_cast<double>(input[i]);"
    , "    }"
    , "    accumulator += partial;"
    , "  }"
    , "  out[0] = static_cast<float>(accumulator);"
    , "}"
    , ""
    , "extern \"C\" int jitml_fixed_reduction_block_size(void) { return 256; }"
    ]
familyImpl Dense2D =
  Text.unlines
    [ "// Row-major dense GEMM stub: out = input * weights^T with deterministic ordering."
    , "// Weights live in a separate ABI surface; this scaffold provides the contract."
    , "extern \"C\" void jitml_kernel(float *out, const float *input, std::size_t n) {"
    , "  for (std::size_t i = 0; i < n; ++i) {"
    , "    out[i] = input[i];"
    , "  }"
    , "}"
    , ""
    , "extern \"C\" const char *jitml_kernel_family_name(void) { return \"dense\"; }"
    ]
familyImpl Conv2DKernel =
  Text.unlines
    [ "// 2D convolution stub. The oneDNN graph wiring (engine, primitive, memory)"
    , "// is dispatched at runtime from the Haskell engine driver."
    , "extern \"C\" void jitml_kernel(float *out, const float *input, std::size_t n) {"
    , "  for (std::size_t i = 0; i < n; ++i) {"
    , "    out[i] = input[i];"
    , "  }"
    , "}"
    , ""
    , "extern \"C\" const char *jitml_kernel_family_name(void) { return \"conv2d\"; }"
    ]
familyImpl Conv3DKernel =
  Text.unlines
    [ "extern \"C\" void jitml_kernel(float *out, const float *input, std::size_t n) {"
    , "  for (std::size_t i = 0; i < n; ++i) {"
    , "    out[i] = input[i];"
    , "  }"
    , "}"
    , ""
    , "extern \"C\" const char *jitml_kernel_family_name(void) { return \"conv3d\"; }"
    ]
familyImpl BatchNormKernel =
  Text.unlines
    [ "// Inference-mode batch-norm scaffold using compile-time eps."
    , "extern \"C\" void jitml_kernel(float *out, const float *input, std::size_t n) {"
    , "  const float eps = 1.0e-5f;"
    , "  for (std::size_t i = 0; i < n; ++i) {"
    , "    out[i] = input[i] / std::sqrt(input[i] * input[i] + eps);"
    , "  }"
    , "}"
    , ""
    , "extern \"C\" const char *jitml_kernel_family_name(void) { return \"batchnorm\"; }"
    ]
familyImpl LayerNormKernel =
  Text.unlines
    [ "extern \"C\" void jitml_kernel(float *out, const float *input, std::size_t n) {"
    , "  const float eps = 1.0e-5f;"
    , "  double mean = 0.0;"
    , "  for (std::size_t i = 0; i < n; ++i) { mean += static_cast<double>(input[i]); }"
    , "  mean /= static_cast<double>(n);"
    , "  double var = 0.0;"
    , "  for (std::size_t i = 0; i < n; ++i) {"
    , "    double d = static_cast<double>(input[i]) - mean;"
    , "    var += d * d;"
    , "  }"
    , "  var /= static_cast<double>(n);"
    , "  float invstd = static_cast<float>(1.0 / std::sqrt(var + eps));"
    , "  for (std::size_t i = 0; i < n; ++i) {"
    , "    out[i] = (input[i] - static_cast<float>(mean)) * invstd;"
    , "  }"
    , "}"
    , ""
    , "extern \"C\" const char *jitml_kernel_family_name(void) { return \"layernorm\"; }"
    ]
familyImpl MultiHeadAttentionKernel =
  Text.unlines
    [ "// Multi-head attention scaffold. The real oneDNN graph wires QKV linear ops,"
    , "// scaled dot-product attention, and softmax inside the engine driver."
    , "extern \"C\" void jitml_kernel(float *out, const float *input, std::size_t n) {"
    , "  for (std::size_t i = 0; i < n; ++i) {"
    , "    out[i] = input[i];"
    , "  }"
    , "}"
    , ""
    , "extern \"C\" const char *jitml_kernel_family_name(void) { return \"mha\"; }"
    ]
familyImpl EmbeddingKernel =
  Text.unlines
    [ "// Embedding-lookup stub. Real path indexes a contiguous weight table."
    , "extern \"C\" void jitml_kernel(float *out, const float *input, std::size_t n) {"
    , "  for (std::size_t i = 0; i < n; ++i) {"
    , "    out[i] = input[i];"
    , "  }"
    , "}"
    , ""
    , "extern \"C\" const char *jitml_kernel_family_name(void) { return \"embedding\"; }"
    ]

identityImpl :: Text
identityImpl =
  Text.unlines
    [ "extern \"C\" void jitml_kernel(float *out, const float *input, std::size_t n) {"
    , "  for (std::size_t i = 0; i < n; ++i) {"
    , "    out[i] = input[i];"
    , "  }"
    , "}"
    ]

cString :: Text -> Text
cString value =
  "\"" <> Text.concatMap escape value <> "\""

escape :: Char -> Text
escape '"' = "\\\""
escape '\\' = "\\\\"
escape '\n' = "\\n"
escape char = Text.singleton char
