{-# LANGUAGE OverloadedStrings #-}

module JitML.Codegen.OneDnn
  ( renderOneDnnSource
  , renderOneDnnFamilySource
  )
where

import Data.Text (Text)
import Data.Text qualified as Text

import JitML.Cache.Key (KernelSpec (..), Kind, TuningChoice (..), kindText)
import JitML.Codegen.KernelFamily (KernelFamily (..), familyName)
import JitML.Codegen.SourceFile (SourceFile (..))

renderOneDnnSource :: KernelSpec -> Kind -> TuningChoice -> [SourceFile]
renderOneDnnSource = renderOneDnnFamilySource Identity

renderOneDnnFamilySource
  :: KernelFamily -> KernelSpec -> Kind -> TuningChoice -> [SourceFile]
renderOneDnnFamilySource family kernelSpec kind tuningChoice =
  [ SourceFile "kernel.cc" (oneDnnSource family kernelSpec kind tuningChoice)
  ]

oneDnnSource :: KernelFamily -> KernelSpec -> Kind -> TuningChoice -> Text
oneDnnSource family kernelSpec kind tuningChoice =
  Text.unlines
    [ "// Generated by jitml. Do not check generated oneDNN source into git."
    , "#include <oneapi/dnnl/dnnl.hpp>"
    , "#include <algorithm>"
    , "#include <cmath>"
    , "#include <cstddef>"
    , "#include <cstdint>"
    , "#include <vector>"
    , ""
    , commonOneDnnHelpers
    , ""
    , familyImpl family
    , ""
    , "static const char *jitml_kernel_spec = " <> cString (kernelSpecPayload kernelSpec) <> ";"
    , "static const char *jitml_kernel_kind = " <> cString (kindText kind) <> ";"
    , "static const char *jitml_tuning_choice = " <> cString (unTuningChoice tuningChoice) <> ";"
    , "static const char *jitml_kernel_family = " <> cString (familyName family) <> ";"
    , "static const int jitml_fixed_reduction_block = 256;"
    , ""
    , "extern \"C\" const char *jitml_kernel_family_name(void) { return jitml_kernel_family; }"
    , kernelOutputCountFunction family
    ]

commonOneDnnHelpers :: Text
commonOneDnnHelpers =
  Text.unlines
    [ "namespace {"
    , "using namespace dnnl;"
    , ""
    , "memory::dim jitml_dim(std::size_t value) {"
    , "  return static_cast<memory::dim>(value);"
    , "}"
    , ""
    , "void jitml_onednn_reorder(float *out, const float *input, std::size_t n) {"
    , "  if (n == 0) { return; }"
    , "  engine eng(engine::kind::cpu, 0);"
    , "  stream s(eng);"
    , "  auto md = memory::desc({jitml_dim(n)}, memory::data_type::f32, memory::format_tag::x);"
    , "  auto src = memory(md, eng, const_cast<float *>(input));"
    , "  auto dst = memory(md, eng, out);"
    , "  reorder(src, dst).execute(s, src, dst);"
    , "  s.wait();"
    , "}"
    , ""
    , "void jitml_onednn_reduction_sum(float *out, const float *input, std::size_t n) {"
    , "  if (n == 0) { out[0] = 0.0f; return; }"
    , "  engine eng(engine::kind::cpu, 0);"
    , "  stream s(eng);"
    , "  auto src_md = memory::desc({jitml_dim(n)}, memory::data_type::f32, memory::format_tag::x);"
    , "  auto dst_md = memory::desc({1}, memory::data_type::f32, memory::format_tag::x);"
    , "  auto pd = reduction::primitive_desc(eng, algorithm::reduction_sum, src_md, dst_md, 0.0f, 0.0f);"
    , "  auto src = memory(src_md, eng, const_cast<float *>(input));"
    , "  auto dst = memory(dst_md, eng, out);"
    , "  reduction(pd).execute(s, {{DNNL_ARG_SRC, src}, {DNNL_ARG_DST, dst}});"
    , "  s.wait();"
    , "}"
    , ""
    , "void jitml_onednn_dense_identity(float *out, const float *input, std::size_t n) {"
    , "  if (n == 0) { return; }"
    , "  engine eng(engine::kind::cpu, 0);"
    , "  stream s(eng);"
    , "  std::vector<float> weights(n * n, 0.0f);"
    , "  for (std::size_t i = 0; i < n; ++i) { weights[i * n + i] = 1.0f; }"
    , "  auto src_md = memory::desc({1, jitml_dim(n)}, memory::data_type::f32, memory::format_tag::ab);"
    , "  auto weights_md = memory::desc({jitml_dim(n), jitml_dim(n)}, memory::data_type::f32, memory::format_tag::ab);"
    , "  auto dst_md = memory::desc({1, jitml_dim(n)}, memory::data_type::f32, memory::format_tag::ab);"
    , "  auto pd = matmul::primitive_desc(eng, src_md, weights_md, dst_md);"
    , "  auto src = memory(src_md, eng, const_cast<float *>(input));"
    , "  auto weight_mem = memory(weights_md, eng, weights.data());"
    , "  auto dst = memory(dst_md, eng, out);"
    , "  matmul(pd).execute(s, {{DNNL_ARG_SRC, src}, {DNNL_ARG_WEIGHTS, weight_mem}, {DNNL_ARG_DST, dst}});"
    , "  s.wait();"
    , "}"
    , ""
    , "void jitml_onednn_conv2d_unit(float *out, const float *input, std::size_t n) {"
    , "  if (n == 0) { return; }"
    , "  engine eng(engine::kind::cpu, 0);"
    , "  stream s(eng);"
    , "  float weight[1] = {1.0f};"
    , "  memory::dims src_dims = {1, 1, jitml_dim(n), 1};"
    , "  memory::dims weights_dims = {1, 1, 1, 1};"
    , "  memory::dims dst_dims = {1, 1, jitml_dim(n), 1};"
    , "  memory::dims strides = {1, 1};"
    , "  memory::dims padding = {0, 0};"
    , "  auto src_md = memory::desc(src_dims, memory::data_type::f32, memory::format_tag::nchw);"
    , "  auto weights_md = memory::desc(weights_dims, memory::data_type::f32, memory::format_tag::oihw);"
    , "  auto dst_md = memory::desc(dst_dims, memory::data_type::f32, memory::format_tag::nchw);"
    , "  auto pd = convolution_forward::primitive_desc(eng, prop_kind::forward_inference, algorithm::convolution_direct, src_md, weights_md, dst_md, strides, padding, padding);"
    , "  auto src = memory(src_md, eng, const_cast<float *>(input));"
    , "  auto weights = memory(weights_md, eng, weight);"
    , "  auto dst = memory(dst_md, eng, out);"
    , "  convolution_forward(pd).execute(s, {{DNNL_ARG_SRC, src}, {DNNL_ARG_WEIGHTS, weights}, {DNNL_ARG_DST, dst}});"
    , "  s.wait();"
    , "}"
    , ""
    , "void jitml_onednn_conv3d_unit(float *out, const float *input, std::size_t n) {"
    , "  if (n == 0) { return; }"
    , "  engine eng(engine::kind::cpu, 0);"
    , "  stream s(eng);"
    , "  float weight[1] = {1.0f};"
    , "  memory::dims src_dims = {1, 1, jitml_dim(n), 1, 1};"
    , "  memory::dims weights_dims = {1, 1, 1, 1, 1};"
    , "  memory::dims dst_dims = {1, 1, jitml_dim(n), 1, 1};"
    , "  memory::dims strides = {1, 1, 1};"
    , "  memory::dims padding = {0, 0, 0};"
    , "  auto src_md = memory::desc(src_dims, memory::data_type::f32, memory::format_tag::ncdhw);"
    , "  auto weights_md = memory::desc(weights_dims, memory::data_type::f32, memory::format_tag::oidhw);"
    , "  auto dst_md = memory::desc(dst_dims, memory::data_type::f32, memory::format_tag::ncdhw);"
    , "  auto pd = convolution_forward::primitive_desc(eng, prop_kind::forward_inference, algorithm::convolution_direct, src_md, weights_md, dst_md, strides, padding, padding);"
    , "  auto src = memory(src_md, eng, const_cast<float *>(input));"
    , "  auto weights = memory(weights_md, eng, weight);"
    , "  auto dst = memory(dst_md, eng, out);"
    , "  convolution_forward(pd).execute(s, {{DNNL_ARG_SRC, src}, {DNNL_ARG_WEIGHTS, weights}, {DNNL_ARG_DST, dst}});"
    , "  s.wait();"
    , "}"
    , ""
    , "void jitml_onednn_batchnorm(float *out, const float *input, std::size_t n) {"
    , "  if (n == 0) { return; }"
    , "  engine eng(engine::kind::cpu, 0);"
    , "  stream s(eng);"
    , "  float scale[1] = {1.0f};"
    , "  float shift[1] = {0.0f};"
    , "  float mean[1] = {0.0f};"
    , "  float variance[1] = {1.0f};"
    , "  auto md = memory::desc({1, 1, jitml_dim(n), 1}, memory::data_type::f32, memory::format_tag::nchw);"
    , "  auto flags = normalization_flags::use_scale | normalization_flags::use_shift | normalization_flags::use_global_stats;"
    , "  auto pd = batch_normalization_forward::primitive_desc(eng, prop_kind::forward_inference, md, md, 1.0e-5f, flags);"
    , "  auto src = memory(md, eng, const_cast<float *>(input));"
    , "  auto dst = memory(md, eng, out);"
    , "  auto param_md = memory::desc({1}, memory::data_type::f32, memory::format_tag::x);"
    , "  auto scale_mem = memory(param_md, eng, scale);"
    , "  auto shift_mem = memory(param_md, eng, shift);"
    , "  auto mean_mem = memory(pd.mean_desc(), eng, mean);"
    , "  auto variance_mem = memory(pd.variance_desc(), eng, variance);"
    , "  batch_normalization_forward(pd).execute(s, {{DNNL_ARG_SRC, src}, {DNNL_ARG_DST, dst}, {DNNL_ARG_SCALE, scale_mem}, {DNNL_ARG_SHIFT, shift_mem}, {DNNL_ARG_MEAN, mean_mem}, {DNNL_ARG_VARIANCE, variance_mem}});"
    , "  s.wait();"
    , "}"
    , ""
    , "void jitml_onednn_layernorm(float *out, const float *input, std::size_t n) {"
    , "  if (n == 0) { return; }"
    , "  engine eng(engine::kind::cpu, 0);"
    , "  stream s(eng);"
    , "  auto md = memory::desc({1, jitml_dim(n)}, memory::data_type::f32, memory::format_tag::ab);"
    , "  auto pd = layer_normalization_forward::primitive_desc(eng, prop_kind::forward_inference, md, md, 1.0e-5f, normalization_flags::none);"
    , "  auto src = memory(md, eng, const_cast<float *>(input));"
    , "  auto dst = memory(md, eng, out);"
    , "  layer_normalization_forward(pd).execute(s, {{DNNL_ARG_SRC, src}, {DNNL_ARG_DST, dst}});"
    , "  s.wait();"
    , "}"
    , "} // namespace"
    ]

familyImpl :: KernelFamily -> Text
familyImpl Identity =
  identityImpl
familyImpl Reduction =
  Text.unlines
    [ "// Deterministic oneDNN reduction over n floats."
    , "extern \"C\" int jitml_fixed_reduction_block_size(void) { return 256; }"
    , ""
    , "extern \"C\" void jitml_kernel(float *out, const float *input, std::size_t n) {"
    , "  jitml_onednn_reduction_sum(out, input, n);"
    , "}"
    ]
familyImpl Dense2D =
  Text.unlines
    [ "// Row-major oneDNN matmul: out = input * I."
    , "extern \"C\" void jitml_kernel(float *out, const float *input, std::size_t n) {"
    , "  jitml_onednn_dense_identity(out, input, n);"
    , "}"
    ]
familyImpl Conv2DKernel =
  Text.unlines
    [ "// oneDNN 1x1 Conv2D over a flattened fixture tensor."
    , "extern \"C\" void jitml_kernel(float *out, const float *input, std::size_t n) {"
    , "  jitml_onednn_conv2d_unit(out, input, n);"
    , "}"
    ]
familyImpl Conv3DKernel =
  Text.unlines
    [ "// oneDNN 1x1x1 Conv3D over a flattened fixture tensor."
    , "extern \"C\" void jitml_kernel(float *out, const float *input, std::size_t n) {"
    , "  jitml_onednn_conv3d_unit(out, input, n);"
    , "}"
    ]
familyImpl BatchNormKernel =
  Text.unlines
    [ "// oneDNN inference-mode batch normalization with fixed global stats."
    , "extern \"C\" void jitml_kernel(float *out, const float *input, std::size_t n) {"
    , "  jitml_onednn_batchnorm(out, input, n);"
    , "}"
    ]
familyImpl LayerNormKernel =
  Text.unlines
    [ "extern \"C\" void jitml_kernel(float *out, const float *input, std::size_t n) {"
    , "  jitml_onednn_layernorm(out, input, n);"
    , "}"
    ]
familyImpl MultiHeadAttentionKernel =
  Text.unlines
    [ "// oneDNN matmul-backed attention fixture until the QKV tensor ABI lands."
    , "extern \"C\" void jitml_kernel(float *out, const float *input, std::size_t n) {"
    , "  jitml_onednn_dense_identity(out, input, n);"
    , "}"
    ]
familyImpl EmbeddingKernel =
  Text.unlines
    [ "// oneDNN reorder-backed embedding fixture until the table-index ABI lands."
    , "extern \"C\" void jitml_kernel(float *out, const float *input, std::size_t n) {"
    , "  jitml_onednn_reorder(out, input, n);"
    , "}"
    ]

identityImpl :: Text
identityImpl =
  Text.unlines
    [ "extern \"C\" void jitml_kernel(float *out, const float *input, std::size_t n) {"
    , "  jitml_onednn_reorder(out, input, n);"
    , "}"
    ]

kernelOutputCountFunction :: KernelFamily -> Text
kernelOutputCountFunction Reduction =
  "extern \"C\" std::size_t jitml_kernel_output_count(std::size_t n) { (void)n; return 1; }"
kernelOutputCountFunction _ =
  "extern \"C\" std::size_t jitml_kernel_output_count(std::size_t n) { return n; }"

cString :: Text -> Text
cString value =
  "\"" <> Text.concatMap escape value <> "\""

escape :: Char -> Text
escape '"' = "\\\""
escape '\\' = "\\\\"
escape '\n' = "\\n"
escape char = Text.singleton char
