{-# LANGUAGE OverloadedStrings #-}

module JitML.Codegen.OneDnn
  ( renderOneDnnSource
  )
where

import Data.Text qualified as Text

import JitML.Cache.Key (KernelSpec (..), Kind, TuningChoice (..), kindText)
import JitML.Codegen.SourceFile (SourceFile (..))

renderOneDnnSource :: KernelSpec -> Kind -> TuningChoice -> [SourceFile]
renderOneDnnSource kernelSpec kind tuningChoice =
  [ SourceFile
      "kernel.cc"
      ( Text.unlines
          [ "// Generated by jitml. Do not check generated oneDNN source into git."
          , "#include <algorithm>"
          , "#include <cstddef>"
          , ""
          , "extern \"C\" void jitml_kernel(float *out, const float *input, std::size_t n) {"
          , "  for (std::size_t i = 0; i < n; ++i) {"
          , "    out[i] = input[i];"
          , "  }"
          , "}"
          , ""
          , "static const char *jitml_kernel_spec = " <> cString (kernelSpecPayload kernelSpec) <> ";"
          , "static const char *jitml_kernel_kind = " <> cString (kindText kind) <> ";"
          , "static const char *jitml_tuning_choice = " <> cString (unTuningChoice tuningChoice) <> ";"
          , "static const int jitml_fixed_reduction_block = 256;"
          ]
      )
  ]

cString :: Text.Text -> Text.Text
cString value =
  "\"" <> Text.concatMap escape value <> "\""

escape :: Char -> Text.Text
escape '"' = "\\\""
escape '\\' = "\\\\"
escape '\n' = "\\n"
escape char = Text.singleton char
