{-# LANGUAGE OverloadedStrings #-}

-- | Generated Linux-CPU source for the persistence-safe supervised-runtime
-- structural operations.  The source is materialised only in the JIT cache;
-- no native source artifact is checked into the repository.
module JitML.Codegen.RuntimeOperationsCpu
  ( renderRuntimeOperationsCpuSource
  , runtimeOperationsCpuKernelSpec
  )
where

import Data.Text (Text)
import Data.Text qualified as Text

import JitML.Cache.Key (KernelSpec (..))
import JitML.Codegen.SourceFile (SourceFile (..))

runtimeOperationsCpuKernelSpec :: KernelSpec
runtimeOperationsCpuKernelSpec =
  KernelSpec "supervised-runtime-structural-operations-v1"

renderRuntimeOperationsCpuSource :: [SourceFile]
renderRuntimeOperationsCpuSource =
  [SourceFile "kernel.cc" runtimeOperationsCpuSource]

runtimeOperationsCpuSource :: Text
runtimeOperationsCpuSource =
  Text.unlines
    [ "// Generated by jitml. Do not check generated Linux-CPU runtime source into git."
    , "#include <algorithm>"
    , "#include <cmath>"
    , "#include <cstddef>"
    , "#include <cstdint>"
    , "#include <limits>"
    , "#include <vector>"
    , ""
    , "namespace {"
    , "constexpr std::uint32_t JITML_RUNTIME_OPERATIONS_ABI = 1;"
    , "constexpr std::uint64_t JITML_RUNTIME_CAPABILITIES = 0xffULL;"
    , "enum Status : int {"
    , "  JITML_OK = 0,"
    , "  JITML_INVALID_DIMENSION = 1,"
    , "  JITML_NONFINITE_INPUT = 2,"
    , "  JITML_VALUE_OUT_OF_RANGE = 3,"
    , "  JITML_INVALID_SCALE = 4,"
    , "  JITML_INVALID_TRANSFORM = 5,"
    , "  JITML_NONFINITE_OUTPUT = 6,"
    , "  JITML_INVALID_INDEX = 7"
    , "};"
    , ""
    , "bool finite_buffer(const double *values, std::size_t count) {"
    , "  for (std::size_t i = 0; i < count; ++i) {"
    , "    if (!std::isfinite(values[i])) { return false; }"
    , "  }"
    , "  return true;"
    , "}"
    , ""
    , "bool finite_positive_buffer(const double *values, std::size_t count) {"
    , "  for (std::size_t i = 0; i < count; ++i) {"
    , "    if (!std::isfinite(values[i]) || values[i] <= 0.0) { return false; }"
    , "  }"
    , "  return true;"
    , "}"
    , "}  // namespace"
    , ""
    , "extern \"C\" std::uint32_t jitml_runtime_operations_abi_version(void) {"
    , "  return JITML_RUNTIME_OPERATIONS_ABI;"
    , "}"
    , ""
    , "extern \"C\" std::uint64_t jitml_runtime_operations_capabilities(void) {"
    , "  return JITML_RUNTIME_CAPABILITIES;"
    , "}"
    , ""
    , inputTransformSource
    , ""
    , outputTransformSource
    , ""
    , residualSource
    , ""
    , layerNormSource
    , ""
    , tokenMixSource
    , ""
    , patchSource
    , ""
    , attentionSource
    , ""
    , meanPoolSource
    ]

inputTransformSource :: Text
inputTransformSource =
  Text.unlines
    [ "extern \"C\" int jitml_runtime_input_transform("
    , "    double *output, const double *input, std::size_t count,"
    , "    std::uint32_t transform, const double *means, const double *scales,"
    , "    std::size_t stats_count) {"
    , "  if (count == 0) { return JITML_INVALID_DIMENSION; }"
    , "  if (!finite_buffer(input, count)) { return JITML_NONFINITE_INPUT; }"
    , "  if (transform == 0U) {"
    , "    for (std::size_t i = 0; i < count; ++i) { output[i] = input[i]; }"
    , "  } else if (transform == 1U) {"
    , "    for (std::size_t i = 0; i < count; ++i) {"
    , "      if (input[i] < 0.0 || input[i] > 1.0) { return JITML_VALUE_OUT_OF_RANGE; }"
    , "      output[i] = input[i];"
    , "    }"
    , "  } else if (transform == 2U) {"
    , "    if (stats_count != count) { return JITML_INVALID_DIMENSION; }"
    , "    if (!finite_buffer(means, count) || !finite_positive_buffer(scales, count)) {"
    , "      return JITML_INVALID_SCALE;"
    , "    }"
    , "    for (std::size_t i = 0; i < count; ++i) {"
    , "      output[i] = (input[i] - means[i]) / scales[i];"
    , "    }"
    , "  } else {"
    , "    return JITML_INVALID_TRANSFORM;"
    , "  }"
    , "  return finite_buffer(output, count) ? JITML_OK : JITML_NONFINITE_OUTPUT;"
    , "}"
    ]

outputTransformSource :: Text
outputTransformSource =
  Text.unlines
    [ "extern \"C\" int jitml_runtime_output_transform("
    , "    double *output, std::size_t output_count,"
    , "    const double *input, std::size_t input_count,"
    , "    std::uint32_t transform, const double *means, const double *scales,"
    , "    std::size_t stats_count) {"
    , "  if (output_count == 0 || input_count < output_count) { return JITML_INVALID_DIMENSION; }"
    , "  if (!finite_buffer(input, input_count)) { return JITML_NONFINITE_INPUT; }"
    , "  if (transform == 0U) {"
    , "    if (input_count != output_count) { return JITML_INVALID_DIMENSION; }"
    , "    for (std::size_t i = 0; i < output_count; ++i) { output[i] = input[i]; }"
    , "  } else if (transform == 1U) {"
    , "    for (std::size_t i = 0; i < output_count; ++i) { output[i] = input[i]; }"
    , "  } else if (transform == 2U) {"
    , "    if (input_count != output_count || stats_count != output_count) {"
    , "      return JITML_INVALID_DIMENSION;"
    , "    }"
    , "    if (!finite_buffer(means, output_count)"
    , "        || !finite_positive_buffer(scales, output_count)) {"
    , "      return JITML_INVALID_SCALE;"
    , "    }"
    , "    for (std::size_t i = 0; i < output_count; ++i) {"
    , "      output[i] = input[i] * scales[i] + means[i];"
    , "    }"
    , "  } else {"
    , "    return JITML_INVALID_TRANSFORM;"
    , "  }"
    , "  return finite_buffer(output, output_count) ? JITML_OK : JITML_NONFINITE_OUTPUT;"
    , "}"
    ]

residualSource :: Text
residualSource =
  Text.unlines
    [ "extern \"C\" int jitml_runtime_residual_add("
    , "    double *output, const double *input, const double *residual,"
    , "    std::size_t count, double scale) {"
    , "  if (count == 0) { return JITML_INVALID_DIMENSION; }"
    , "  if (!std::isfinite(scale) || scale <= 0.0) { return JITML_INVALID_SCALE; }"
    , "  if (!finite_buffer(input, count) || !finite_buffer(residual, count)) {"
    , "    return JITML_NONFINITE_INPUT;"
    , "  }"
    , "  for (std::size_t i = 0; i < count; ++i) {"
    , "    output[i] = input[i] + scale * residual[i];"
    , "  }"
    , "  return finite_buffer(output, count) ? JITML_OK : JITML_NONFINITE_OUTPUT;"
    , "}"
    ]

layerNormSource :: Text
layerNormSource =
  Text.unlines
    [ "extern \"C\" int jitml_runtime_layer_norm("
    , "    double *output, const double *input, std::size_t count) {"
    , "  if (count == 0) { return JITML_INVALID_DIMENSION; }"
    , "  if (!finite_buffer(input, count)) { return JITML_NONFINITE_INPUT; }"
    , "  double total = 0.0;"
    , "  for (std::size_t i = 0; i < count; ++i) { total += input[i]; }"
    , "  const double mean = total / static_cast<double>(count);"
    , "  double squared = 0.0;"
    , "  for (std::size_t i = 0; i < count; ++i) {"
    , "    const double centered = input[i] - mean;"
    , "    squared += centered * centered;"
    , "  }"
    , "  const double inverse_std ="
    , "      1.0 / std::sqrt(squared / static_cast<double>(count) + 1.0e-5);"
    , "  for (std::size_t i = 0; i < count; ++i) {"
    , "    output[i] = (input[i] - mean) * inverse_std;"
    , "  }"
    , "  return finite_buffer(output, count) ? JITML_OK : JITML_NONFINITE_OUTPUT;"
    , "}"
    ]

tokenMixSource :: Text
tokenMixSource =
  Text.unlines
    [ "extern \"C\" int jitml_runtime_token_mix_pack("
    , "    double *channels, const double *tokens,"
    , "    std::size_t token_count, std::size_t width) {"
    , "  if (token_count == 0 || width == 0) { return JITML_INVALID_DIMENSION; }"
    , "  const std::size_t count = token_count * width;"
    , "  if (!finite_buffer(tokens, count)) { return JITML_NONFINITE_INPUT; }"
    , "  for (std::size_t channel = 0; channel < width; ++channel) {"
    , "    for (std::size_t token = 0; token < token_count; ++token) {"
    , "      channels[channel * token_count + token] = tokens[token * width + channel];"
    , "    }"
    , "  }"
    , "  return JITML_OK;"
    , "}"
    , ""
    , "extern \"C\" int jitml_runtime_token_mix_merge("
    , "    double *output, const double *tokens, const double *mixed_channels,"
    , "    std::size_t token_count, std::size_t width) {"
    , "  if (token_count == 0 || width == 0) { return JITML_INVALID_DIMENSION; }"
    , "  const std::size_t count = token_count * width;"
    , "  if (!finite_buffer(tokens, count) || !finite_buffer(mixed_channels, count)) {"
    , "    return JITML_NONFINITE_INPUT;"
    , "  }"
    , "  for (std::size_t token = 0; token < token_count; ++token) {"
    , "    for (std::size_t channel = 0; channel < width; ++channel) {"
    , "      output[token * width + channel] ="
    , "          mixed_channels[channel * token_count + token];"
    , "    }"
    , "  }"
    , "  return finite_buffer(output, count) ? JITML_OK : JITML_NONFINITE_OUTPUT;"
    , "}"
    ]

patchSource :: Text
patchSource =
  Text.unlines
    [ "extern \"C\" int jitml_runtime_patch_extract("
    , "    double *output, std::size_t patch_count, std::size_t patch_width,"
    , "    const double *input, std::size_t input_count,"
    , "    const std::int64_t *indices, std::size_t index_count,"
    , "    std::size_t image_width, std::size_t image_height,"
    , "    std::size_t channels) {"
    , "  if (patch_count == 0 || patch_width <= 2 || image_width == 0"
    , "      || image_height == 0 || channels == 0) {"
    , "    return JITML_INVALID_DIMENSION;"
    , "  }"
    , "  const std::size_t value_width = patch_width - 2;"
    , "  if (index_count != patch_count * value_width"
    , "      || input_count != image_width * image_height * channels) {"
    , "    return JITML_INVALID_DIMENSION;"
    , "  }"
    , "  if (!finite_buffer(input, input_count)) { return JITML_NONFINITE_INPUT; }"
    , "  for (std::size_t patch = 0; patch < patch_count; ++patch) {"
    , "    const std::size_t base = patch * value_width;"
    , "    for (std::size_t i = 0; i < value_width; ++i) {"
    , "      const std::int64_t index = indices[base + i];"
    , "      if (index < 0 || static_cast<std::size_t>(index) >= input_count) {"
    , "        return JITML_INVALID_INDEX;"
    , "      }"
    , "      output[patch * patch_width + i] = input[static_cast<std::size_t>(index)];"
    , "    }"
    , "    const std::size_t first = static_cast<std::size_t>(indices[base]);"
    , "    const std::size_t pixel = first / channels;"
    , "    const std::size_t x = pixel % image_width;"
    , "    const std::size_t y = pixel / image_width;"
    , "    output[patch * patch_width + value_width] = image_width <= 1"
    , "        ? 0.0"
    , "        : (static_cast<double>(x) / static_cast<double>(image_width - 1)) * 2.0 - 1.0;"
    , "    output[patch * patch_width + value_width + 1] = image_height <= 1"
    , "        ? 0.0"
    , "        : (static_cast<double>(y) / static_cast<double>(image_height - 1)) * 2.0 - 1.0;"
    , "  }"
    , "  return finite_buffer(output, patch_count * patch_width)"
    , "      ? JITML_OK : JITML_NONFINITE_OUTPUT;"
    , "}"
    ]

attentionSource :: Text
attentionSource =
  Text.unlines
    [ "extern \"C\" int jitml_runtime_attention("
    , "    double *output, const double *tokens, const double *qkv,"
    , "    std::size_t token_count, std::size_t width) {"
    , "  if (token_count == 0 || width == 0) { return JITML_INVALID_DIMENSION; }"
    , "  const std::size_t token_values = token_count * width;"
    , "  const std::size_t qkv_values = token_count * 3 * width;"
    , "  if (!finite_buffer(tokens, token_values) || !finite_buffer(qkv, qkv_values)) {"
    , "    return JITML_NONFINITE_INPUT;"
    , "  }"
    , "  const double scale = 1.0 / std::sqrt(static_cast<double>(width));"
    , "  std::vector<double> scores(token_count, 0.0);"
    , "  std::vector<double> weights(token_count, 0.0);"
    , "  for (std::size_t query_token = 0; query_token < token_count; ++query_token) {"
    , "    double maximum = -std::numeric_limits<double>::infinity();"
    , "    for (std::size_t key_token = 0; key_token < token_count; ++key_token) {"
    , "      double dot = 0.0;"
    , "      for (std::size_t channel = 0; channel < width; ++channel) {"
    , "        dot += qkv[query_token * 3 * width + channel]"
    , "            * qkv[key_token * 3 * width + width + channel];"
    , "      }"
    , "      scores[key_token] = dot * scale;"
    , "      maximum = std::max(maximum, scores[key_token]);"
    , "    }"
    , "    double denominator = 0.0;"
    , "    for (std::size_t key_token = 0; key_token < token_count; ++key_token) {"
    , "      weights[key_token] = std::exp(scores[key_token] - maximum);"
    , "      denominator += weights[key_token];"
    , "    }"
    , "    if (!std::isfinite(denominator) || denominator <= 0.0) {"
    , "      return JITML_NONFINITE_OUTPUT;"
    , "    }"
    , "    for (std::size_t channel = 0; channel < width; ++channel) {"
    , "      double attended = 0.0;"
    , "      for (std::size_t value_token = 0; value_token < token_count; ++value_token) {"
    , "        attended += (weights[value_token] / denominator)"
    , "            * qkv[value_token * 3 * width + 2 * width + channel];"
    , "      }"
    , "      output[query_token * width + channel] = attended;"
    , "    }"
    , "  }"
    , "  return finite_buffer(output, token_values) ? JITML_OK : JITML_NONFINITE_OUTPUT;"
    , "}"
    ]

meanPoolSource :: Text
meanPoolSource =
  Text.unlines
    [ "extern \"C\" int jitml_runtime_mean_pool("
    , "    double *output, const double *tokens,"
    , "    std::size_t token_count, std::size_t width) {"
    , "  if (token_count == 0 || width == 0) { return JITML_INVALID_DIMENSION; }"
    , "  if (!finite_buffer(tokens, token_count * width)) { return JITML_NONFINITE_INPUT; }"
    , "  for (std::size_t channel = 0; channel < width; ++channel) {"
    , "    double total = 0.0;"
    , "    for (std::size_t token = 0; token < token_count; ++token) {"
    , "      total += tokens[token * width + channel];"
    , "    }"
    , "    output[channel] = total / static_cast<double>(token_count);"
    , "  }"
    , "  return finite_buffer(output, width) ? JITML_OK : JITML_NONFINITE_OUTPUT;"
    , "}"
    ]
