{-# LANGUAGE OverloadedStrings #-}

module JitML.Web.Contracts
  ( ApiEndpoint (..)
  , apiEndpoints
  , contractGeneratorName
  , renderPureScriptContracts
  )
where

import Data.Text (Text)
import Data.Text qualified as Text

import JitML.Substrate (renderSubstrate)
import JitML.Test.WorkflowMatrix qualified as WorkflowMatrix

data ApiEndpoint = ApiEndpoint
  { endpointName :: Text
  , endpointMethod :: Text
  , endpointPath :: Text
  }
  deriving stock (Eq, Show)

apiEndpoints :: [ApiEndpoint]
apiEndpoints =
  [ ApiEndpoint "RunCommand" "POST" "/api/runs/{runId}/command"
  , ApiEndpoint "InferenceRun" "POST" "/api/inference"
  , ApiEndpoint "GenericInference" "POST" "/api/inference/generic"
  , ApiEndpoint "UploadImage" "POST" "/api/images"
  , ApiEndpoint "CheckpointCompare" "POST" "/api/checkpoints/compare"
  , ApiEndpoint "Connect4Move" "POST" "/api/connect4/move"
  , ApiEndpoint "MetricsStream" "GET" "/api/ws"
  , ApiEndpoint "TrainingStream" "GET" "/api/ws/training"
  , ApiEndpoint "RlStream" "GET" "/api/ws/rl"
  , ApiEndpoint "TuneStream" "GET" "/api/ws/tune"
  , ApiEndpoint "InferenceStream" "GET" "/api/ws/inference"
  , ApiEndpoint "CheckpointList" "POST" "/api/checkpoints"
  , ApiEndpoint "WorkflowStream" "GET" "/api/ws/workflow"
  , ApiEndpoint "TranscriptReplay" "POST" "/api/transcripts/replay"
  ]

contractGeneratorName :: Text
contractGeneratorName =
  "local-purescript-bridge-compatible-renderer"

renderPureScriptContracts :: Text
renderPureScriptContracts =
  Text.unlines contractModuleLines

contractModuleLines :: [Text]
contractModuleLines =
  [ "module Generated.Contracts where"
  , ""
  , "import Prelude"
  , ""
  , "import Data.Array as Array"
  , "import Data.Either (Either(..))"
  , "import Data.Enum (fromEnum)"
  , "import Data.Foldable (all)"
  , "import Data.Int as Int"
  , "import Data.Maybe (Maybe(..), fromMaybe)"
  , "import Data.Number as Number"
  , "import Data.String as String"
  , "import Data.String.Pattern (Pattern(..))"
  , "import Data.Traversable (traverse)"
  , ""
  , "type Endpoint = { name :: String, method :: String, path :: String }"
  , ""
  , "type TunePlanBudget ="
  , "  { trials :: Int"
  , "  , parallelism :: Int"
  , "  , promotions :: Int"
  , "  , optimizerUpdatesPerTrial :: Int"
  , "  }"
  , ""
  , "type BrowserInferenceRequest ="
  , "  { panel :: String"
  , "  , modelId :: String"
  , "  , experimentHash :: String"
  , "  , input :: Array Number"
  , "  }"
  , ""
  , "type BrowserImageRequest ="
  , "  { panel :: String"
  , "  , datasetName :: String"
  , "  , experimentHash :: String"
  , "  , imageBase64 :: String"
  , "  , input :: Array Number"
  , "  }"
  , ""
  , "type BrowserGenericInferenceRequest ="
  , "  { panel :: String"
  , "  , experimentHash :: String"
  , "  , input :: Array Number"
  , "  }"
  , ""
  , "type BrowserCheckpointCompareRequest ="
  , "  { panel :: String"
  , "  , baselineExperimentHash :: String"
  , "  , candidateExperimentHash :: String"
  , "  , input :: Array Number"
  , "  }"
  , ""
  , "type BrowserAdversarialMoveRequest ="
  , "  { panel :: String"
  , "  , game :: String"
  , "  , experimentHash :: String"
  , "  , moves :: Array Int"
  , "  , humanIsPlayer :: Int"
  , "  , simulationsPerMove :: Int"
  , "  }"
  , ""
  , "type InferenceResult ="
  , "  { panel :: String"
  , "  , modelId :: String"
  , "  , checkpointSha :: String"
  , "  , topClass :: Int"
  , "  , confidence :: Number"
  , "  , latencyMs :: Number"
  , "  , probabilities :: Array Number"
  , "  , output :: Array Number"
  , "  , status :: String"
  , "  }"
  , ""
  , "type ImageInferenceResult ="
  , "  { panel :: String"
  , "  , datasetName :: String"
  , "  , checkpointSha :: String"
  , "  , topK :: Array Int"
  , "  , probabilities :: Array Number"
  , "  , preprocessingMs :: Number"
  , "  , inferenceMs :: Number"
  , "  , status :: String"
  , "  }"
  , ""
  , "type GenericInferenceResult ="
  , "  { panel :: String"
  , "  , experimentHash :: String"
  , "  , checkpointSha :: String"
  , "  , latencyMs :: Number"
  , "  , output :: Array Number"
  , "  , status :: String"
  , "  }"
  , ""
  , "type CheckpointCompareResult ="
  , "  { panel :: String"
  , "  , baselineCheckpointSha :: String"
  , "  , candidateCheckpointSha :: String"
  , "  , baselineOutput :: Array Number"
  , "  , candidateOutput :: Array Number"
  , "  , maxAbsDelta :: Number"
  , "  , meanAbsDelta :: Number"
  , "  , latencyMs :: Number"
  , "  , status :: String"
  , "  }"
  , ""
  , "type AdversarialMoveResult ="
  , "  { panel :: String"
  , "  , game :: String"
  , "  , chosenColumn :: Int"
  , "  , legalMoves :: Array Int"
  , "  , visitCounts :: Array Int"
  , "  , policyPriors :: Array Number"
  , "  , valueEstimate :: Number"
  , "  , gameOver :: Boolean"
  , "  , transcriptId :: String"
  , "  }"
  , ""
  , "type TrainingEventFrame ="
  , "  { panel :: String"
  , "  , experimentHash :: String"
  , "  , epoch :: Int"
  , "  , step :: Int"
  , "  , trainingLoss :: Number"
  , "  , validationLoss :: Number"
  , "  , throughput :: Number"
  , "  , device :: String"
  , "  , checkpointSha :: String"
  , "  , tensorboardUrl :: String"
  , "  , timestampNs :: String"
  , "  }"
  , ""
  , "type RlAnimationFrame ="
  , "  { panel :: String"
  , "  , experimentHash :: String"
  , "  , environment :: String"
  , "  , episodeIndex :: Int"
  , "  , stepIndex :: Int"
  , "  , reward :: Number"
  , "  , done :: Boolean"
  , "  , action :: Int"
  , "  , observation :: Array Number"
  , "  , actionProbabilities :: Array Number"
  , "  , observationHash :: String"
  , "  , replayCursor :: String"
  , "  , timestampNs :: String"
  , "  }"
  , ""
  , "type RlReplayFrame ="
  , "  { panel :: String"
  , "  , experimentHash :: String"
  , "  , replayId :: String"
  , "  , environment :: String"
  , "  , episodeIndex :: Int"
  , "  , stepIndex :: Int"
  , "  , action :: Int"
  , "  , reward :: Number"
  , "  , done :: Boolean"
  , "  , observation :: Array Number"
  , "  , nextObservation :: Array Number"
  , "  , policyVersion :: String"
  , "  , observationHash :: String"
  , "  , timestampNs :: String"
  , "  }"
  , ""
  , "type TuneTrialFrame ="
  , "  { panel :: String"
  , "  , sweepId :: String"
  , "  , trialIndex :: Int"
  , "  , trialSeed :: Int"
  , "  , objective :: Number"
  , "  , pruned :: Boolean"
  , "  , sampler :: String"
  , "  , scheduler :: String"
  , "  , pruner :: String"
  , "  , parametersJson :: String"
  , "  , checkpointSha :: String"
  , "  }"
  , ""
  , "type TuneSweepDoneFrame ="
  , "  { panel :: String"
  , "  , sweepId :: String"
  , "  , trialsCompleted :: Int"
  , "  , trialsPruned :: Int"
  , "  , bestObjective :: Number"
  , "  , promotedCheckpointSha :: String"
  , "  }"
  , ""
  , "type WorkflowCommandAck ="
  , "  { runId :: String"
  , "  , command :: String"
  , "  , status :: String"
  , "  }"
  , ""
  , "type WorkflowStatus ="
  , "  { panel :: String"
  , "  , runId :: String"
  , "  , status :: String"
  , "  , detail :: String"
  , "  }"
  , ""
  , "-- Sprint 11.10 — the Engine-decoded inference result (one discriminated"
  , "-- record over OutputDecoderKind). The panels render its fields directly; no"
  , "-- browser-side decode (argmax/softmax) happens."
  , "type DecodedInference ="
  , "  { kind :: String"
  , "  , topClass :: Int"
  , "  , confidence :: Number"
  , "  , probabilities :: Array Number"
  , "  , labels :: Array String"
  , "  , values :: Array Number"
  , "  , value :: Number"
  , "  , output :: Array Number"
  , "  }"
  , ""
  , "-- Sprint 11.10 — the Engine-computed checkpoint-compare frame (two"
  , "-- inferences + delta, all in the daemon)."
  , "type CompareFrame ="
  , "  { baselineExperimentHash :: String"
  , "  , candidateExperimentHash :: String"
  , "  , baselineOutput :: Array Number"
  , "  , candidateOutput :: Array Number"
  , "  , maxAbsDelta :: Number"
  , "  , meanAbsDelta :: Number"
  , "  }"
  , ""
  , "-- Sprint 11.10 — the Engine-computed adversarial-move frame (inference +"
  , "-- MCTS, all in the daemon)."
  , "type MoveFrame ="
  , "  { experimentHash :: String"
  , "  , game :: String"
  , "  , chosenColumn :: Int"
  , "  , legalMoves :: Array Int"
  , "  , visitCounts :: Array Int"
  , "  , policyPriors :: Array Number"
  , "  , valueEstimate :: Number"
  , "  , gameOver :: Boolean"
  , "  , transcriptId :: String"
  , "  }"
  , ""
  , "-- One product-row checkpoint manifest summary, parsed"
  , "-- from a tab-separated `checkpoint-summary:` line of the Engine's"
  , "-- `CheckpointList` frame."
  , "type CheckpointSummary ="
  , "  { ordinal :: Int"
  , "  , rowId :: String"
  , "  , planId :: String"
  , "  , experimentHash :: String"
  , "  , sha :: String"
  , "  , step :: Int"
  , "  , modelFamily :: String"
  , "  , tensorCount :: Int"
  , "  , eligibility :: String"
  , "  , completedBudget :: String"
  , "  , measuredResult :: String"
  , "  , tensorboardPrefix :: String"
  , "  }"
  , ""
  , "type ProductRowSelector ="
  , "  { ordinal :: Int"
  , "  , rowId :: String"
  , "  , planId :: String"
  , "  , experimentHash :: String"
  , "  , manifestSha :: String"
  , "  , family :: String"
  , "  , evidenceStatus :: String"
  , "  , evidenceReason :: String"
  , "  , demoPanel :: String"
  , "  }"
  , ""
  , "-- The Engine-listed product-row checkpoint catalogue, including per-row"
  , "-- selector state and inference-eligible manifests listed from MinIO."
  , "type CheckpointList ="
  , "  { kind :: String"
  , "  , callId :: String"
  , "  , panel :: String"
  , "  , publicationStatus :: String"
  , "  , runId :: String"
  , "  , substrate :: String"
  , "  , catalogueSha256 :: String"
  , "  , sourceJournalSha256 :: String"
  , "  , count :: Int"
  , "  , selectorState :: String"
  , "  , rowSelectors :: Array ProductRowSelector"
  , "  , checkpoints :: Array CheckpointSummary"
  , "  }"
  , ""
  ]
    <> modelMatrixLines
    <> [ ""
       , "-- Sprint 14.1 (Feature B) — a persisted adversarial-game transcript replayed"
       , "-- from the `jitml-transcripts` bucket (read back in the daemon)."
       , "type TranscriptReplay ="
       , "  { kind :: String"
       , "  , game :: String"
       , "  , experimentHash :: String"
       , "  , moves :: Array Int"
       , "  , analysis :: String"
       , "  }"
       , ""
       , "renderStartTrainingCommand :: String -> String -> Int -> Int -> Int -> String"
       , "renderStartTrainingCommand experimentHash dhallObjectKey seed epochs batchSize ="
       , "  String.joinWith \"\\n\""
       , "    [ \"kind: StartTraining\""
       , "    , \"experiment-hash: \" <> experimentHash"
       , "    , \"dhall-object-key: \" <> dhallObjectKey"
       , "    , \"substrate: live\""
       , "    , \"seed: \" <> show seed"
       , "    , \"epochs: \" <> show epochs"
       , "    , \"batch-size: \" <> show batchSize"
       , "    , \"plan-id: browser-unresolved\""
       , "    , \"resolved-plan: browser-unresolved\""
       , "    , \"training-examples: 2000\""
       , "    , \"evaluation-examples: 1000\""
       , "    , \"\""
       , "    ]"
       , ""
       , "renderStopTrainingCommand :: String -> Boolean -> String"
       , "renderStopTrainingCommand experimentHash drain ="
       , "  String.joinWith \"\\n\""
       , "    [ \"kind: StopTraining\""
       , "    , \"experiment-hash: \" <> experimentHash"
       , "    , \"drain: \" <> renderBoolFlag drain"
       , "    , \"\""
       , "    ]"
       , ""
       , "renderStartRlCommand :: String -> String -> String -> Int -> Int -> Int -> String"
       , "renderStartRlCommand experimentHash algorithm environment seed maxSteps evalEpisodes ="
       , "  String.joinWith \"\\n\""
       , "    [ \"kind: StartRLRun\""
       , "    , \"experiment-hash: \" <> experimentHash"
       , "    , \"algorithm: \" <> algorithm"
       , "    , \"environment: \" <> environment"
       , "    , \"substrate: live\""
       , "    , \"seed: \" <> show seed"
       , "    , \"max-steps: \" <> show maxSteps"
       , "    , \"eval-episodes: \" <> show evalEpisodes"
       , "    , \"\""
       , "    ]"
       , ""
       , "renderStopRlCommand :: String -> Boolean -> String"
       , "renderStopRlCommand experimentHash drain ="
       , "  String.joinWith \"\\n\""
       , "    [ \"kind: StopRLRun\""
       , "    , \"experiment-hash: \" <> experimentHash"
       , "    , \"drain: \" <> renderBoolFlag drain"
       , "    , \"\""
       , "    ]"
       , ""
       , "renderStartTuneCommand :: String -> String -> Int -> TunePlanBudget -> String -> String -> String -> String"
       , "renderStartTuneCommand experimentHash dhallObjectKey sweepSeed budget sampler scheduler pruner ="
       , "  String.joinWith \"\\n\""
       , "    [ \"kind: StartSweep\""
       , "    , \"experiment-hash: \" <> experimentHash"
       , "    , \"dhall-object-key: \" <> dhallObjectKey"
       , "    , \"substrate: live\""
       , "    , \"sweep-seed: \" <> show sweepSeed"
       , "    , \"trial-budget: \" <> show budget.trials"
       , "    , \"budget-per-trial: \" <> show budget.optimizerUpdatesPerTrial"
       , "    , \"sampler: \" <> sampler"
       , "    , \"scheduler: \" <> scheduler"
       , "    , \"pruner: \" <> pruner"
       , "    , \"parallelism: \" <> show budget.parallelism"
       , "    , \"promotions: \" <> show budget.promotions"
       , "    , \"plan-id: browser-unresolved\""
       , "    , \"resolved-plan: browser-unresolved\""
       , "    , \"\""
       , "    ]"
       , ""
       , "renderStopTuneCommand :: String -> String"
       , "renderStopTuneCommand experimentHash ="
       , "  String.joinWith \"\\n\""
       , "    [ \"kind: StopSweep\""
       , "    , \"experiment-hash: \" <> experimentHash"
       , "    , \"\""
       , "    ]"
       , ""
       , "renderBrowserInferenceRequest :: String -> String -> String -> Array Number -> String"
       , "renderBrowserInferenceRequest panel modelId experimentHash input ="
       , "  String.joinWith \"\\n\""
       , "    [ \"kind: BrowserInferenceRequest\""
       , "    , \"panel: \" <> panel"
       , "    , \"model-id: \" <> modelId"
       , "    , \"experiment-hash: \" <> experimentHash"
       , "    , \"input: \" <> renderNumberList input"
       , "    , \"\""
       , "    ]"
       , ""
       , "renderBrowserImageRequest :: String -> String -> String -> String -> Array Number -> String"
       , "renderBrowserImageRequest panel datasetName experimentHash imageBase64 input ="
       , "  String.joinWith \"\\n\""
       , "    [ \"kind: BrowserImageRequest\""
       , "    , \"panel: \" <> panel"
       , "    , \"dataset: \" <> datasetName"
       , "    , \"experiment-hash: \" <> experimentHash"
       , "    , \"image-base64: \" <> imageBase64"
       , "    , \"input: \" <> renderNumberList input"
       , "    , \"\""
       , "    ]"
       , ""
       , "renderBrowserGenericInferenceRequest :: String -> String -> Array Number -> String"
       , "renderBrowserGenericInferenceRequest panel experimentHash input ="
       , "  String.joinWith \"\\n\""
       , "    [ \"kind: BrowserGenericInferenceRequest\""
       , "    , \"panel: \" <> panel"
       , "    , \"experiment-hash: \" <> experimentHash"
       , "    , \"input: \" <> renderNumberList input"
       , "    , \"\""
       , "    ]"
       , ""
       , "renderBrowserCheckpointCompareRequest :: String -> String -> String -> Array Number -> String"
       , "renderBrowserCheckpointCompareRequest panel baselineExperimentHash candidateExperimentHash input ="
       , "  String.joinWith \"\\n\""
       , "    [ \"kind: BrowserCheckpointCompareRequest\""
       , "    , \"panel: \" <> panel"
       , "    , \"baseline-experiment-hash: \" <> baselineExperimentHash"
       , "    , \"candidate-experiment-hash: \" <> candidateExperimentHash"
       , "    , \"input: \" <> renderNumberList input"
       , "    , \"\""
       , "    ]"
       , ""
       , "renderBrowserAdversarialMoveRequest :: String -> String -> String -> Array Int -> Int -> Int -> String"
       , "renderBrowserAdversarialMoveRequest panel game experimentHash moves humanIsPlayer simulationsPerMove ="
       , "  String.joinWith \"\\n\""
       , "    [ \"kind: BrowserAdversarialMoveRequest\""
       , "    , \"panel: \" <> panel"
       , "    , \"game: \" <> game"
       , "    , \"experiment-hash: \" <> experimentHash"
       , "    , \"moves: \" <> renderIntList moves"
       , "    , \"human-is-player: \" <> show humanIsPlayer"
       , "    , \"simulations-per-move: \" <> show simulationsPerMove"
       , "    , \"\""
       , "    ]"
       , ""
       , "renderInferenceResult :: String -> String -> String -> Int -> Number -> Number -> Array Number -> Array Number -> String -> InferenceResult"
       , "renderInferenceResult panel modelId checkpointSha topClass confidence latencyMs probabilities output status ="
       , "  { panel"
       , "  , modelId"
       , "  , checkpointSha"
       , "  , topClass"
       , "  , confidence"
       , "  , latencyMs"
       , "  , probabilities"
       , "  , output"
       , "  , status"
       , "  }"
       , ""
       , "renderImageInferenceResult :: String -> String -> String -> Array Int -> Array Number -> Number -> Number -> String -> ImageInferenceResult"
       , "renderImageInferenceResult panel datasetName checkpointSha topK probabilities preprocessingMs inferenceMs status ="
       , "  { panel"
       , "  , datasetName"
       , "  , checkpointSha"
       , "  , topK"
       , "  , probabilities"
       , "  , preprocessingMs"
       , "  , inferenceMs"
       , "  , status"
       , "  }"
       , ""
       , "renderGenericInferenceResult :: String -> String -> String -> Number -> Array Number -> String -> GenericInferenceResult"
       , "renderGenericInferenceResult panel experimentHash checkpointSha latencyMs output status ="
       , "  { panel"
       , "  , experimentHash"
       , "  , checkpointSha"
       , "  , latencyMs"
       , "  , output"
       , "  , status"
       , "  }"
       , ""
       , "renderCheckpointCompareResult :: String -> String -> String -> Array Number -> Array Number -> Number -> Number -> Number -> String -> CheckpointCompareResult"
       , "renderCheckpointCompareResult panel baselineCheckpointSha candidateCheckpointSha baselineOutput candidateOutput maxAbsDelta meanAbsDelta latencyMs status ="
       , "  { panel"
       , "  , baselineCheckpointSha"
       , "  , candidateCheckpointSha"
       , "  , baselineOutput"
       , "  , candidateOutput"
       , "  , maxAbsDelta"
       , "  , meanAbsDelta"
       , "  , latencyMs"
       , "  , status"
       , "  }"
       , ""
       , "renderAdversarialMoveResult :: String -> String -> Int -> Array Int -> Array Int -> Array Number -> Number -> Boolean -> String -> AdversarialMoveResult"
       , "renderAdversarialMoveResult panel game chosenColumn legalMoves visitCounts policyPriors valueEstimate gameOver transcriptId ="
       , "  { panel"
       , "  , game"
       , "  , chosenColumn"
       , "  , legalMoves"
       , "  , visitCounts"
       , "  , policyPriors"
       , "  , valueEstimate"
       , "  , gameOver"
       , "  , transcriptId"
       , "  }"
       , ""
       , "renderTrainingEventFrame :: String -> Int -> Int -> Number -> Number -> Number -> String -> String -> String -> String -> TrainingEventFrame"
       , "renderTrainingEventFrame experimentHash epoch step trainingLoss validationLoss throughput device checkpointSha tensorboardUrl timestampNs ="
       , "  { panel: \"training-progress\""
       , "  , experimentHash"
       , "  , epoch"
       , "  , step"
       , "  , trainingLoss"
       , "  , validationLoss"
       , "  , throughput"
       , "  , device"
       , "  , checkpointSha"
       , "  , tensorboardUrl"
       , "  , timestampNs"
       , "  }"
       , ""
       , "renderRlAnimationFrame :: String -> String -> Int -> Int -> Number -> Boolean -> Int -> Array Number -> Array Number -> String -> String -> String -> RlAnimationFrame"
       , "renderRlAnimationFrame experimentHash environment episodeIndex stepIndex reward done action observation actionProbabilities observationHash replayCursor timestampNs ="
       , "  { panel: \"rl-trajectory\""
       , "  , experimentHash"
       , "  , environment"
       , "  , episodeIndex"
       , "  , stepIndex"
       , "  , reward"
       , "  , done"
       , "  , action"
       , "  , observation"
       , "  , actionProbabilities"
       , "  , observationHash"
       , "  , replayCursor"
       , "  , timestampNs"
       , "  }"
       , ""
       , "renderRlReplayFrame :: String -> String -> String -> Int -> Int -> Int -> Number -> Boolean -> Array Number -> Array Number -> String -> String -> String -> RlReplayFrame"
       , "renderRlReplayFrame experimentHash replayId environment episodeIndex stepIndex action reward done observation nextObservation policyVersion observationHash timestampNs ="
       , "  { panel: \"rl-trajectory\""
       , "  , experimentHash"
       , "  , replayId"
       , "  , environment"
       , "  , episodeIndex"
       , "  , stepIndex"
       , "  , action"
       , "  , reward"
       , "  , done"
       , "  , observation"
       , "  , nextObservation"
       , "  , policyVersion"
       , "  , observationHash"
       , "  , timestampNs"
       , "  }"
       , ""
       , "renderTuneTrialFrame :: String -> Int -> Int -> Number -> Boolean -> String -> String -> String -> String -> String -> TuneTrialFrame"
       , "renderTuneTrialFrame sweepId trialIndex trialSeed objective pruned sampler scheduler pruner parametersJson checkpointSha ="
       , "  { panel: \"hyperparameter-sweep\""
       , "  , sweepId"
       , "  , trialIndex"
       , "  , trialSeed"
       , "  , objective"
       , "  , pruned"
       , "  , sampler"
       , "  , scheduler"
       , "  , pruner"
       , "  , parametersJson"
       , "  , checkpointSha"
       , "  }"
       , ""
       , "renderTuneSweepDoneFrame :: String -> Int -> Int -> Number -> String -> TuneSweepDoneFrame"
       , "renderTuneSweepDoneFrame sweepId trialsCompleted trialsPruned bestObjective promotedCheckpointSha ="
       , "  { panel: \"hyperparameter-sweep\""
       , "  , sweepId"
       , "  , trialsCompleted"
       , "  , trialsPruned"
       , "  , bestObjective"
       , "  , promotedCheckpointSha"
       , "  }"
       , ""
       , "renderWorkflowCommandAck :: String -> String -> String -> WorkflowCommandAck"
       , "renderWorkflowCommandAck runId command status ="
       , "  { runId, command, status }"
       , ""
       , "renderWorkflowStatus :: String -> String -> String -> String -> WorkflowStatus"
       , "renderWorkflowStatus panel runId status detail ="
       , "  { panel, runId, status, detail }"
       , ""
       , "parseWorkflowCommandAck :: String -> Maybe WorkflowCommandAck"
       , "parseWorkflowCommandAck payload"
       , "  | fieldValue \"kind\" payload == Just \"WorkflowCommandAck\" ="
       , "      renderWorkflowCommandAck"
       , "        <$> fieldValue \"run-id\" payload"
       , "        <*> fieldValue \"command\" payload"
       , "        <*> fieldValue \"status\" payload"
       , "  | otherwise = Nothing"
       , ""
       , "parseWorkflowStatus :: String -> Maybe WorkflowStatus"
       , "parseWorkflowStatus payload"
       , "  | fieldValue \"kind\" payload == Just \"WorkflowStatus\" ="
       , "      renderWorkflowStatus"
       , "        <$> fieldValue \"panel\" payload"
       , "        <*> fieldValue \"run-id\" payload"
       , "        <*> fieldValue \"status\" payload"
       , "        <*> fieldValue \"detail\" payload"
       , "  | otherwise = Nothing"
       , ""
       , "parseInferenceResult :: String -> Maybe InferenceResult"
       , "parseInferenceResult payload"
       , "  | fieldValue \"kind\" payload == Just \"InferenceResult\" ="
       , "      renderInferenceResult"
       , "        <$> fieldValue \"panel\" payload"
       , "        <*> fieldValue \"model-id\" payload"
       , "        <*> fieldValue \"checkpoint-sha\" payload"
       , "        <*> intField \"top-class\" payload"
       , "        <*> numberField \"confidence\" payload"
       , "        <*> numberField \"latency-ms\" payload"
       , "        <*> numberListField \"probabilities\" payload"
       , "        <*> numberListField \"output\" payload"
       , "        <*> fieldValue \"status\" payload"
       , "  | otherwise = Nothing"
       , ""
       , "parseDecodedInference :: String -> Maybe DecodedInference"
       , "parseDecodedInference payload ="
       , "  case fieldValue \"decoded-kind\" payload of"
       , "    Nothing -> Nothing"
       , "    Just decodedKind -> Just"
       , "      { kind: decodedKind"
       , "      , topClass: fromMaybe 0 (intField \"decoded-top-class\" payload)"
       , "      , confidence: fromMaybe 0.0 (numberField \"decoded-confidence\" payload)"
       , "      , probabilities: fromMaybe [] (numberListField \"decoded-probabilities\" payload)"
       , "      , labels: fromMaybe [] (stringListField \"decoded-labels\" payload)"
       , "      , values: fromMaybe [] (numberListField \"decoded-values\" payload)"
       , "      , value: fromMaybe 0.0 (numberField \"decoded-value\" payload)"
       , "      , output: fromMaybe [] (numberListField \"decoded-output\" payload)"
       , "      }"
       , ""
       , "parseCompareFrame :: String -> Maybe CompareFrame"
       , "parseCompareFrame payload"
       , "  | fieldValue \"kind\" payload == Just \"CheckpointCompareResult\" ="
       , "      (\\baselineExperimentHash candidateExperimentHash baselineOutput candidateOutput maxAbsDelta meanAbsDelta -> { baselineExperimentHash, candidateExperimentHash, baselineOutput, candidateOutput, maxAbsDelta, meanAbsDelta })"
       , "        <$> fieldValue \"baseline-experiment-hash\" payload"
       , "        <*> fieldValue \"candidate-experiment-hash\" payload"
       , "        <*> numberListField \"baseline-output\" payload"
       , "        <*> numberListField \"candidate-output\" payload"
       , "        <*> numberField \"max-abs-delta\" payload"
       , "        <*> numberField \"mean-abs-delta\" payload"
       , "  | otherwise = Nothing"
       , ""
       , "parseMoveFrame :: String -> Maybe MoveFrame"
       , "parseMoveFrame payload"
       , "  | fieldValue \"kind\" payload == Just \"AdversarialMoveResult\" ="
       , "      (\\experimentHash game chosenColumn legalMoves visitCounts policyPriors valueEstimate gameOver transcriptId -> { experimentHash, game, chosenColumn, legalMoves, visitCounts, policyPriors, valueEstimate, gameOver, transcriptId })"
       , "        <$> fieldValue \"experiment-hash\" payload"
       , "        <*> fieldValue \"game\" payload"
       , "        <*> intField \"chosen-column\" payload"
       , "        <*> intListField \"legal-moves\" payload"
       , "        <*> intListField \"visit-counts\" payload"
       , "        <*> numberListField \"policy-priors\" payload"
       , "        <*> numberField \"value-estimate\" payload"
       , "        <*> Just (fieldValue \"game-over\" payload == Just \"true\")"
       , "        <*> fieldValue \"transcript-id\" payload"
       , "  | otherwise = Nothing"
       , ""
       , "parseCheckpointList :: String -> Either String CheckpointList"
       , "parseCheckpointList payload ="
       , "  case parseCheckpointListFields payload of"
       , "    Nothing -> Left \"malformed CheckpointList frame\""
       , "    Just response ->"
       , "      case checkpointListValidationError response of"
       , "        Just detail -> Left detail"
       , "        Nothing -> Right response"
       , ""
       , "parseCheckpointListFields :: String -> Maybe CheckpointList"
       , "parseCheckpointListFields payload"
       , "  | not (all validCheckpointFieldLine (checkpointFieldLines payload)) = Nothing"
       , "  | checkpointUniqueFieldValue \"kind\" payload == Just \"CheckpointList\" ="
       , "      ( \\callId panel publicationStatus runId substrate catalogueSha256 sourceJournalSha256 count selectorState rowSelectors checkpoints ->"
       , "          { kind: \"CheckpointList\", callId, panel, publicationStatus, runId, substrate, catalogueSha256, sourceJournalSha256, count, selectorState, rowSelectors, checkpoints }"
       , "      )"
       , "        <$> checkpointUniqueFieldValue \"call-id\" payload"
       , "        <*> checkpointUniqueFieldValue \"panel\" payload"
       , "        <*> checkpointUniqueFieldValue \"status\" payload"
       , "        <*> checkpointUniqueFieldValue \"run-id\" payload"
       , "        <*> checkpointUniqueFieldValue \"substrate\" payload"
       , "        <*> checkpointUniqueFieldValue \"catalogue-sha256\" payload"
       , "        <*> checkpointUniqueFieldValue \"source-journal-sha256\" payload"
       , "        <*> checkpointUniqueIntField \"count\" payload"
       , "        <*> checkpointUniqueFieldValue \"selector-state\" payload"
       , "        <*> traverse parseProductRowSelector (checkpointFieldValues \"row-selector\" payload)"
       , "        <*> traverse parseCheckpointSummary (checkpointFieldValues \"checkpoint-summary\" payload)"
       , "  | otherwise = Nothing"
       , ""
       , "checkpointFieldLines :: String -> Array String"
       , "checkpointFieldLines payload ="
       , "  Array.filter (_ /= \"\") (String.split (Pattern \"\\n\") payload)"
       , ""
       , "validCheckpointFieldLine :: String -> Boolean"
       , "validCheckpointFieldLine line ="
       , "  case Array.head (String.split (Pattern \": \") line) of"
       , "    Just key -> String.contains (Pattern \": \") line && Array.elem key checkpointFieldNames"
       , "    Nothing -> false"
       , ""
       , "checkpointFieldNames :: Array String"
       , "checkpointFieldNames ="
       , "  [ \"kind\""
       , "  , \"call-id\""
       , "  , \"panel\""
       , "  , \"status\""
       , "  , \"run-id\""
       , "  , \"substrate\""
       , "  , \"catalogue-sha256\""
       , "  , \"source-journal-sha256\""
       , "  , \"count\""
       , "  , \"selector-state\""
       , "  , \"row-selector\""
       , "  , \"checkpoint-summary\""
       , "  ]"
       , ""
       , "checkpointFieldValues :: String -> String -> Array String"
       , "checkpointFieldValues key payload ="
       , "  Array.mapMaybe"
       , "    (String.stripPrefix (Pattern (key <> \": \")))"
       , "    (String.split (Pattern \"\\n\") payload)"
       , ""
       , "checkpointUniqueFieldValue :: String -> String -> Maybe String"
       , "checkpointUniqueFieldValue key payload ="
       , "  case checkpointFieldValues key payload of"
       , "    [ value ] -> Just value"
       , "    _ -> Nothing"
       , ""
       , "checkpointUniqueIntField :: String -> String -> Maybe Int"
       , "checkpointUniqueIntField key payload ="
       , "  checkpointUniqueFieldValue key payload >>= Int.fromString"
       , ""
       , "parseProductRowSelector :: String -> Maybe ProductRowSelector"
       , "parseProductRowSelector raw ="
       , "  case String.split (Pattern \"\\t\") raw of"
       , "    [ ordinalRaw, rowId, planId, experimentHash, manifestSha, family, evidenceStatus, evidenceReason, demoPanel ] ->"
       , "      (\\ordinal -> { ordinal, rowId, planId, experimentHash, manifestSha, family, evidenceStatus, evidenceReason, demoPanel })"
       , "        <$> Int.fromString ordinalRaw"
       , "    _ -> Nothing"
       , ""
       , "parseCheckpointSummary :: String -> Maybe CheckpointSummary"
       , "parseCheckpointSummary raw ="
       , "  case String.split (Pattern \"\\t\") raw of"
       , "    [ ordinalRaw, rowId, planId, experimentHash, sha, stepRaw, modelFamily, tensorCountRaw, eligibility, completedBudget, measuredResult, tensorboardPrefix ] ->"
       , "      (\\ordinal step tensorCount -> { ordinal, rowId, planId, experimentHash, sha, step, modelFamily, tensorCount, eligibility, completedBudget, measuredResult, tensorboardPrefix })"
       , "        <$> Int.fromString ordinalRaw"
       , "        <*> Int.fromString stepRaw"
       , "        <*> Int.fromString tensorCountRaw"
       , "    _ -> Nothing"
       , ""
       , "checkpointListValidationError :: CheckpointList -> Maybe String"
       , "checkpointListValidationError response"
       , "  | response.panel /= \"checkpoint-browse\" = Just \"CheckpointList panel is not checkpoint-browse\""
       , "  | response.publicationStatus /= \"published\" = Just \"CheckpointList publication status is not published\""
       , "  | not (canonicalIdentity response.callId) = Just \"CheckpointList call-id is invalid\""
       , "  | not (canonicalIdentity response.runId) = Just \"CheckpointList run-id is invalid\""
       , "  | not (validSubstrate response.substrate) = Just \"CheckpointList substrate is invalid\""
       , "  | not (canonicalSha256 response.catalogueSha256) = Just \"CheckpointList catalogue SHA is invalid\""
       , "  | not (canonicalSha256 response.sourceJournalSha256) = Just \"CheckpointList source journal SHA is invalid\""
       , "  | response.count /= expectedProductRowCount response.substrate = Just \"CheckpointList count is not the canonical ProductRow denominator\""
       , "  | Array.length response.rowSelectors /= expectedProductRowCount response.substrate = Just \"CheckpointList selector coverage is partial\""
       , "  | Array.length response.checkpoints /= expectedProductRowCount response.substrate = Just \"CheckpointList summary coverage is partial\""
       , "  | map _.ordinal response.rowSelectors /= expectedProductOrdinals response.substrate = Just \"CheckpointList selector order is invalid\""
       , "  | map _.ordinal response.checkpoints /= expectedProductOrdinals response.substrate = Just \"CheckpointList summary order is invalid\""
       , "  | map _.rowId response.rowSelectors /= expectedProductRowIds response.substrate = Just \"CheckpointList selector rows differ from the canonical registry order\""
       , "  | map _.rowId response.checkpoints /= expectedProductRowIds response.substrate = Just \"CheckpointList summary rows differ from the canonical registry order\""
       , "  | map _.planId response.rowSelectors /= expectedProductPlanIds response.substrate = Just \"CheckpointList selector PlanIds differ from the canonical substrate registry\""
       , "  | map _.planId response.checkpoints /= expectedProductPlanIds response.substrate = Just \"CheckpointList summary PlanIds differ from the canonical substrate registry\""
       , "  | map _.experimentHash response.rowSelectors /= expectedProductExperiments response.substrate = Just \"CheckpointList selector experiments differ from the canonical registry\""
       , "  | map _.experimentHash response.checkpoints /= expectedProductExperiments response.substrate = Just \"CheckpointList summary experiments differ from the canonical registry\""
       , "  | map _.family response.rowSelectors /= expectedProductFamilies response.substrate = Just \"CheckpointList selector families differ from the canonical registry\""
       , "  | map _.modelFamily response.checkpoints /= expectedProductFamilies response.substrate = Just \"CheckpointList summary families differ from the canonical registry\""
       , "  | map _.demoPanel response.rowSelectors /= expectedProductDemoPanels response.substrate = Just \"CheckpointList demo panels differ from the canonical registry\""
       , "  | hasDuplicates (map (\\row -> row.rowId <> \"\\n\" <> row.planId) response.rowSelectors) = Just \"CheckpointList contains a duplicate rowId/PlanId selector\""
       , "  | hasDuplicates (map (\\row -> row.rowId <> \"\\n\" <> row.planId) response.checkpoints) = Just \"CheckpointList contains a duplicate rowId/PlanId summary\""
       , "  | not (all validProductRowSelector response.rowSelectors) = Just \"CheckpointList contains an invalid selector\""
       , "  | not (all validCheckpointSummary response.checkpoints) = Just \"CheckpointList contains an invalid summary\""
       , "  | not (all identity (Array.zipWith selectorMatchesSummary response.rowSelectors response.checkpoints)) = Just \"CheckpointList selectors and summaries are not an exact identity bijection\""
       , "  | not (all (\\row -> row.evidenceStatus == \"Passed\") response.rowSelectors) = Just \"CheckpointList contains non-Passed source evidence\""
       , "  | response.selectorState /= \"ready\" = Just \"CheckpointList complete Passed evidence is not ready\""
       , "  | otherwise = Nothing"
       , ""
       , "validProductRowSelector :: ProductRowSelector -> Boolean"
       , "validProductRowSelector row ="
       , "  canonicalIdentity row.rowId"
       , "    && canonicalSha256 row.planId"
       , "    && canonicalIdentity row.experimentHash"
       , "    && canonicalSha256 row.manifestSha"
       , "    && canonicalIdentity row.family"
       , "    && canonicalIdentity row.demoPanel"
       , "    && validEvidenceStatus row.evidenceStatus row.evidenceReason"
       , ""
       , "validCheckpointSummary :: CheckpointSummary -> Boolean"
       , "validCheckpointSummary row ="
       , "  canonicalIdentity row.rowId"
       , "    && canonicalSha256 row.planId"
       , "    && canonicalIdentity row.experimentHash"
       , "    && canonicalSha256 row.sha"
       , "    && row.step >= 0"
       , "    && canonicalIdentity row.modelFamily"
       , "    && row.tensorCount > 0"
       , "    && (row.eligibility == \"eligible\" || row.eligibility == \"unavailable\")"
       , "    && canonicalIdentity row.completedBudget"
       , "    && canonicalIdentity row.measuredResult"
       , "    && canonicalIdentity row.tensorboardPrefix"
       , ""
       , "selectorMatchesSummary :: ProductRowSelector -> CheckpointSummary -> Boolean"
       , "selectorMatchesSummary selector summary ="
       , "  selector.ordinal == summary.ordinal"
       , "    && selector.rowId == summary.rowId"
       , "    && selector.planId == summary.planId"
       , "    && selector.experimentHash == summary.experimentHash"
       , "    && selector.manifestSha == summary.sha"
       , "    && selector.family == summary.modelFamily"
       , "    && ((selector.evidenceStatus == \"Passed\") == (summary.eligibility == \"eligible\"))"
       , ""
       , "validEvidenceStatus :: String -> String -> Boolean"
       , "validEvidenceStatus status reason ="
       , "  case status of"
       , "    \"Passed\" -> reason == \"\""
       , "    \"Failed\" -> canonicalIdentity reason"
       , "    \"NotRun\" -> canonicalIdentity reason"
       , "    _ -> false"
       , ""
       , "validSubstrate :: String -> Boolean"
       , "validSubstrate value = value == \"linux-cpu\" || value == \"linux-cuda\" || value == \"apple-silicon\""
       , ""
       , "canonicalIdentity :: String -> Boolean"
       , "canonicalIdentity value ="
       , "  value /= \"\""
       , "    && Array.length (String.toCodePointArray value) <= 4096"
       , "    && String.trim value == value"
       , "    && all (not <<< isControlCodePoint) (String.toCodePointArray value)"
       , ""
       , "isControlCodePoint codePoint ="
       , "  let"
       , "    value = fromEnum codePoint"
       , "  in"
       , "    (value >= 0 && value <= 31) || (value >= 127 && value <= 159)"
       , ""
       , "canonicalSha256 :: String -> Boolean"
       , "canonicalSha256 value ="
       , "  String.length value == 64"
       , "    && all isLowerHex (String.toCodePointArray value)"
       , ""
       , "isLowerHex codePoint ="
       , "  let"
       , "    value = String.singleton codePoint"
       , "  in"
       , "    String.contains (Pattern value) \"0123456789abcdef\""
       , ""
       , "hasDuplicates :: Array String -> Boolean"
       , "hasDuplicates values = Array.length (Array.nub values) /= Array.length values"
       , ""
       , "expectedProductRowCount :: String -> Int"
       , "expectedProductRowCount substrate = Array.length (allModelMatrixRowsForSubstrate substrate)"
       , ""
       , "expectedProductOrdinals :: String -> Array Int"
       , "expectedProductOrdinals substrate = Array.range 0 (expectedProductRowCount substrate - 1)"
       , ""
       , "expectedProductRowIds :: String -> Array String"
       , "expectedProductRowIds substrate = map _.name (allModelMatrixRowsForSubstrate substrate)"
       , ""
       , "expectedProductPlanIds :: String -> Array String"
       , "expectedProductPlanIds substrate = map _.planId (allModelMatrixRowsForSubstrate substrate)"
       , ""
       , "expectedProductExperiments :: String -> Array String"
       , "expectedProductExperiments substrate = map _.experimentHash (allModelMatrixRowsForSubstrate substrate)"
       , ""
       , "expectedProductFamilies :: String -> Array String"
       , "expectedProductFamilies substrate ="
       , "  map (\\row -> if row.kind == \"her\" then \"rl\" else row.kind) (allModelMatrixRowsForSubstrate substrate)"
       , ""
       , "expectedProductDemoPanels :: String -> Array String"
       , "expectedProductDemoPanels substrate = map _.demoPanel (allModelMatrixRowsForSubstrate substrate)"
       , ""
       , "parseTranscriptReplay :: String -> Maybe TranscriptReplay"
       , "parseTranscriptReplay payload"
       , "  | fieldValue \"kind\" payload == Just \"TranscriptReplay\" ="
       , "      (\\game experimentHash moves analysis -> { kind: \"TranscriptReplay\", game, experimentHash, moves, analysis })"
       , "        <$> fieldValue \"game\" payload"
       , "        <*> fieldValue \"experiment-hash\" payload"
       , "        <*> intListField \"moves\" payload"
       , "        <*> Just (fromMaybe \"\" (fieldValue \"analysis\" payload))"
       , "  | otherwise = Nothing"
       , ""
       , "parseImageInferenceResult :: String -> Maybe ImageInferenceResult"
       , "parseImageInferenceResult payload"
       , "  | fieldValue \"kind\" payload == Just \"ImageInferenceResult\" ="
       , "      renderImageInferenceResult"
       , "        <$> fieldValue \"panel\" payload"
       , "        <*> fieldValue \"dataset\" payload"
       , "        <*> fieldValue \"checkpoint-sha\" payload"
       , "        <*> intListField \"top-k\" payload"
       , "        <*> numberListField \"probabilities\" payload"
       , "        <*> numberField \"preprocessing-ms\" payload"
       , "        <*> numberField \"inference-ms\" payload"
       , "        <*> fieldValue \"status\" payload"
       , "  | otherwise = Nothing"
       , ""
       , "parseGenericInferenceResult :: String -> Maybe GenericInferenceResult"
       , "parseGenericInferenceResult payload"
       , "  | fieldValue \"kind\" payload == Just \"GenericInferenceResult\" ="
       , "      renderGenericInferenceResult"
       , "        <$> fieldValue \"panel\" payload"
       , "        <*> fieldValue \"experiment-hash\" payload"
       , "        <*> fieldValue \"checkpoint-sha\" payload"
       , "        <*> numberField \"latency-ms\" payload"
       , "        <*> numberListField \"output\" payload"
       , "        <*> fieldValue \"status\" payload"
       , "  | otherwise = Nothing"
       , ""
       , "parseCheckpointCompareResult :: String -> Maybe CheckpointCompareResult"
       , "parseCheckpointCompareResult payload"
       , "  | fieldValue \"kind\" payload == Just \"CheckpointCompareResult\" ="
       , "      renderCheckpointCompareResult"
       , "        <$> fieldValue \"panel\" payload"
       , "        <*> fieldValue \"baseline-checkpoint-sha\" payload"
       , "        <*> fieldValue \"candidate-checkpoint-sha\" payload"
       , "        <*> numberListField \"baseline-output\" payload"
       , "        <*> numberListField \"candidate-output\" payload"
       , "        <*> numberField \"max-abs-delta\" payload"
       , "        <*> numberField \"mean-abs-delta\" payload"
       , "        <*> numberField \"latency-ms\" payload"
       , "        <*> fieldValue \"status\" payload"
       , "  | otherwise = Nothing"
       , ""
       , "parseAdversarialMoveResult :: String -> Maybe AdversarialMoveResult"
       , "parseAdversarialMoveResult payload"
       , "  | fieldValue \"kind\" payload == Just \"AdversarialMoveResult\" ="
       , "      renderAdversarialMoveResult"
       , "        <$> fieldValue \"panel\" payload"
       , "        <*> fieldValue \"game\" payload"
       , "        <*> intField \"chosen-column\" payload"
       , "        <*> intListField \"legal-moves\" payload"
       , "        <*> intListField \"visit-counts\" payload"
       , "        <*> numberListField \"policy-priors\" payload"
       , "        <*> numberField \"value-estimate\" payload"
       , "        <*> boolField \"game-over\" payload"
       , "        <*> fieldValue \"transcript-id\" payload"
       , "  | otherwise = Nothing"
       , ""
       , "parseTrainingEventFrame :: String -> Maybe TrainingEventFrame"
       , "parseTrainingEventFrame payload"
       , "  | fieldValue \"kind\" payload == Just \"TrainingEventFrame\" ="
       , "      renderTrainingEventFrame"
       , "        <$> fieldValue \"experiment-hash\" payload"
       , "        <*> intField \"epoch\" payload"
       , "        <*> intField \"step\" payload"
       , "        <*> numberField \"training-loss\" payload"
       , "        <*> numberField \"validation-loss\" payload"
       , "        <*> numberField \"throughput\" payload"
       , "        <*> fieldValue \"device\" payload"
       , "        <*> fieldValue \"checkpoint-sha\" payload"
       , "        <*> fieldValue \"tensorboard-url\" payload"
       , "        <*> fieldValue \"timestamp-ns\" payload"
       , "  | otherwise = Nothing"
       , ""
       , "parseRlAnimationFrame :: String -> Maybe RlAnimationFrame"
       , "parseRlAnimationFrame payload"
       , "  | fieldValue \"kind\" payload == Just \"RlAnimationFrame\" ="
       , "      renderRlAnimationFrame"
       , "        <$> fieldValue \"experiment-hash\" payload"
       , "        <*> fieldValue \"environment\" payload"
       , "        <*> intField \"episode\" payload"
       , "        <*> intField \"step\" payload"
       , "        <*> numberField \"reward\" payload"
       , "        <*> boolField \"done\" payload"
       , "        <*> intField \"action\" payload"
       , "        <*> numberListField \"observation\" payload"
       , "        <*> numberListField \"action-probabilities\" payload"
       , "        <*> fieldValue \"observation-hash\" payload"
       , "        <*> fieldValue \"replay-cursor\" payload"
       , "        <*> fieldValue \"timestamp-ns\" payload"
       , "  | otherwise = Nothing"
       , ""
       , "parseRlReplayFrame :: String -> Maybe RlReplayFrame"
       , "parseRlReplayFrame payload"
       , "  | fieldValue \"kind\" payload == Just \"RlReplayFrame\" ="
       , "      renderRlReplayFrame"
       , "        <$> fieldValue \"experiment-hash\" payload"
       , "        <*> fieldValue \"replay-id\" payload"
       , "        <*> fieldValue \"environment\" payload"
       , "        <*> intField \"episode\" payload"
       , "        <*> intField \"step\" payload"
       , "        <*> intField \"action\" payload"
       , "        <*> numberField \"reward\" payload"
       , "        <*> boolField \"done\" payload"
       , "        <*> numberListField \"observation\" payload"
       , "        <*> numberListField \"next-observation\" payload"
       , "        <*> fieldValue \"policy-version\" payload"
       , "        <*> fieldValue \"observation-hash\" payload"
       , "        <*> fieldValue \"timestamp-ns\" payload"
       , "  | otherwise = Nothing"
       , ""
       , "parseTuneTrialFrame :: String -> Maybe TuneTrialFrame"
       , "parseTuneTrialFrame payload"
       , "  | fieldValue \"kind\" payload == Just \"TuneTrialFrame\" ="
       , "      renderTuneTrialFrame"
       , "        <$> fieldValue \"sweep-id\" payload"
       , "        <*> intField \"trial-index\" payload"
       , "        <*> intField \"trial-seed\" payload"
       , "        <*> numberField \"objective\" payload"
       , "        <*> boolField \"pruned\" payload"
       , "        <*> fieldValue \"sampler\" payload"
       , "        <*> fieldValue \"scheduler\" payload"
       , "        <*> fieldValue \"pruner\" payload"
       , "        <*> fieldValue \"parameters-json\" payload"
       , "        <*> fieldValue \"checkpoint-sha\" payload"
       , "  | otherwise = Nothing"
       , ""
       , "parseTuneSweepDoneFrame :: String -> Maybe TuneSweepDoneFrame"
       , "parseTuneSweepDoneFrame payload"
       , "  | fieldValue \"kind\" payload == Just \"TuneSweepDoneFrame\" ="
       , "      renderTuneSweepDoneFrame"
       , "        <$> fieldValue \"sweep-id\" payload"
       , "        <*> intField \"trials-completed\" payload"
       , "        <*> intField \"trials-pruned\" payload"
       , "        <*> numberField \"best-objective\" payload"
       , "        <*> fieldValue \"promoted-checkpoint-sha\" payload"
       , "  | otherwise = Nothing"
       , ""
       , "fieldValue :: String -> String -> Maybe String"
       , "fieldValue key payload ="
       , "  Array.head (fieldValues key payload)"
       , ""
       , "uniqueFieldValue :: String -> String -> Maybe String"
       , "uniqueFieldValue key payload ="
       , "  case fieldValues key payload of"
       , "    [ value ] -> Just value"
       , "    _ -> Nothing"
       , ""
       , "uniqueIntField :: String -> String -> Maybe Int"
       , "uniqueIntField key payload ="
       , "  uniqueFieldValue key payload >>= Int.fromString"
       , ""
       , "fieldValues :: String -> String -> Array String"
       , "fieldValues key payload ="
       , "  Array.mapMaybe"
       , "    (String.stripPrefix (Pattern (key <> \": \")) <<< String.trim)"
       , "    (String.split (Pattern \"\\n\") payload)"
       , ""
       , "intField :: String -> String -> Maybe Int"
       , "intField key payload ="
       , "  fieldValue key payload >>= Int.fromString"
       , ""
       , "numberField :: String -> String -> Maybe Number"
       , "numberField key payload ="
       , "  fieldValue key payload >>= Number.fromString"
       , ""
       , "intListField :: String -> String -> Maybe (Array Int)"
       , "intListField key payload ="
       , "  case fieldValue key payload of"
       , "    Just raw | String.trim raw == \"\" -> Just []"
       , "    Just raw -> traverse (Int.fromString <<< String.trim) (String.split (Pattern \",\") raw)"
       , "    Nothing -> Nothing"
       , ""
       , "numberListField :: String -> String -> Maybe (Array Number)"
       , "numberListField key payload ="
       , "  case fieldValue key payload of"
       , "    Just raw | String.trim raw == \"\" -> Just []"
       , "    Just raw -> traverse (Number.fromString <<< String.trim) (String.split (Pattern \",\") raw)"
       , "    Nothing -> Nothing"
       , ""
       , "stringListField :: String -> String -> Maybe (Array String)"
       , "stringListField key payload ="
       , "  case fieldValue key payload of"
       , "    Just raw | String.trim raw == \"\" -> Just []"
       , "    Just raw -> Just (map String.trim (String.split (Pattern \",\") raw))"
       , "    Nothing -> Nothing"
       , ""
       , "boolField :: String -> String -> Maybe Boolean"
       , "boolField key payload ="
       , "  case fieldValue key payload of"
       , "    Just \"True\" -> Just true"
       , "    Just \"False\" -> Just false"
       , "    Just \"true\" -> Just true"
       , "    Just \"false\" -> Just false"
       , "    _ -> Nothing"
       , ""
       , "renderBoolFlag :: Boolean -> String"
       , "renderBoolFlag flag ="
       , "  if flag then \"True\" else \"False\""
       , ""
       , "renderIntList :: Array Int -> String"
       , "renderIntList values ="
       , "  String.joinWith \",\" (map show values)"
       , ""
       , "renderNumberList :: Array Number -> String"
       , "renderNumberList values ="
       , "  String.joinWith \",\" (map show values)"
       , ""
       , "endpoints :: Array Endpoint"
       , "endpoints ="
       , "  [ { name: \"RunCommand\", method: \"POST\", path: \"/api/runs/{runId}/command\" }"
       , "  , { name: \"InferenceRun\", method: \"POST\", path: \"/api/inference\" }"
       , "  , { name: \"GenericInference\", method: \"POST\", path: \"/api/inference/generic\" }"
       , "  , { name: \"UploadImage\", method: \"POST\", path: \"/api/images\" }"
       , "  , { name: \"CheckpointCompare\", method: \"POST\", path: \"/api/checkpoints/compare\" }"
       , "  , { name: \"Connect4Move\", method: \"POST\", path: \"/api/connect4/move\" }"
       , "  , { name: \"MetricsStream\", method: \"GET\", path: \"/api/ws\" }"
       , "  , { name: \"TrainingStream\", method: \"GET\", path: \"/api/ws/training\" }"
       , "  , { name: \"RlStream\", method: \"GET\", path: \"/api/ws/rl\" }"
       , "  , { name: \"TuneStream\", method: \"GET\", path: \"/api/ws/tune\" }"
       , "  , { name: \"InferenceStream\", method: \"GET\", path: \"/api/ws/inference\" }"
       , "  , { name: \"CheckpointList\", method: \"POST\", path: \"/api/checkpoints\" }"
       , "  , { name: \"WorkflowStream\", method: \"GET\", path: \"/api/ws/workflow\" }"
       , "  , { name: \"TranscriptReplay\", method: \"POST\", path: \"/api/transcripts/replay\" }"
       , "  ]"
       ]

modelMatrixLines :: [Text]
modelMatrixLines =
  [ "-- Phase 262 — browser-visible product matrix, generated through"
  , "-- `JitML.Test.WorkflowMatrix.modelCellMatrix` from"
  , "-- `JitML.Product.Matrix.allProductRows` so the PureScript app,"
  , "-- and Haskell tests consume one substrate-specific product registry."
  , "type ModelMatrixRow ="
  , "  { kind :: String"
  , "  , name :: String"
  , "  , planId :: String"
  , "  , substrate :: String"
  , "  , experimentHash :: String"
  , "  , e2eTest :: String"
  , "  , demoPanel :: String"
  , "  , budget :: String"
  , "  , command :: Array String"
  , "  , requiresTrainedArtifact :: Boolean"
  , "  }"
  , ""
  , "allModelMatrixRows :: Array ModelMatrixRow"
  , "allModelMatrixRows = allModelMatrixRowsForSubstrate \"linux-cpu\""
  , ""
  , "allModelMatrixRowsForSubstrate :: String -> Array ModelMatrixRow"
  , "allModelMatrixRowsForSubstrate substrate ="
  , "  Array.filter (\\row -> row.substrate == substrate) allSubstrateModelMatrixRows"
  , ""
  , "allSubstrateModelMatrixRows :: Array ModelMatrixRow"
  , "allSubstrateModelMatrixRows ="
  ]
    <> renderPureScriptArray (fmap (renderModelMatrixRow . fst) WorkflowMatrix.modelCellMatrix)

renderPureScriptArray :: [Text] -> [Text]
renderPureScriptArray [] = ["  []"]
renderPureScriptArray (row : rows) =
  ("  [ " <> row)
    : fmap ("  , " <>) rows
      <> ["  ]"]

renderModelMatrixRow :: WorkflowMatrix.ModelCell -> Text
renderModelMatrixRow cell =
  "{ kind: "
    <> psString (renderModelKind (WorkflowMatrix.modelCellKind cell))
    <> ", name: "
    <> psString (WorkflowMatrix.modelCellName cell)
    <> ", planId: "
    <> psString (WorkflowMatrix.modelCellPlanId cell)
    <> ", substrate: "
    <> psString (renderSubstrate (WorkflowMatrix.modelCellSubstrate cell))
    <> ", experimentHash: "
    <> psString (WorkflowMatrix.modelCellExperimentHash cell)
    <> ", e2eTest: "
    <> psString (WorkflowMatrix.modelCellE2eTest cell)
    <> ", demoPanel: "
    <> psString (WorkflowMatrix.modelCellDemoPanel cell)
    <> ", budget: "
    <> psString (WorkflowMatrix.modelCellBudget cell)
    <> ", command: "
    <> psStringArray (WorkflowMatrix.modelCellCommand cell)
    <> ", requiresTrainedArtifact: "
    <> psBool (WorkflowMatrix.modelCellRequiresTrainedArtifact cell)
    <> " }"

renderModelKind :: WorkflowMatrix.ModelKind -> Text
renderModelKind kind =
  case kind of
    WorkflowMatrix.SupervisedModelCell -> "supervised"
    WorkflowMatrix.RlAlgorithmModelCell -> "rl"
    WorkflowMatrix.HerModelCell -> "her"
    WorkflowMatrix.AlphaZeroGameModelCell -> "alphazero"
    WorkflowMatrix.TuningModelCell -> "tuning"

psStringArray :: [Text] -> Text
psStringArray values =
  "[ " <> Text.intercalate ", " (fmap psString values) <> " ]"

psBool :: Bool -> Text
psBool flag =
  if flag then "true" else "false"

psString :: Text -> Text
psString raw =
  "\"" <> Text.concatMap escapePureScriptString raw <> "\""

escapePureScriptString :: Char -> Text
escapePureScriptString ch =
  case ch of
    '"' -> "\\\""
    '\\' -> "\\\\"
    '\n' -> "\\n"
    '\r' -> "\\r"
    '\t' -> "\\t"
    _ -> Text.singleton ch
