{-# LANGUAGE OverloadedStrings #-}

module JitML.Web.Contracts
  ( ApiEndpoint (..)
  , apiEndpoints
  , contractGeneratorName
  , renderPureScriptContracts
  )
where

import Data.Text (Text)
import Data.Text qualified as Text

data ApiEndpoint = ApiEndpoint
  { endpointName :: Text
  , endpointMethod :: Text
  , endpointPath :: Text
  }
  deriving stock (Eq, Show)

apiEndpoints :: [ApiEndpoint]
apiEndpoints =
  [ ApiEndpoint "RunCommand" "POST" "/api/runs/{runId}/command"
  , ApiEndpoint "InferenceRun" "POST" "/api/inference"
  , ApiEndpoint "GenericInference" "POST" "/api/inference/generic"
  , ApiEndpoint "UploadImage" "POST" "/api/images"
  , ApiEndpoint "CheckpointCompare" "POST" "/api/checkpoints/compare"
  , ApiEndpoint "Connect4Move" "POST" "/api/connect4/move"
  , ApiEndpoint "MetricsStream" "GET" "/api/ws"
  , ApiEndpoint "TrainingStream" "GET" "/api/ws/training"
  , ApiEndpoint "RlStream" "GET" "/api/ws/rl"
  , ApiEndpoint "TuneStream" "GET" "/api/ws/tune"
  , ApiEndpoint "InferenceStream" "GET" "/api/ws/inference"
  ]

contractGeneratorName :: Text
contractGeneratorName =
  "local-purescript-bridge-compatible-renderer"

renderPureScriptContracts :: Text
renderPureScriptContracts =
  Text.unlines contractModuleLines

contractModuleLines :: [Text]
contractModuleLines =
  [ "module Generated.Contracts where"
  , ""
  , "import Prelude"
  , ""
  , "import Data.Array as Array"
  , "import Data.Int as Int"
  , "import Data.Maybe (Maybe(..), fromMaybe)"
  , "import Data.Number as Number"
  , "import Data.String as String"
  , "import Data.String.Pattern (Pattern(..))"
  , "import Data.Traversable (traverse)"
  , ""
  , "type Endpoint = { name :: String, method :: String, path :: String }"
  , ""
  , "type BrowserInferenceRequest ="
  , "  { panel :: String"
  , "  , modelId :: String"
  , "  , experimentHash :: String"
  , "  , input :: Array Number"
  , "  }"
  , ""
  , "type BrowserImageRequest ="
  , "  { panel :: String"
  , "  , datasetName :: String"
  , "  , experimentHash :: String"
  , "  , imageBase64 :: String"
  , "  , input :: Array Number"
  , "  }"
  , ""
  , "type BrowserGenericInferenceRequest ="
  , "  { panel :: String"
  , "  , experimentHash :: String"
  , "  , input :: Array Number"
  , "  }"
  , ""
  , "type BrowserCheckpointCompareRequest ="
  , "  { panel :: String"
  , "  , baselineExperimentHash :: String"
  , "  , candidateExperimentHash :: String"
  , "  , input :: Array Number"
  , "  }"
  , ""
  , "type BrowserAdversarialMoveRequest ="
  , "  { panel :: String"
  , "  , game :: String"
  , "  , experimentHash :: String"
  , "  , moves :: Array Int"
  , "  , humanIsPlayer :: Int"
  , "  , simulationsPerMove :: Int"
  , "  }"
  , ""
  , "type InferenceResult ="
  , "  { panel :: String"
  , "  , modelId :: String"
  , "  , checkpointSha :: String"
  , "  , topClass :: Int"
  , "  , confidence :: Number"
  , "  , latencyMs :: Number"
  , "  , probabilities :: Array Number"
  , "  , output :: Array Number"
  , "  , status :: String"
  , "  }"
  , ""
  , "type ImageInferenceResult ="
  , "  { panel :: String"
  , "  , datasetName :: String"
  , "  , checkpointSha :: String"
  , "  , topK :: Array Int"
  , "  , probabilities :: Array Number"
  , "  , preprocessingMs :: Number"
  , "  , inferenceMs :: Number"
  , "  , status :: String"
  , "  }"
  , ""
  , "type GenericInferenceResult ="
  , "  { panel :: String"
  , "  , experimentHash :: String"
  , "  , checkpointSha :: String"
  , "  , latencyMs :: Number"
  , "  , output :: Array Number"
  , "  , status :: String"
  , "  }"
  , ""
  , "type CheckpointCompareResult ="
  , "  { panel :: String"
  , "  , baselineCheckpointSha :: String"
  , "  , candidateCheckpointSha :: String"
  , "  , baselineOutput :: Array Number"
  , "  , candidateOutput :: Array Number"
  , "  , maxAbsDelta :: Number"
  , "  , meanAbsDelta :: Number"
  , "  , latencyMs :: Number"
  , "  , status :: String"
  , "  }"
  , ""
  , "type AdversarialMoveResult ="
  , "  { panel :: String"
  , "  , game :: String"
  , "  , chosenColumn :: Int"
  , "  , legalMoves :: Array Int"
  , "  , visitCounts :: Array Int"
  , "  , policyPriors :: Array Number"
  , "  , valueEstimate :: Number"
  , "  , gameOver :: Boolean"
  , "  , transcriptId :: String"
  , "  }"
  , ""
  , "type TrainingEventFrame ="
  , "  { panel :: String"
  , "  , experimentHash :: String"
  , "  , epoch :: Int"
  , "  , step :: Int"
  , "  , trainingLoss :: Number"
  , "  , validationLoss :: Number"
  , "  , throughput :: Number"
  , "  , device :: String"
  , "  , checkpointSha :: String"
  , "  , tensorboardUrl :: String"
  , "  , timestampNs :: String"
  , "  }"
  , ""
  , "type RlAnimationFrame ="
  , "  { panel :: String"
  , "  , experimentHash :: String"
  , "  , environment :: String"
  , "  , episodeIndex :: Int"
  , "  , stepIndex :: Int"
  , "  , reward :: Number"
  , "  , done :: Boolean"
  , "  , action :: Int"
  , "  , observation :: Array Number"
  , "  , actionProbabilities :: Array Number"
  , "  , observationHash :: String"
  , "  , replayCursor :: String"
  , "  , timestampNs :: String"
  , "  }"
  , ""
  , "type RlReplayFrame ="
  , "  { panel :: String"
  , "  , experimentHash :: String"
  , "  , replayId :: String"
  , "  , environment :: String"
  , "  , episodeIndex :: Int"
  , "  , stepIndex :: Int"
  , "  , action :: Int"
  , "  , reward :: Number"
  , "  , done :: Boolean"
  , "  , observation :: Array Number"
  , "  , nextObservation :: Array Number"
  , "  , policyVersion :: String"
  , "  , observationHash :: String"
  , "  , timestampNs :: String"
  , "  }"
  , ""
  , "type TuneTrialFrame ="
  , "  { panel :: String"
  , "  , sweepId :: String"
  , "  , trialIndex :: Int"
  , "  , trialSeed :: Int"
  , "  , objective :: Number"
  , "  , pruned :: Boolean"
  , "  , sampler :: String"
  , "  , scheduler :: String"
  , "  , pruner :: String"
  , "  , parametersJson :: String"
  , "  , checkpointSha :: String"
  , "  }"
  , ""
  , "type TuneSweepDoneFrame ="
  , "  { panel :: String"
  , "  , sweepId :: String"
  , "  , trialsCompleted :: Int"
  , "  , trialsPruned :: Int"
  , "  , bestObjective :: Number"
  , "  , promotedCheckpointSha :: String"
  , "  }"
  , ""
  , "type WorkflowCommandAck ="
  , "  { runId :: String"
  , "  , command :: String"
  , "  , status :: String"
  , "  }"
  , ""
  , "type WorkflowStatus ="
  , "  { panel :: String"
  , "  , runId :: String"
  , "  , status :: String"
  , "  , detail :: String"
  , "  }"
  , ""
  , "-- Sprint 11.10 — the Engine-decoded inference result (one discriminated"
  , "-- record over OutputDecoderKind). The panels render its fields directly; no"
  , "-- browser-side decode (argmax/softmax) happens."
  , "type DecodedInference ="
  , "  { kind :: String"
  , "  , topClass :: Int"
  , "  , confidence :: Number"
  , "  , probabilities :: Array Number"
  , "  , labels :: Array String"
  , "  , values :: Array Number"
  , "  , value :: Number"
  , "  , output :: Array Number"
  , "  }"
  , ""
  , "-- Sprint 11.10 — the Engine-computed checkpoint-compare frame (two"
  , "-- inferences + delta, all in the daemon)."
  , "type CompareFrame ="
  , "  { baselineExperimentHash :: String"
  , "  , candidateExperimentHash :: String"
  , "  , baselineOutput :: Array Number"
  , "  , candidateOutput :: Array Number"
  , "  , maxAbsDelta :: Number"
  , "  , meanAbsDelta :: Number"
  , "  }"
  , ""
  , "-- Sprint 11.10 — the Engine-computed adversarial-move frame (inference +"
  , "-- MCTS, all in the daemon)."
  , "type MoveFrame ="
  , "  { experimentHash :: String"
  , "  , game :: String"
  , "  , chosenColumn :: Int"
  , "  , legalMoves :: Array Int"
  , "  , visitCounts :: Array Int"
  , "  , policyPriors :: Array Number"
  , "  , valueEstimate :: Number"
  , "  , gameOver :: Boolean"
  , "  , transcriptId :: String"
  , "  }"
  , ""
  , "renderStartTrainingCommand :: String -> String -> Int -> Int -> Int -> String"
  , "renderStartTrainingCommand experimentHash dhallObjectKey seed epochs batchSize ="
  , "  String.joinWith \"\\n\""
  , "    [ \"kind: StartTraining\""
  , "    , \"experiment-hash: \" <> experimentHash"
  , "    , \"dhall-object-key: \" <> dhallObjectKey"
  , "    , \"substrate: live\""
  , "    , \"seed: \" <> show seed"
  , "    , \"epochs: \" <> show epochs"
  , "    , \"batch-size: \" <> show batchSize"
  , "    , \"\""
  , "    ]"
  , ""
  , "renderStopTrainingCommand :: String -> Boolean -> String"
  , "renderStopTrainingCommand experimentHash drain ="
  , "  String.joinWith \"\\n\""
  , "    [ \"kind: StopTraining\""
  , "    , \"experiment-hash: \" <> experimentHash"
  , "    , \"drain: \" <> renderBoolFlag drain"
  , "    , \"\""
  , "    ]"
  , ""
  , "renderStartRlCommand :: String -> String -> String -> Int -> Int -> Int -> String"
  , "renderStartRlCommand experimentHash algorithm environment seed maxSteps evalEpisodes ="
  , "  String.joinWith \"\\n\""
  , "    [ \"kind: StartRLRun\""
  , "    , \"experiment-hash: \" <> experimentHash"
  , "    , \"algorithm: \" <> algorithm"
  , "    , \"environment: \" <> environment"
  , "    , \"substrate: live\""
  , "    , \"seed: \" <> show seed"
  , "    , \"max-steps: \" <> show maxSteps"
  , "    , \"eval-episodes: \" <> show evalEpisodes"
  , "    , \"\""
  , "    ]"
  , ""
  , "renderStopRlCommand :: String -> Boolean -> String"
  , "renderStopRlCommand experimentHash drain ="
  , "  String.joinWith \"\\n\""
  , "    [ \"kind: StopRLRun\""
  , "    , \"experiment-hash: \" <> experimentHash"
  , "    , \"drain: \" <> renderBoolFlag drain"
  , "    , \"\""
  , "    ]"
  , ""
  , "renderStartTuneCommand :: String -> String -> Int -> Int -> Int -> String -> String -> String -> String"
  , "renderStartTuneCommand experimentHash dhallObjectKey sweepSeed trialBudget budgetPerTrial sampler scheduler pruner ="
  , "  String.joinWith \"\\n\""
  , "    [ \"kind: StartSweep\""
  , "    , \"experiment-hash: \" <> experimentHash"
  , "    , \"dhall-object-key: \" <> dhallObjectKey"
  , "    , \"substrate: live\""
  , "    , \"sweep-seed: \" <> show sweepSeed"
  , "    , \"trial-budget: \" <> show trialBudget"
  , "    , \"budget-per-trial: \" <> show budgetPerTrial"
  , "    , \"sampler: \" <> sampler"
  , "    , \"scheduler: \" <> scheduler"
  , "    , \"pruner: \" <> pruner"
  , "    , \"\""
  , "    ]"
  , ""
  , "renderStopTuneCommand :: String -> String"
  , "renderStopTuneCommand experimentHash ="
  , "  String.joinWith \"\\n\""
  , "    [ \"kind: StopSweep\""
  , "    , \"experiment-hash: \" <> experimentHash"
  , "    , \"\""
  , "    ]"
  , ""
  , "renderBrowserInferenceRequest :: String -> String -> String -> Array Number -> String"
  , "renderBrowserInferenceRequest panel modelId experimentHash input ="
  , "  String.joinWith \"\\n\""
  , "    [ \"kind: BrowserInferenceRequest\""
  , "    , \"panel: \" <> panel"
  , "    , \"model-id: \" <> modelId"
  , "    , \"experiment-hash: \" <> experimentHash"
  , "    , \"input: \" <> renderNumberList input"
  , "    , \"\""
  , "    ]"
  , ""
  , "renderBrowserImageRequest :: String -> String -> String -> String -> Array Number -> String"
  , "renderBrowserImageRequest panel datasetName experimentHash imageBase64 input ="
  , "  String.joinWith \"\\n\""
  , "    [ \"kind: BrowserImageRequest\""
  , "    , \"panel: \" <> panel"
  , "    , \"dataset: \" <> datasetName"
  , "    , \"experiment-hash: \" <> experimentHash"
  , "    , \"image-base64: \" <> imageBase64"
  , "    , \"input: \" <> renderNumberList input"
  , "    , \"\""
  , "    ]"
  , ""
  , "renderBrowserGenericInferenceRequest :: String -> String -> Array Number -> String"
  , "renderBrowserGenericInferenceRequest panel experimentHash input ="
  , "  String.joinWith \"\\n\""
  , "    [ \"kind: BrowserGenericInferenceRequest\""
  , "    , \"panel: \" <> panel"
  , "    , \"experiment-hash: \" <> experimentHash"
  , "    , \"input: \" <> renderNumberList input"
  , "    , \"\""
  , "    ]"
  , ""
  , "renderBrowserCheckpointCompareRequest :: String -> String -> String -> Array Number -> String"
  , "renderBrowserCheckpointCompareRequest panel baselineExperimentHash candidateExperimentHash input ="
  , "  String.joinWith \"\\n\""
  , "    [ \"kind: BrowserCheckpointCompareRequest\""
  , "    , \"panel: \" <> panel"
  , "    , \"baseline-experiment-hash: \" <> baselineExperimentHash"
  , "    , \"candidate-experiment-hash: \" <> candidateExperimentHash"
  , "    , \"input: \" <> renderNumberList input"
  , "    , \"\""
  , "    ]"
  , ""
  , "renderBrowserAdversarialMoveRequest :: String -> String -> String -> Array Int -> Int -> Int -> String"
  , "renderBrowserAdversarialMoveRequest panel game experimentHash moves humanIsPlayer simulationsPerMove ="
  , "  String.joinWith \"\\n\""
  , "    [ \"kind: BrowserAdversarialMoveRequest\""
  , "    , \"panel: \" <> panel"
  , "    , \"game: \" <> game"
  , "    , \"experiment-hash: \" <> experimentHash"
  , "    , \"moves: \" <> renderIntList moves"
  , "    , \"human-is-player: \" <> show humanIsPlayer"
  , "    , \"simulations-per-move: \" <> show simulationsPerMove"
  , "    , \"\""
  , "    ]"
  , ""
  , "renderInferenceResult :: String -> String -> String -> Int -> Number -> Number -> Array Number -> Array Number -> String -> InferenceResult"
  , "renderInferenceResult panel modelId checkpointSha topClass confidence latencyMs probabilities output status ="
  , "  { panel"
  , "  , modelId"
  , "  , checkpointSha"
  , "  , topClass"
  , "  , confidence"
  , "  , latencyMs"
  , "  , probabilities"
  , "  , output"
  , "  , status"
  , "  }"
  , ""
  , "renderImageInferenceResult :: String -> String -> String -> Array Int -> Array Number -> Number -> Number -> String -> ImageInferenceResult"
  , "renderImageInferenceResult panel datasetName checkpointSha topK probabilities preprocessingMs inferenceMs status ="
  , "  { panel"
  , "  , datasetName"
  , "  , checkpointSha"
  , "  , topK"
  , "  , probabilities"
  , "  , preprocessingMs"
  , "  , inferenceMs"
  , "  , status"
  , "  }"
  , ""
  , "renderGenericInferenceResult :: String -> String -> String -> Number -> Array Number -> String -> GenericInferenceResult"
  , "renderGenericInferenceResult panel experimentHash checkpointSha latencyMs output status ="
  , "  { panel"
  , "  , experimentHash"
  , "  , checkpointSha"
  , "  , latencyMs"
  , "  , output"
  , "  , status"
  , "  }"
  , ""
  , "renderCheckpointCompareResult :: String -> String -> String -> Array Number -> Array Number -> Number -> Number -> Number -> String -> CheckpointCompareResult"
  , "renderCheckpointCompareResult panel baselineCheckpointSha candidateCheckpointSha baselineOutput candidateOutput maxAbsDelta meanAbsDelta latencyMs status ="
  , "  { panel"
  , "  , baselineCheckpointSha"
  , "  , candidateCheckpointSha"
  , "  , baselineOutput"
  , "  , candidateOutput"
  , "  , maxAbsDelta"
  , "  , meanAbsDelta"
  , "  , latencyMs"
  , "  , status"
  , "  }"
  , ""
  , "renderAdversarialMoveResult :: String -> String -> Int -> Array Int -> Array Int -> Array Number -> Number -> Boolean -> String -> AdversarialMoveResult"
  , "renderAdversarialMoveResult panel game chosenColumn legalMoves visitCounts policyPriors valueEstimate gameOver transcriptId ="
  , "  { panel"
  , "  , game"
  , "  , chosenColumn"
  , "  , legalMoves"
  , "  , visitCounts"
  , "  , policyPriors"
  , "  , valueEstimate"
  , "  , gameOver"
  , "  , transcriptId"
  , "  }"
  , ""
  , "renderTrainingEventFrame :: String -> Int -> Int -> Number -> Number -> Number -> String -> String -> String -> String -> TrainingEventFrame"
  , "renderTrainingEventFrame experimentHash epoch step trainingLoss validationLoss throughput device checkpointSha tensorboardUrl timestampNs ="
  , "  { panel: \"training-progress\""
  , "  , experimentHash"
  , "  , epoch"
  , "  , step"
  , "  , trainingLoss"
  , "  , validationLoss"
  , "  , throughput"
  , "  , device"
  , "  , checkpointSha"
  , "  , tensorboardUrl"
  , "  , timestampNs"
  , "  }"
  , ""
  , "renderRlAnimationFrame :: String -> String -> Int -> Int -> Number -> Boolean -> Int -> Array Number -> Array Number -> String -> String -> String -> RlAnimationFrame"
  , "renderRlAnimationFrame experimentHash environment episodeIndex stepIndex reward done action observation actionProbabilities observationHash replayCursor timestampNs ="
  , "  { panel: \"rl-trajectory\""
  , "  , experimentHash"
  , "  , environment"
  , "  , episodeIndex"
  , "  , stepIndex"
  , "  , reward"
  , "  , done"
  , "  , action"
  , "  , observation"
  , "  , actionProbabilities"
  , "  , observationHash"
  , "  , replayCursor"
  , "  , timestampNs"
  , "  }"
  , ""
  , "renderRlReplayFrame :: String -> String -> String -> Int -> Int -> Int -> Number -> Boolean -> Array Number -> Array Number -> String -> String -> String -> RlReplayFrame"
  , "renderRlReplayFrame experimentHash replayId environment episodeIndex stepIndex action reward done observation nextObservation policyVersion observationHash timestampNs ="
  , "  { panel: \"rl-trajectory\""
  , "  , experimentHash"
  , "  , replayId"
  , "  , environment"
  , "  , episodeIndex"
  , "  , stepIndex"
  , "  , action"
  , "  , reward"
  , "  , done"
  , "  , observation"
  , "  , nextObservation"
  , "  , policyVersion"
  , "  , observationHash"
  , "  , timestampNs"
  , "  }"
  , ""
  , "renderTuneTrialFrame :: String -> Int -> Int -> Number -> Boolean -> String -> String -> String -> String -> String -> TuneTrialFrame"
  , "renderTuneTrialFrame sweepId trialIndex trialSeed objective pruned sampler scheduler pruner parametersJson checkpointSha ="
  , "  { panel: \"hyperparameter-sweep\""
  , "  , sweepId"
  , "  , trialIndex"
  , "  , trialSeed"
  , "  , objective"
  , "  , pruned"
  , "  , sampler"
  , "  , scheduler"
  , "  , pruner"
  , "  , parametersJson"
  , "  , checkpointSha"
  , "  }"
  , ""
  , "renderTuneSweepDoneFrame :: String -> Int -> Int -> Number -> String -> TuneSweepDoneFrame"
  , "renderTuneSweepDoneFrame sweepId trialsCompleted trialsPruned bestObjective promotedCheckpointSha ="
  , "  { panel: \"hyperparameter-sweep\""
  , "  , sweepId"
  , "  , trialsCompleted"
  , "  , trialsPruned"
  , "  , bestObjective"
  , "  , promotedCheckpointSha"
  , "  }"
  , ""
  , "renderWorkflowCommandAck :: String -> String -> String -> WorkflowCommandAck"
  , "renderWorkflowCommandAck runId command status ="
  , "  { runId, command, status }"
  , ""
  , "renderWorkflowStatus :: String -> String -> String -> String -> WorkflowStatus"
  , "renderWorkflowStatus panel runId status detail ="
  , "  { panel, runId, status, detail }"
  , ""
  , "parseWorkflowCommandAck :: String -> Maybe WorkflowCommandAck"
  , "parseWorkflowCommandAck payload"
  , "  | fieldValue \"kind\" payload == Just \"WorkflowCommandAck\" ="
  , "      renderWorkflowCommandAck"
  , "        <$> fieldValue \"run-id\" payload"
  , "        <*> fieldValue \"command\" payload"
  , "        <*> fieldValue \"status\" payload"
  , "  | otherwise = Nothing"
  , ""
  , "parseWorkflowStatus :: String -> Maybe WorkflowStatus"
  , "parseWorkflowStatus payload"
  , "  | fieldValue \"kind\" payload == Just \"WorkflowStatus\" ="
  , "      renderWorkflowStatus"
  , "        <$> fieldValue \"panel\" payload"
  , "        <*> fieldValue \"run-id\" payload"
  , "        <*> fieldValue \"status\" payload"
  , "        <*> fieldValue \"detail\" payload"
  , "  | otherwise = Nothing"
  , ""
  , "parseInferenceResult :: String -> Maybe InferenceResult"
  , "parseInferenceResult payload"
  , "  | fieldValue \"kind\" payload == Just \"InferenceResult\" ="
  , "      renderInferenceResult"
  , "        <$> fieldValue \"panel\" payload"
  , "        <*> fieldValue \"model-id\" payload"
  , "        <*> fieldValue \"checkpoint-sha\" payload"
  , "        <*> intField \"top-class\" payload"
  , "        <*> numberField \"confidence\" payload"
  , "        <*> numberField \"latency-ms\" payload"
  , "        <*> numberListField \"probabilities\" payload"
  , "        <*> numberListField \"output\" payload"
  , "        <*> fieldValue \"status\" payload"
  , "  | otherwise = Nothing"
  , ""
  , "parseDecodedInference :: String -> Maybe DecodedInference"
  , "parseDecodedInference payload ="
  , "  case fieldValue \"decoded-kind\" payload of"
  , "    Nothing -> Nothing"
  , "    Just decodedKind -> Just"
  , "      { kind: decodedKind"
  , "      , topClass: fromMaybe 0 (intField \"decoded-top-class\" payload)"
  , "      , confidence: fromMaybe 0.0 (numberField \"decoded-confidence\" payload)"
  , "      , probabilities: fromMaybe [] (numberListField \"decoded-probabilities\" payload)"
  , "      , labels: fromMaybe [] (stringListField \"decoded-labels\" payload)"
  , "      , values: fromMaybe [] (numberListField \"decoded-values\" payload)"
  , "      , value: fromMaybe 0.0 (numberField \"decoded-value\" payload)"
  , "      , output: fromMaybe [] (numberListField \"decoded-output\" payload)"
  , "      }"
  , ""
  , "parseCompareFrame :: String -> Maybe CompareFrame"
  , "parseCompareFrame payload"
  , "  | fieldValue \"kind\" payload == Just \"CheckpointCompareResult\" ="
  , "      (\\baselineExperimentHash candidateExperimentHash baselineOutput candidateOutput maxAbsDelta meanAbsDelta -> { baselineExperimentHash, candidateExperimentHash, baselineOutput, candidateOutput, maxAbsDelta, meanAbsDelta })"
  , "        <$> fieldValue \"baseline-experiment-hash\" payload"
  , "        <*> fieldValue \"candidate-experiment-hash\" payload"
  , "        <*> numberListField \"baseline-output\" payload"
  , "        <*> numberListField \"candidate-output\" payload"
  , "        <*> numberField \"max-abs-delta\" payload"
  , "        <*> numberField \"mean-abs-delta\" payload"
  , "  | otherwise = Nothing"
  , ""
  , "parseMoveFrame :: String -> Maybe MoveFrame"
  , "parseMoveFrame payload"
  , "  | fieldValue \"kind\" payload == Just \"AdversarialMoveResult\" ="
  , "      (\\experimentHash game chosenColumn legalMoves visitCounts policyPriors valueEstimate gameOver transcriptId -> { experimentHash, game, chosenColumn, legalMoves, visitCounts, policyPriors, valueEstimate, gameOver, transcriptId })"
  , "        <$> fieldValue \"experiment-hash\" payload"
  , "        <*> fieldValue \"game\" payload"
  , "        <*> intField \"chosen-column\" payload"
  , "        <*> intListField \"legal-moves\" payload"
  , "        <*> intListField \"visit-counts\" payload"
  , "        <*> numberListField \"policy-priors\" payload"
  , "        <*> numberField \"value-estimate\" payload"
  , "        <*> Just (fieldValue \"game-over\" payload == Just \"true\")"
  , "        <*> fieldValue \"transcript-id\" payload"
  , "  | otherwise = Nothing"
  , ""
  , "parseImageInferenceResult :: String -> Maybe ImageInferenceResult"
  , "parseImageInferenceResult payload"
  , "  | fieldValue \"kind\" payload == Just \"ImageInferenceResult\" ="
  , "      renderImageInferenceResult"
  , "        <$> fieldValue \"panel\" payload"
  , "        <*> fieldValue \"dataset\" payload"
  , "        <*> fieldValue \"checkpoint-sha\" payload"
  , "        <*> intListField \"top-k\" payload"
  , "        <*> numberListField \"probabilities\" payload"
  , "        <*> numberField \"preprocessing-ms\" payload"
  , "        <*> numberField \"inference-ms\" payload"
  , "        <*> fieldValue \"status\" payload"
  , "  | otherwise = Nothing"
  , ""
  , "parseGenericInferenceResult :: String -> Maybe GenericInferenceResult"
  , "parseGenericInferenceResult payload"
  , "  | fieldValue \"kind\" payload == Just \"GenericInferenceResult\" ="
  , "      renderGenericInferenceResult"
  , "        <$> fieldValue \"panel\" payload"
  , "        <*> fieldValue \"experiment-hash\" payload"
  , "        <*> fieldValue \"checkpoint-sha\" payload"
  , "        <*> numberField \"latency-ms\" payload"
  , "        <*> numberListField \"output\" payload"
  , "        <*> fieldValue \"status\" payload"
  , "  | otherwise = Nothing"
  , ""
  , "parseCheckpointCompareResult :: String -> Maybe CheckpointCompareResult"
  , "parseCheckpointCompareResult payload"
  , "  | fieldValue \"kind\" payload == Just \"CheckpointCompareResult\" ="
  , "      renderCheckpointCompareResult"
  , "        <$> fieldValue \"panel\" payload"
  , "        <*> fieldValue \"baseline-checkpoint-sha\" payload"
  , "        <*> fieldValue \"candidate-checkpoint-sha\" payload"
  , "        <*> numberListField \"baseline-output\" payload"
  , "        <*> numberListField \"candidate-output\" payload"
  , "        <*> numberField \"max-abs-delta\" payload"
  , "        <*> numberField \"mean-abs-delta\" payload"
  , "        <*> numberField \"latency-ms\" payload"
  , "        <*> fieldValue \"status\" payload"
  , "  | otherwise = Nothing"
  , ""
  , "parseAdversarialMoveResult :: String -> Maybe AdversarialMoveResult"
  , "parseAdversarialMoveResult payload"
  , "  | fieldValue \"kind\" payload == Just \"AdversarialMoveResult\" ="
  , "      renderAdversarialMoveResult"
  , "        <$> fieldValue \"panel\" payload"
  , "        <*> fieldValue \"game\" payload"
  , "        <*> intField \"chosen-column\" payload"
  , "        <*> intListField \"legal-moves\" payload"
  , "        <*> intListField \"visit-counts\" payload"
  , "        <*> numberListField \"policy-priors\" payload"
  , "        <*> numberField \"value-estimate\" payload"
  , "        <*> boolField \"game-over\" payload"
  , "        <*> fieldValue \"transcript-id\" payload"
  , "  | otherwise = Nothing"
  , ""
  , "parseTrainingEventFrame :: String -> Maybe TrainingEventFrame"
  , "parseTrainingEventFrame payload"
  , "  | fieldValue \"kind\" payload == Just \"TrainingEventFrame\" ="
  , "      renderTrainingEventFrame"
  , "        <$> fieldValue \"experiment-hash\" payload"
  , "        <*> intField \"epoch\" payload"
  , "        <*> intField \"step\" payload"
  , "        <*> numberField \"training-loss\" payload"
  , "        <*> numberField \"validation-loss\" payload"
  , "        <*> numberField \"throughput\" payload"
  , "        <*> fieldValue \"device\" payload"
  , "        <*> fieldValue \"checkpoint-sha\" payload"
  , "        <*> fieldValue \"tensorboard-url\" payload"
  , "        <*> fieldValue \"timestamp-ns\" payload"
  , "  | otherwise = Nothing"
  , ""
  , "parseRlAnimationFrame :: String -> Maybe RlAnimationFrame"
  , "parseRlAnimationFrame payload"
  , "  | fieldValue \"kind\" payload == Just \"RlAnimationFrame\" ="
  , "      renderRlAnimationFrame"
  , "        <$> fieldValue \"experiment-hash\" payload"
  , "        <*> fieldValue \"environment\" payload"
  , "        <*> intField \"episode\" payload"
  , "        <*> intField \"step\" payload"
  , "        <*> numberField \"reward\" payload"
  , "        <*> boolField \"done\" payload"
  , "        <*> intField \"action\" payload"
  , "        <*> numberListField \"observation\" payload"
  , "        <*> numberListField \"action-probabilities\" payload"
  , "        <*> fieldValue \"observation-hash\" payload"
  , "        <*> fieldValue \"replay-cursor\" payload"
  , "        <*> fieldValue \"timestamp-ns\" payload"
  , "  | otherwise = Nothing"
  , ""
  , "parseRlReplayFrame :: String -> Maybe RlReplayFrame"
  , "parseRlReplayFrame payload"
  , "  | fieldValue \"kind\" payload == Just \"RlReplayFrame\" ="
  , "      renderRlReplayFrame"
  , "        <$> fieldValue \"experiment-hash\" payload"
  , "        <*> fieldValue \"replay-id\" payload"
  , "        <*> fieldValue \"environment\" payload"
  , "        <*> intField \"episode\" payload"
  , "        <*> intField \"step\" payload"
  , "        <*> intField \"action\" payload"
  , "        <*> numberField \"reward\" payload"
  , "        <*> boolField \"done\" payload"
  , "        <*> numberListField \"observation\" payload"
  , "        <*> numberListField \"next-observation\" payload"
  , "        <*> fieldValue \"policy-version\" payload"
  , "        <*> fieldValue \"observation-hash\" payload"
  , "        <*> fieldValue \"timestamp-ns\" payload"
  , "  | otherwise = Nothing"
  , ""
  , "parseTuneTrialFrame :: String -> Maybe TuneTrialFrame"
  , "parseTuneTrialFrame payload"
  , "  | fieldValue \"kind\" payload == Just \"TuneTrialFrame\" ="
  , "      renderTuneTrialFrame"
  , "        <$> fieldValue \"sweep-id\" payload"
  , "        <*> intField \"trial-index\" payload"
  , "        <*> intField \"trial-seed\" payload"
  , "        <*> numberField \"objective\" payload"
  , "        <*> boolField \"pruned\" payload"
  , "        <*> fieldValue \"sampler\" payload"
  , "        <*> fieldValue \"scheduler\" payload"
  , "        <*> fieldValue \"pruner\" payload"
  , "        <*> fieldValue \"parameters-json\" payload"
  , "        <*> fieldValue \"checkpoint-sha\" payload"
  , "  | otherwise = Nothing"
  , ""
  , "parseTuneSweepDoneFrame :: String -> Maybe TuneSweepDoneFrame"
  , "parseTuneSweepDoneFrame payload"
  , "  | fieldValue \"kind\" payload == Just \"TuneSweepDoneFrame\" ="
  , "      renderTuneSweepDoneFrame"
  , "        <$> fieldValue \"sweep-id\" payload"
  , "        <*> intField \"trials-completed\" payload"
  , "        <*> intField \"trials-pruned\" payload"
  , "        <*> numberField \"best-objective\" payload"
  , "        <*> fieldValue \"promoted-checkpoint-sha\" payload"
  , "  | otherwise = Nothing"
  , ""
  , "fieldValue :: String -> String -> Maybe String"
  , "fieldValue key payload ="
  , "  Array.head"
  , "    ( Array.mapMaybe"
  , "        (String.stripPrefix (Pattern (key <> \": \")) <<< String.trim)"
  , "        (String.split (Pattern \"\\n\") payload)"
  , "    )"
  , ""
  , "intField :: String -> String -> Maybe Int"
  , "intField key payload ="
  , "  fieldValue key payload >>= Int.fromString"
  , ""
  , "numberField :: String -> String -> Maybe Number"
  , "numberField key payload ="
  , "  fieldValue key payload >>= Number.fromString"
  , ""
  , "intListField :: String -> String -> Maybe (Array Int)"
  , "intListField key payload ="
  , "  case fieldValue key payload of"
  , "    Just raw | String.trim raw == \"\" -> Just []"
  , "    Just raw -> traverse (Int.fromString <<< String.trim) (String.split (Pattern \",\") raw)"
  , "    Nothing -> Nothing"
  , ""
  , "numberListField :: String -> String -> Maybe (Array Number)"
  , "numberListField key payload ="
  , "  case fieldValue key payload of"
  , "    Just raw | String.trim raw == \"\" -> Just []"
  , "    Just raw -> traverse (Number.fromString <<< String.trim) (String.split (Pattern \",\") raw)"
  , "    Nothing -> Nothing"
  , ""
  , "stringListField :: String -> String -> Maybe (Array String)"
  , "stringListField key payload ="
  , "  case fieldValue key payload of"
  , "    Just raw | String.trim raw == \"\" -> Just []"
  , "    Just raw -> Just (map String.trim (String.split (Pattern \",\") raw))"
  , "    Nothing -> Nothing"
  , ""
  , "boolField :: String -> String -> Maybe Boolean"
  , "boolField key payload ="
  , "  case fieldValue key payload of"
  , "    Just \"True\" -> Just true"
  , "    Just \"False\" -> Just false"
  , "    Just \"true\" -> Just true"
  , "    Just \"false\" -> Just false"
  , "    _ -> Nothing"
  , ""
  , "renderBoolFlag :: Boolean -> String"
  , "renderBoolFlag flag ="
  , "  if flag then \"True\" else \"False\""
  , ""
  , "renderIntList :: Array Int -> String"
  , "renderIntList values ="
  , "  String.joinWith \",\" (map show values)"
  , ""
  , "renderNumberList :: Array Number -> String"
  , "renderNumberList values ="
  , "  String.joinWith \",\" (map show values)"
  , ""
  , "endpoints :: Array Endpoint"
  , "endpoints ="
  , "  [ { name: \"RunCommand\", method: \"POST\", path: \"/api/runs/{runId}/command\" }"
  , "  , { name: \"InferenceRun\", method: \"POST\", path: \"/api/inference\" }"
  , "  , { name: \"GenericInference\", method: \"POST\", path: \"/api/inference/generic\" }"
  , "  , { name: \"UploadImage\", method: \"POST\", path: \"/api/images\" }"
  , "  , { name: \"CheckpointCompare\", method: \"POST\", path: \"/api/checkpoints/compare\" }"
  , "  , { name: \"Connect4Move\", method: \"POST\", path: \"/api/connect4/move\" }"
  , "  , { name: \"MetricsStream\", method: \"GET\", path: \"/api/ws\" }"
  , "  , { name: \"TrainingStream\", method: \"GET\", path: \"/api/ws/training\" }"
  , "  , { name: \"RlStream\", method: \"GET\", path: \"/api/ws/rl\" }"
  , "  , { name: \"TuneStream\", method: \"GET\", path: \"/api/ws/tune\" }"
  , "  , { name: \"InferenceStream\", method: \"GET\", path: \"/api/ws/inference\" }"
  , "  ]"
  ]
